### ISSUE TITLE
Inequality constraints

### ISSUE THREAD

**Issue by bthakur21** [dynamicslab/pysindy#109]
Hi! Is there a way of implementing inequality constraints (Cw<=0) in the constrained SR3 algorithm? For example, if I want some coefficient to be always negative, how can I implement something like Cw < 0?

**Comment by briandesilva** [comment]
Our current implementation only supports equality constraints Cw=0. @akaptano are you aware of any work that generalizes constrained SR3 to inequality constraints?

**Comment by briandesilva** [comment]
If you wanted *all* the coefficients to be negative, you could implement a custom optimizer using a non-negative least squares algorithm (e.g. Scipy's [nnls](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.nnls.html#scipy.optimize.nnls)) and reverse the sign of the data to which you fit. If you're interested in this approach, I can give you more information on how to set up the custom optimizer. It should only be a few lines of code. But it sounds like you might want only a few coefficients to be negative so this may not be useful.

**Comment by akaptano** [comment]
this is a good question. I don't think Cw <= d is a straightforward change from the version of Cw = d implemented in constrained SR3 or the trapping SR3 in #106. However, the trapping SR3 has a version that uses cvxpy to solve the optimization problem, and cvxpy does allow for inequality constraints. 

So this should be super easy. Switch to the trapping SR3 branch, set relax_optim=False when you call the optimizer, and edit the _solve_direct_cvxpy function in trapping_sr3.py under /pysindy/optimizers/ from:
prob = cp.Problem(cp.Minimize(cost), [self.constraint_lhs @ xi == self.constraint_rhs])
to:
prob = cp.Problem(cp.Minimize(cost), [self.constraint_lhs @ xi <= self.constraint_rhs]).

There are some funny features in this branch because it is geared for quadratic nonlinear models, but it can be used like normal constrained SINDy if you can navigate through all the options. Let me know if you need some help.

Best,
Alan

**Comment by bthakur21** [comment]
Thank you Alan and Brian for your suggestions. I will try them and get back to you.

**Comment by bthakur21** [comment]
@akaptano I have been trying to use trapping SR3 algorithm for implementing inequality constraints. I have made the changes you mentioned in the trapping_sr3.py. I haven't been able to navigate through all the options of the algorithm yet but the convergence seems to be a bit slow if I don't choose the options correctly. As a simple test I tried to impose the inequality constraints in the example of Lorenz system given in trapping_sr3.py. In the equation z' = x y - 8/3 z, I am trying to constraint the coefficient of xy to be less than zero. This constraint is not correct but I am trying to see if trapping SINDy would implement it anyway. It doesn't seem like it. I am not sure if I am doing something wrong in incorporating the constraint or the constraint is not implemented because it is incorrect. Here's the code:
import numpy as np
from scipy.integrate import odeint
import pysindy as ps
from pysindy.optimizers import TrappingSR3
lorenz = lambda z,t : [10*(z[1] - z[0]),
                       z[0]*(28 - z[2]) - z[1],
                       z[0]*z[1] - 8/3*z[2]]
### Lorenz equations
### x' = 10 (y - x)       ----- (1)
### y' = x (28 - z) - y   ----- (2)
### z' = x y - 8/3 z      ----- (3)  

t = np.arange(0,4,.002)
x = odeint(lorenz, [-8,8,27], t)


### Constraints
### First: coefficient of y in the equation for first target variable (eq(1)) is <= 10
### Second: coefficient of xy in the equation for first target variable (eq(1)) is <= 0

constraint_zeros = np.array([10, 0])
constraint_matrix = np.zeros((2, 30))

constraint_matrix = np.array([[0, 0., 1., 0., 0., 0., 0., 0., 0.,0.,0.,0., 0., 0., 0., 0., 0.
                               , 0., 0., 0.,0.,0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0.,0., 0., 0., 0., 0., 0., 0., 0., 0.,0.,0., 0., 0., 0., 0., 0., 0., 0., 
        0.,0.,0., 0., 0., 0., 1., 0., 0., 0., 0.],
       ])
    
feature_names = ['x', 'y', 'z']

opt = ps.TrappingSR3(threshold=0.5,
            constraint_lhs=constraint_matrix,
            constraint_rhs=constraint_zeros,
            constraint_order="target"
                       )
model = ps.SINDy(optimizer=opt,feature_library=ps.PolynomialLibrary(degree=2),
       differentiation_method=ps.FiniteDifference(drop_endpoints=True),
                 feature_names=feature_names)
model.fit(x, t=t[1]-t[0])
model.print()

Thanks!

**Comment by akaptano** [comment]
In ps.TrappingSR3, it should be:
opt = ps.TrappingSR3(threshold=0.5,
constraint_lhs=constraint_matrix,
constraint_rhs=constraint_zeros,
constraint_order="target",
relax_optim=False
)

Otherwise the default is to use the non-cvxpy version, and you want to use the cvxpy version with the inequality constraints. Let me know if that works.

**Comment by bthakur21** [comment]
@akaptano Thanks! It seems to work but there is an issue. 
I am taking the following constraint matrix

constraint_zeros = np.array([10, -1])
constraint_matrix = np.zeros((2, 30))

constraint_matrix = np.array([[0, 0., 1., 0., 0., 0., 0., 0., 0.,0.,0.,0., 0., 0., 0., 0., 0.
, 0., 0., 0.,0.,0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0.,0., 0., 0., 0., 0., 0., 0., 0., 0.,0.,0., 0., 0., 0., 0., 0., 0., 0.,
0.,0.,0., 0., 0., 0., 1., 0., 0., 0., 0.],
])

Instead of implementing the second inequality constraint (i.e. coefficient of xy <= -1) on the equation for dz/dt, the inequality seems to be implemented on the equation for dx/dt.  Trapping algorithm gives the following model

x' = -62.395 1 + 29.554 x + -14.516 y + 7.265 z + 0.957 x^2 + -0.997 x y + -1.132 x 
        z + 0.272 y^2 + 0.723 y z + -0.208 z^2
y' = 27.991 x + -0.996 y + -1.000 x z
z' = 0.003 1 + 0.006 x + -0.003 y + -2.666 z + 0.001 x^2 + 0.999 x y

If I use Constrained SR3 algorithm instead which implements equality constraints only, then the same constraints give the model

x' = -10.000 x + 10.000 y
y' = 27.990 x + -0.997 y + -1.000 x z
z' = -105.186 1 + 12.476 x + -7.496 y + 10.438 z + 2.055 x^2 + -1.000 x y + -0.317 x z + 0.496 y^2 + -0.397 z^2

Here the "equality" constraint is imposed on the "xy" feature of dz/dt as I wanted. 

Is the constraint matrix defined differently in trapping_sr3 than the constrained_SR3 algorithm?

**Comment by akaptano** [comment]
Thanks, I'll give this a try in the next few hours and report back with findings

**Comment by akaptano** [comment]
Okay, the quick answer here is that everything works if you use constraint_order="feature" in the trapping SR3 routine. This fix is more complicated than I hoped, I think much of the routine presumes the feature order, and so there is some reindexing to do make it work with "target". 

For now, I pushed a few changes to the code and added two new tests in /test/optimizers/test_optimizers.py at the bottom -- these show how to properly use the trapping SR3 optimizer with the inequality constraints (heads up to @briandesilva). Update your branch and let me know if you have any more issues.

**Comment by bthakur21** [comment]
It seems to be working well. Thank you very much. There is one thing that I noticed. Since the constraints are defined as Cw <= d, the inequality is not strict. So it seems that there are going to be a few cases where the constraint is imposed as an equality constraint. For instance, in the example of Lorenz system, if I take the following constraint, it is implemented as an equality constraint for any value of "b<0". The coefficient seems to be taking whatever value is assigned to "b".
However for "a", inequality is imposed. 
a = 9
b = -2
constraint_rhs = np.array([a, b])
constraint_matrix = np.zeros((2, 30))
constraint_matrix[0, 6] = 1.0
constraint_matrix[1, 1] = 1.0

**Comment by akaptano** [comment]
My guess is that the best solution happens to be b = whatever. Try b = -10000 or something crazy, or a different ode system, and see if it still gives you this behavior. You could also do b <= - delta for some small delta > 0. If this is too annoying, I'll make it into a strict inequality constraint in the next few days, which should be a matter of changing the two cvxpy lines in trapping_sr3 from <= to <

**Comment by bthakur21** [comment]
Thanks. With b=-10000, the coefficient comes out to be close to but less than it (coef. = -10021). For  b <= - delta, if delta is very small (of the order of 10^-3 or smaller), then the coef. becomes zero and if delta is more than that (of the order of 10^-2 or more), then this behavior seems to be there. I tried changing the cvxpy lines in trapping_sr3 from <= to < but I think cvxpy doesn't allow that. I am getting an error:  "Strict inequalities are not allowed" in cvxpy\expressions\expression.py.

I think in most cases the trapping algorithm is able to implement the inequality constraints. For the cases it can't, it maybe because the constraints are incorrect.

**Comment by akaptano** [comment]
Okay it sounds like this is the best cvxpy can give us. I'm going to mark this as closed for now.
