### ISSUE TITLE
[BUG] Multiple PySINDy models on one kernel overwriting each other.

### ISSUE THREAD

**Issue by friesb** [dynamicslab/pysindy#116]
Loading two separate sets of data each with multiple trajectories and attempting to use SINDy on each set of data. However, when using [model_2].fit(data_2) this overwrites the first model. (see example code below)
### Reproducing code example:

```python
import pysindy as ps

degree= 2
data_u = # [load multiple trajectories for model 1]
data_v = # [load multiple trajectories for model 2]

t=np.linspace(0,2,1500) # same dt for each model

poly_library = ps.PolynomialLibrary(include_interaction=False, degree = degree)
model_u_PS = ps.SINDy(feature_library = poly_library)
model_u_PS.fit(data_u, t = dt, multiple_trajectories = True)

poly_library = ps.PolynomialLibrary(include_interaction=False, degree = degree)
model_v_PS = ps.SINDy(feature_library = poly_library)
model_v_PS.fit(data_v, t = dt, multiple_trajectories = True)

model_u_PS.print()
print('')
model_v_PS.print()
```

### Error message:
** No error message** 
model_u_PS is the same as model_v_PS

### PySINDy/Python version information:
0.14.1 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]

**Comment by briandesilva** [comment]
I'm unable to reproduce this bug using your code and loading my own sets of trajectories. A couple things to check:
* Are you sure `data_u` and `data_v` contain different data?
* Does this issue persist with newer versions of PySINDy?

**Comment by friesb** [comment]
Yes the datasets were different but the issue does not persist on newer
versions.

Thank you
