### ISSUE TITLE
SINDy-PI: a robust algorithm for parallel implicit sparse identification of nonlinear dynamics

### ISSUE THREAD

**Issue by alokwarey** [dynamicslab/pysindy#117]
Any plans to include SINDy-PI in PySINDy?

**Comment by akaptano** [comment]
Not currently. Basically Kadierdan is the expert, so we have been waiting to see if he bothers to include this. That being said, there is already a repo at https://github.com/dynamicslab/SINDy-PI  (albeit in matlab), so it would probably be straightforward to incorporate into PySINDy. I'll poke around and get a sense for me how easy this would be.

**Comment by alokwarey** [comment]
Thanks! It would great to have it in PySINDy.

**Comment by akaptano** [comment]
I have started implementing a basic sindy-pi version in PySINDy. Should have this done and polished in a week or two. See #101 for details + updates.

**Comment by alokwarey** [comment]
Thanks!
