### ISSUE TITLE
Is there a way to have a different function library for the input term(s)?

### ISSUE THREAD

**Issue by fahimabdullah1** [dynamicslab/pysindy#118]
For my system, I am only interested in linear control terms. Therefore, I would like something like f(x,u) = f(x) + c*u where c is a constant to be found via sparse identification along with the f(x). However, so far, I have not found a way to pass a different library (not even library, just a linear u term) to do this. Is there a way to do this or some small modification I can make to achieve it?

**Comment by akaptano** [comment]
This is something I have been considering adding recently. You are correct, I believe the only functionality right now is that the library becomes x * u, x ^2 * u, etc. so the only way to get a term like c * u right now is to start with a library function that includes the constant function, and then this will be multiplied by u. Unfortunately, as you mentioned, you also get all the other library functions * u. I'll add a way to add custom functions of u in the next few days.

**Comment by fahimabdullah1** [comment]
Yes, right now, the u is treated just like another variable. So it takes all the functions in the library as well as interactions, hugely increasing the number of functions in the library. For example, in my 2 state system with a library of polynomials up to quadratic, I have 10 functions instead of 6 since all of u, u^2, x0 u, x1 u, get included in the library.

More than computationally speaking, my problem is the system tries to identify all those other 3 terms and messed up the solution due to trying so many irrelevant functions that might actually even be a good fit sometimes.

Thanks so much for considering adding it. I will eagerly wait for the update. Would I just have to update the package or reinstall it when you make the change?

**Comment by akaptano** [comment]
You will need to use the github repo directly for now. Download the repo, switch to the "sindypi" branch, and in a few days I will put in the functionality you want. Then all you will need to do is a "git pull" from your local branch.

**Comment by akaptano** [comment]
Okay, after some poking around, I think the best option is to just provide an option for a single control term of c * u, rather than a custom library for u. The problem with the latter approach is that this means you have to specify both 1) the library of functions for u, and 2) which terms it should interact with. For instance, should we include terms like u * x0 but not u * x1? You can see how this gets quite complicated if u and x are not 1-dimensional. If you need terms like u^2, u * x0, u * x1, etc. the best solution is probably to include all these terms and then train with as much data as possible to help distinguish fits in the optimization. I'll add this in a few days, thanks for your patience.

**Comment by akaptano** [comment]
The sindypi branch now has the "linear control" version working. Try out the following example and let me know if you have any issues using this:

import numpy as np
from scipy.integrate import odeint
from pysindy.utils import lorenz, lorenz_control, lorenz_u
import pysindy as ps

# Generate measurement data
dt = .002

t_train = np.arange(0, 10, dt)
x0_train = [-8, 8, 27]
x_train = odeint(lorenz_control, x0_train, t_train)
u_train = lorenz_u(t_train)

library_functions = [
    lambda x : x,
    lambda x : x ** 2,
    lambda x,y : x * y
]
library_function_names = [
    lambda x : x,
    lambda x : x + x,
    lambda x, y : x + y
]
custom_library = ps.CustomLibrary(
    library_functions=library_functions, linear_control=True, n_control_features=u_train.shape[-1], 
    function_names=library_function_names
    )
    
model = ps.SINDy(feature_library=custom_library)
model.fit(x_train, u=u_train, t=dt, quiet=True)
model.print(precision=3)
model.coefficients()
custom_library.get_feature_names()

**Comment by fahimabdullah1** [comment]
Thank you, I totally agree that a separate library for u can make things very complicated. Moreover, in many applications, the control u is indeed applied linearly anyway. So I think this adds most of the functionality people are looking for.

I'll see if installing the package that way through github and pulls works on anaconda with windows since that's what I am using now. Otherwise, I will install on my Linux VirtualBox and let you know if it worked. Thanks!

**Comment by fahimabdullah1** [comment]
I couldn't figure out the way in Windows/Anaconda, so I was trying to repeat your example in my Linux. However, I wasn't able to successfully install this version. I installed once with pip and once by cloning the git repository so using both ways mentioned in the readme on Github. The version was 1.4.3, which seems to be the one you released yesterday. However, after modifying the example a bit because I first got an error trying to use pysindy.utils for the lorenz functions, I was still getting this error:

`TypeError: __init__() got an unexpected keyword argument 'linear_control'`

**Comment by akaptano** [comment]
Can you post your code? It's hard for me to tell what is going on here. And yes, the only way you can get access to this feature right now is to 1) clone the github repo and then 2) switch to the sindypi branch. You can use git branch -a to check which branch you are using and git checkout "name-of-branch" to switch to another branch.

**Comment by fahimabdullah1** [comment]
Sure, I just modified your code to not run into the error in the previous comment. I just explicitly defined the ODE instead of trying to get it from the .utils package. If I just use your code, I get this error:
`ImportError: cannot import name 'lorenz' from 'pysindy.utils' (C:\Users\[Username]\anaconda3\lib\site-packages\pysindy\utils\__init__.py)`
So I just added an ODE definition as you see in the code attached at the end. The main issue, however, is the error message,
`TypeError: __init__() got an unexpected keyword argument 'linear_control'`

I think the issue is I am not used to using branches and just use the package by installing pysindy using pip or the other method described in the readme. So I am using it as a package. I will have to look into how to use it with the git branch, etc.


`import numpy as np
from scipy.integrate import solve_ivp
import pysindy as ps

def lorenz_u(t, z):
    u = lambda t : np.sin(2 * t)
    return [
        10 * (z[1] - z[0]) + u(t) * 6,
        z[0] * (28 - z[2]) - z[1],
        z[0] * z[1] - 8 / 3 * z[2]
        ]

dt = .002

t_train = np.arange(0, 10, dt)
x0_train = [-8, 8, 27]
x_train = solve_ivp(lorenz_u, [0, 10], x0_train, t_eval = t_train).y.T
u_train = np.sin(2 * t_train)

library_functions = [
lambda x : x,
lambda x : x ** 2,
lambda x,y : x * y
]
library_function_names = [
lambda x : x,
lambda x : x + x,
lambda x, y : x + y
]
custom_library = ps.CustomLibrary(
library_functions=library_functions, linear_control=True, n_control_features=u_train.shape[-1],
function_names=library_function_names
)

model = ps.SINDy(feature_library=custom_library)
model.fit(x_train, u=u_train, t=dt, quiet=True)
model.print(precision=3)
model.coefficients()
custom_library.get_feature_names()`

**Comment by akaptano** [comment]
Yes, the issue is that you are on the "main" branch, rather than the sindypi branch. Unfortunately the solution is either 1) learn to use git branches or 2) wait until we "merge" the sindypi branch with the main branch, which might be a few weeks, or a few months. I'll talk to Brian about doing a merge soon.

**Comment by fahimabdullah1** [comment]
Thank you for the clarification. I will look into that for now. There is no way to just copy & paste only the modified files from the repository into my package installation since I am assuming it's just a few lines?

**Comment by briandesilva** [comment]
Here are commands you can follow to use Alan's sindy-pi branch on linux (assuming PySINDy is not already installed—if it is, you'll want to run `pip uninstall pysindy` before the following steps):

```bash
git clone https://github.com/dynamicslab/pysindy.git
cd pysindy
git fetch origin
git checkout -b sindy-pi origin/sindy-pi
pip install -e .
``` 
The third line grabs all the remote branches, the fourth creates a new local branch `sindy-pi` paralleling Alan's `sindy-pi` branch, and the last command installs PySINDy (the `-e` flag means that any changes you make to the source code, such as switching branches, will be reflected when you next import pysindy). To switch back to the main branch use `git checkout master`.

**Comment by akaptano** [comment]
You can, but there were a few more changes than you might expect. If you already have the github repo downloaded, the easiest thing to do is switch to the sindypi branch. In total, the steps here would be (on a terminal):
1) git clone https://github.com/dynamicslab/pysindy.git
2) Change your directory into the github repo... "cd pysindy/"
3) git checkout sindy-pi
4) Make sure your code is using this repo and not some other installed version of PySINDy by 
export PYTHONPATH=$PYTHONPATH:~/path/to/this-pysindy-repo/

**Comment by akaptano** [comment]
Okay, Brian has the better way to do it. Let us know if you are still having issues.

**Comment by fahimabdullah1** [comment]
Thank you so much, both of you! I have installed it successfully now and am able to run the example Alan posted above. I believe this is the expected output?
```
(x0)' = -9.999 x0 + 9.999 x1 + 1.000 u0
(x1)' = 27.987 x0 + -0.997 x1 + -1.000 x0x2
(x2)' = -2.666 x2 + 1.000 x0x1 + -1.000 u1
```

**Comment by akaptano** [comment]
That looks right. And I think the example below is also correct... I have implemented it only for a pure custom library. There is an easy fix though. Instead of using PolynomialLibrary(degree=3) you can just make another custom library:
library_functions = [
    lambda x : x,
    lambda x : x * x,
    lambda x, y : x * y,
    lambda x : x * x * x,
    lambda x, y : x * y * y
    lamda x, y, z : x * y * z
    ]
Note that I might be getting the ordering of the terms differently here than how it is defined in the default polynomial library.

**Comment by fahimabdullah1** [comment]
Thank you for clarifying that. When making a fully custom library as you did above,

1. Is the bias "1" term always included or do I have to add it in?
2. Your example library above is of 3rd order polynomials, I assume. So you only need to specify x*y*y to cover both x^2 y and xy^2 interaction terms? I had both in my library when trying to replicate the polynomial library like this.

**Comment by akaptano** [comment]
1. No, you can add in the bias term as lambda x : 1, I think. This should be shown in example 1 in the /examples/ directory.
2. Yes, xyy covers it because both x and y loop through all of x0, ..., xN so xxy just repeats terms.

**Comment by fahimabdullah1** [comment]
> Here are commands you can follow to use Alan's sindy-pi branch on linux (assuming PySINDy is not already installed—if it is, you'll want to run `pip uninstall pysindy` before the following steps):
> 
> ```shell
> git clone https://github.com/dynamicslab/pysindy.git
> cd pysindy
> git fetch origin
> git checkout -b sindy-pi origin/sindy-pi
> pip install -e .
> ```
> 
> The third line grabs all the remote branches, the fourth creates a new local branch `sindy-pi` paralleling Alan's `sindy-pi` branch, and the last command installs PySINDy (the `-e` flag means that any changes you make to the source code, such as switching branches, will be reflected when you next import pysindy). To switch back to the main branch use `git checkout master`.

Hi,

Sorry to reopen this. Let me know if I should open a new issue instead. I found the documentation now had some new "greedy algorithms", which didn't work when I tried them. It seemed they were new in v1.5.1, which could be downloaded via pip now. I uninstalled the sindy-pi branch installation above (v1.4.4 or something) and reinstalled v1.5.1 via pip. However, although the greedy algorithms worked, the linear_control, which this whole thread was about, did not work again. I get

`TypeError: __init__() got an unexpected keyword argument 'linear_control'`

When I tried reinstalling via the instructions above, assuming it would install the latest sindy-pi branch, when I run line 4, I get this error:

`fatal: 'origin/sindy-pi' is not a commit and a branch 'sindy-pi' cannot be created from it`

I did ignore it and run line 5 (pip install -e .), which seems to have worked and it says I have installed 1.5.2.dev1+gdfcdb37. However, the actual error (TypeError: __init__()... above) remains. Was this change not merged into the new version perhaps?

**Comment by akaptano** [comment]
Sorry I didn't update this when the new release came out. We have deleted the sindy-pi branch because all the new features are included on the master branch now. 

You are right, we have gotten rid of the "linear_control" option since this was a hack. Instead, we have added a much more flexible formulation by allowing you to build completely separate SINDy libraries for the control variables. See the "GeneralizedLibrary" class in the new Example 15. To build a quadratic polynomial library with a linear control input you can adapt that example straightforwardly:

# Initialize two libraries
poly_library = ps.PolynomialLibrary()
control_library = ps.PolynomialLibrary(degree=1)

# Initialize the default inputs, i.e. each library
# uses all the input variables, (5 inputs and 2 libraries here)
inputs_temp = np.tile([0, 1, 2, 3, 4], 2)
inputs_per_library = np.reshape(inputs_temp, (2, 5))

# Don't use the u0, u1 inputs for generating the quadratic library
inputs_per_library[1, 3] = 1
inputs_per_library[1, 4] = 1

# Don't use the x, y, z inputs for generating the linear library
inputs_per_library[2, 0] = 0
inputs_per_library[2, 1] = 0
inputs_per_library[2, 2] = 0

# Optional: tensor two polynomial libraries together (think you don't want this?)
# tensor_array = [[1, 1]]

# Initialize this generalized library, all the work hidden from the user!
generalized_library = ps.GeneralizedLibrary(
    [poly_library, control_library],
    tensor_array=tensor_array,
    inputs_per_library=inputs_per_library,
)

# Fit the model and print the library feature names to check success
model = ps.SINDy(feature_library=generalized_library, optimizer=ps.STLSQ())
model.fit(x_train_control, u=u_train_control, t=dt, quiet=True)
model.print()
model.get_feature_names

**Comment by fahimabdullah1** [comment]
> Sorry I didn't update this when the new release came out. We have deleted the sindy-pi branch because all the new features are included on the master branch now.
> 
> You are right, we have gotten rid of the "linear_control" option since this was a hack. Instead, we have added a much more flexible formulation by allowing you to build completely separate SINDy libraries for the control variables. See the "GeneralizedLibrary" class in the new Example 15. To build a quadratic polynomial library with a linear control input you can adapt that example straightforwardly:
> 
> ### Initialize two libraries
> poly_library = ps.PolynomialLibrary() control_library = ps.PolynomialLibrary(degree=1)
> 
> ### Initialize the default inputs, i.e. each library uses all the input variables, (5 inputs and 2 libraries here)
> inputs_temp = np.tile([0, 1, 2, 3, 4], 2) inputs_per_library = np.reshape(inputs_temp, (2, 5))
> 
> ### Don't use the u0, u1 inputs for generating the quadratic library
> inputs_per_library[1, 3] = 1 inputs_per_library[1, 4] = 1
> 
> ### Don't use the x, y, z inputs for generating the linear library
> inputs_per_library[2, 0] = 3 inputs_per_library[2, 1] = 3 inputs_per_library[2, 2] = 3
> 
> ### creates separate quadratic library for x, y, z and separate linear library for control inputs
> generalized_library = ps.GeneralizedLibrary( [poly_library, control_library], inputs_per_library=inputs_per_library, )
> 
> ### Fit the model and print the library feature names to check success
> model = ps.SINDy(feature_library=generalized_library, optimizer=ps.STLSQ()) model.fit(x_train_control, u=u_train_control, t=dt, quiet=True) model.print() model.get_feature_names

Thank you akaptano. I just had to reduce the first indices of the inputs_per_library by 1 since they should be 0 and 1 now I believe and it worked!

**Comment by akaptano** [comment]
Yep! Nice catch. Glad to hear it is working!
