### ISSUE TITLE
[BUG] Problem finding model of a simple discrete system with controls

### ISSUE THREAD

**Issue by achary** [dynamicslab/pysindy#122]
When using synthetically produced data of a simple discrete system with control *u*:

```
x[k+1] = (1-a)*x[k] + a*u[k]
```

SINDYc reports a model that 'stucks' at initial conditions. I've tried to compile both examples from the docs: one on discrete time systems and one on including controls.

### Reproducing code example:

```python
# Python 3.8 env. prepared with:
# pip install numpy matplotlib pysindy
# 
import matplotlib.pyplot as plt
import pysindy as ps
import numpy as np

num_points = 1000
num_periods = 3

t = np.linspace(0,100,num_periods*num_points)

# constructing stepped control signal u
u1 = np.zeros(400)
u2 = np.ones(num_points - len(u1))
u = []
for i in range(0, num_periods):
    u.append(u1)
    u.append(u2)
u = np.hstack(u)

x0 = .0
a = 0.01

# Discrete system x[k+1] = (1-a)*x[k] + a*u[k] 
def system(x0, u):
    x = np.zeros(len(u))
    x[0] = x0
    for k in range(1,len(u)):
        x[k] = (1-a)*x[k-1] + a*u[k-1]
    return x
    
# synthetic data of system response: initial conditions and controls
x = system(x0, u)

plt.figure()
plt.plot(t,u,label="step control signal (input)")
plt.plot(t,x,label="system output")
plt.xlabel('t')
plt.ylabel('u')
plt.legend()
plt.title("signals")
# plt.show() if not in jupyter

# Instantiate and fit the SINDyc model
poly_library = ps.PolynomialLibrary(include_interaction=False, degree = 3)
model = ps.SINDy(discrete_time=True, feature_library = poly_library)
model.fit(x, u=u ,t=t)
model.print()

xs = model.simulate(x0, t=3*num_points, u=u)

plt.figure()
plt.plot(t,u,label="step control signal (input)")
plt.plot(t,xs,label="system output (by SINDy)")
plt.xlabel('t')
plt.ylabel('u')
plt.legend()
plt.title("signals")
# plt.show() if not in jupyter


```

### Error message:

Plot showing control signal *u* and synthetically produced system outputs is:

![image](https://user-images.githubusercontent.com/1964880/132589022-037c7cab-e735-4e09-8c68-872d5ebe301e.png)

The printed SINDy model is far from anything that captures the dynamics:

```
x0[k+1] = 1.000 x0[k]
```

and the simulation result on a plot:

![image](https://user-images.githubusercontent.com/1964880/132589135-51ee2236-5594-4250-8719-7195e90e5d29.png)

which is nothing but flat `x0`. With polynomials library, I expected the method to capture something that reassembles the original system a bit better (and at least some  dependency on *u* as well).

In the manual (readthedocs) I was able to find  a section with example of a discrete system, as well as a section about SINDy with controls, but direct example of linking the two. Is this combination supported?

### PySINDy/Python version information:

```
1.4.3 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
```

**Comment by akaptano** [comment]
Sorry for the slow response, working on this now.

**Comment by achary** [comment]
Many thanks for a useful reply.
Yup, that makes a difference now and brings it to where I wanted it to be. (I admit I would not figure this out on my own).
Yup, all makes sense, incl. the 3 z power terms of `u` for a control signal, when it's a step function like that.
Cheers.
