### ISSUE TITLE
How to encode time delay constraints?

### ISSUE THREAD

**Issue by minasouliman** [dynamicslab/pysindy#128]
Hello! I'll start off by being VERY grateful for all the awesome work that's been put into pysindy. It's been awesome to look at all the new additions and peek at some of the soon-to-come ones in the next release.

I'm looking at using pysindy to identify dynamics in an industrial process setting. These models are for the most part linear with a small subset requiring non-linearity and are typically in the form of First Order Plus Dead Time (FOPDT). I've explored the ConstrainedSR3 optimizer quite a bit because most of the problems I'm facing are where I already know the model structure, and I might even know the sign of the coefficient, and so I'm able to help pysindy out in that regard. But to get the "dead time" aspect of the model to work, I was thinking that I'd pretty much generate time-delay embeddings (similar to how it's done [here](https://arxiv.org/pdf/1608.05306.pdf)) and simply use those as part of my u-matrix. The problem comes in that I'd like to then add a constraint for each potential control variable to only pick one time-delay value. For example, if I have a target variable y and two potential control variables x1 and x2, then I'd like to generate the time-delay variables x1_10, x1_20, x1_30...where each of those are delayed in time by 10,20,30 data points. But I'd like to constrain the model to only pick one variable for x1 and one variable for x2.....is there an easy way to accomplish this with the current setup of the ConstrainedSR3 optimizer? Or is there a different approach that I should take to tackle the issue?

Thanks!

**Comment by akaptano** [comment]
So to be clear, you have something like: 
1. Control variable x1 and x2
2. Generated time-delay control variable x1_10, x1_20, etc. 
3. So total control input matrix is something like [x1, x2, x1_10, x1_20, ...]
4. Default for PySINDy is to simply concatenate these variables to the end of the target variables, so the target 
variable is now [y, x1, x2, x1_10, x1_20, ...]
5. For each model generated, only choose ONE of x1, x1_10, x1_20, etc. in the model and zero the rest. Same for x2, x2_10, x2_20, etc. 

If this is the case, you need to think about how this could be phrased as an equality or inequality constraint. It is possible but may take some thinking. If you can do so, I am happy to instruct you how to use the optimizer with such a constraint.

**Comment by minasouliman** [comment]
Thanks for the response! I've dug a bit deeper into it today and the only way that I could think of expressing this as a constraint is to introduce some sort of boolean variable and limit it to 1 per set of time-delayed inputs...unfortunately this makes the problem a  mixed integer optimization and cvxpy does not seem to like using glpk to solve it.

I'll keep hacking at it to see if I can get it to work. Thanks! closing this for now.

**Comment by akaptano** [comment]
That makes sense... and yes this is a good way to go about it generally... 1) express as constraint and then 2) figure out if cvxpy supports a solver that can solve such a problem. Let me know if you have any success and need additional help. Glad you're using some of the advanced features and feedback is always appreciated!
