### ISSUE TITLE
[BUG] recurrent "can't set attribute" error in all notebooks (3_original_paper.ipynb)

### ISSUE THREAD

**Issue by robertonuca** [dynamicslab/pysindy#129]
After creating a virtual environment and installing pysindy and related libraries I execute the jupyter blocks of provided examples but I end up every time with the same error. I report here the 3_original_paper.ipynb result.

### Reproducing code example:
```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.cm import rainbow
import numpy as np
from scipy.integrate import odeint
from scipy.io import loadmat
import pysindy as ps

# Generate training data
def f(x, t):
    return [
        -0.1 * x[0] + 2 * x[1],
        -2 * x[0] - 0.1 * x[1]        
    ]


dt = 0.01
t_train = np.arange(0, 25, dt)
x0_train = [2, 0]
x_train = odeint(f, x0_train, t_train)

# Fit the model
poly_order = 5
threshold = 0.05
model = ps.SINDy(
    optimizer=ps.STLSQ(threshold=threshold),
    feature_library=ps.PolynomialLibrary(degree=poly_order),
)
model.fit(x_train, t=dt)
model.print()
```

### Error message:
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_28144/4220616345.py in <module>
      8     feature_library=ps.PolynomialLibrary(degree=poly_order),
      9 )
---> 10 model.fit(x_train, t=dt)
     11 model.print()

~/Scaricati/sindyenv/lib/python3.8/site-packages/pysindy/pysindy.py in fit(self, x, t, x_dot, u, multiple_trajectories, unbias, quiet)
    290             warnings.filterwarnings(action, category=UserWarning)
    291 
--> 292             self.model.fit(x, x_dot)
    293 
    294         self.n_input_features_ = self.model.steps[0][1].n_input_features_

~/Scaricati/sindyenv/lib/python3.8/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    388         """
    389         fit_params_steps = self._check_fit_params(**fit_params)
--> 390         Xt = self._fit(X, y, **fit_params_steps)
    391         with _print_elapsed_time("Pipeline", self._log_message(len(self.steps) - 1)):
    392             if self._final_estimator != "passthrough":

~/Scaricati/sindyenv/lib/python3.8/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params_steps)
    346                 cloned_transformer = clone(transformer)
    347             # Fit or load from cache the current transformer
--> 348             X, fitted_transformer = fit_transform_one_cached(
    349                 cloned_transformer,
    350                 X,

~/Scaricati/sindyenv/lib/python3.8/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    347 
    348     def __call__(self, *args, **kwargs):
--> 349         return self.func(*args, **kwargs)
    350 
    351     def call_and_shelve(self, *args, **kwargs):

~/Scaricati/sindyenv/lib/python3.8/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    889     with _print_elapsed_time(message_clsname, message):
    890         if hasattr(transformer, "fit_transform"):
--> 891             res = transformer.fit_transform(X, y, **fit_params)
    892         else:
    893             res = transformer.fit(X, y, **fit_params).transform(X)

~/Scaricati/sindyenv/lib/python3.8/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    845         else:
    846             # fit method of arity 2 (supervised transformation)
--> 847             return self.fit(X, y, **fit_params).transform(X)
    848 
    849 

~/Scaricati/sindyenv/lib/python3.8/site-packages/pysindy/feature_library/polynomial_library.py in fit(self, x, y)
    168             self.include_bias,
    169         )
--> 170         self.n_input_features_ = n_features
    171         self.n_output_features_ = sum(1 for _ in combinations)
    172         return self

AttributeError: can't set attribute

### PySINDy/Python version information:
pysindy             1.4.3

**Comment by gitrobdev** [comment]
Hi Alan,

Thank you very much. I really appreciate your quick responce.

Bests,
Roberto
