### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jogisuda** [dynamicslab/pysindy#130]
Hi! I was trying to get started with PySindy in Colab, running the following simple tutorial code:

```python
import numpy as np
import pysindy as ps

t = np.linspace(0, 1, 100)
x = 3 * np.exp(-2 * t)
y = 0.5 * np.exp(t)
X = np.stack((x, y), axis=-1)  # First column is x, second is y
model = ps.SINDy(feature_names=["x", "y"])
model.fit(X, t=t)
```
However, I get the following **Error message**:

AttributeError                            Traceback (most recent call last)
<ipython-input-2-5d1f1955bcee> in <module>()
      1 model = ps.SINDy(feature_names=["x", "y"])
----> 2 model.fit(X, t=t)

6 frames
/usr/local/lib/python3.7/dist-packages/pysindy/feature_library/polynomial_library.py in fit(self, x, y)
    170         )
    171         print(n_features)
--> 172         self.n_input_features_ = n_features
    173         self.n_output_features_ = sum(1 for _ in combinations)
    174         return self

AttributeError: can't set attribute

### PySINDy/Python version information:

1.4.3 3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0]

**Comment by mathematicsofpaul** [comment]
Still experiencing this (just for other users to know).

**Comment by MattKingShoal** [comment]
Still experiencing this now too

**Comment by akaptano** [comment]
@znicolaou and @Jacob-Stevens-Haas did we not patch this in the latest release?

**Comment by Jacob-Stevens-Haas** [comment]
I thought it was patched before I came into the picture - I haven't worked on it.

Maybe it's because I made the last release a 2.0.0-rc, so pip defaults to the last stable version.

I made a 1.x branch before merging my big PR, so that should have the relevant change.  I can do a release from that branch and that should update the "stable" version pip sees.

**Comment by znicolaou** [comment]
Thanks for taking a look, @akaptano & @Jacob-Stevens-Haas! I'm out of town till next week. I can take a look at some things again soon after I get back.

**Comment by RiabovAndrew** [comment]
Hi!
Can be reproduced on 1.7.5 version. 1.7.3 is OK.
