### ISSUE TITLE
How can we add derivative with respect to time in feature library ?

### ISSUE THREAD

**Issue by AhmadSaeed2601** [dynamicslab/pysindy#136]
How can we add derivative with respect to time in feature library ?

lets say if we have three state variables x,y,z then how to add x_dot in feature library .. 
i am struggling with this one .. please let me know if there is any solution

**Comment by akaptano** [comment]
Hi Ahmad, if x_dot is in the feature library then you are solving for a system of implicit ODEs that looks like
x_dot = f(x, x_dot), which the normal SINDy method is not appropriate for. Fortunately, we have implemented the SINDy-PI library (and associated optimizer) in the upcoming PySINDy release, which does address these types of systems (https://royalsocietypublishing.org/doi/pdf/10.1098/rspa.2020.0279). The new release will be out within a week or so, and I'll let you know when that happens. The new Example 9 Jupyter notebook will show how you can use the SINDy-PI functionality.

**Comment by AhmadSaeed2601** [comment]
Thank you so much for your reply. I didn't know about this article  (
https://royalsocietypublishing.org/doi/pdf/10.1098/rspa.2020.0279). Thanks
for sharing.
I am looking forward to new release of pysindy

**Comment by akaptano** [comment]
You may also find this recent video very illuminating https://www.youtube.com/watch?v=sP8JXF9_wAs 

I'm happy to answer any questions you have about using the new SINDy-PI functionality once the new release is out (there will likely be some bugs to iron out!)

**Comment by akaptano** [comment]
Ahmad, I should have mentioned there is a second way that you can already do this, although it is kind of a hack. Before making a SINDy model you can differentiate [x, y, z] and put all the variables together [x, y, z, x_dot, y_dot, x_dot] and use this as your data. Then if you are using a polynomial library or something, polynomials in x_dot, y_dot, and z_dot will also be generated. The downside is that SINDy will also try to fit models to x_dot, y_dot, and z_dot, but you can ignore these.

**Comment by akaptano** [comment]
SINDy-PI is now implemented in the new release v1.5, so closing this for now. Feel free to reopen this if you have any issues.
