### ISSUE TITLE
Setup Github Action to run examples on master

### ISSUE THREAD

**Issue by Ohjeah** [dynamicslab/pysindy#14]
Before pushing or merging on the master branch we should make sure to verify that the examples are still working as intended.

**Comment by briandesilva** [comment]
[Potentially useful](https://github.com/marketplace/actions/run-notebook): github action for running notebooks

**Comment by Ohjeah** [comment]
Do we want to render and push back to master? Or just run the notebooks to validate them.

I think running the examples from the original SINDy paper is a bit heavy on the CI system. Would it be sufficient to only run the feature overview for now? (and maybe push the more involved examples to a different repository in which we can pin the specific version of pysindy)

**Comment by briandesilva** [comment]
Let's just worry about validating them for now.

I think it is sufficient to only run the feature overview notebook. I also like the idea of only rendering the more involved examples when we think it is necessary, e.g. when we've made substantial changes.

**Comment by Ohjeah** [comment]
Perfect. 

This issues is done by #22
