### ISSUE TITLE
ConstrainedSR3 example

### ISSUE THREAD

**Issue by buathukorala** [dynamicslab/pysindy#141]
Dear pysindy developers and users,

I am going over the  ConstrainedSR3 example that is given [here](https://pysindy.readthedocs.io/en/latest/examples/1_feature_overview.html). The example uses data from Lorenz system. In the model, polynomials of degree 2 were considered, so we have 10 feature: `['1', 'x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2', 'x2^2']` .

In the code, we have 
`n_targets = x_train.shape[1]`
`constraint_rhs = np.array([0, 28])`
`constraint_lhs = np.zeros((2, n_targets * n_features))`.

My question is related to the number of columns in the `constraint_lhs ` matrix. I thought it should have 10 columns (for the 10 features), but it has 30 columns.   

What am I missing here?

Thank you very much for your time,

Bhagya

**Comment by akaptano** [comment]
Bhagya, 

You are fitting three equations for Lorenz, each with a 10 feature library. That means that in principle you have 30 unknown coefficients, so constraint_lhs should have 30 columns. In other words, the first ten columns can be used to constrain the coefficients first equation, the next ten columns can be used to constraint the coefficients in the second equation, and so on. Let me know if you're still confused on this point.

Best,
Alan

**Comment by buathukorala** [comment]
Hello Alan,
Thank you for the quick reply; it does clarify my question. 
For some reason, I thought each row in C corresponds to a constraint in each equation.

Thanks again,
Bhagya
