### ISSUE TITLE
ensemble is not recognised by fit()

### ISSUE THREAD

**Issue by ckaskouras** [dynamicslab/pysindy#145]
Hello,

I try to use the ensembled method since I work with noisy data. But I get the following message:

`fit() got an unexpected keyword argument 'ensemble' `

I have tried it in both spyder and jypiter notebook.
Is there any case somethng has not loaded properly?
The PySINDy version I am using is: 1.4.3.

Thank you,
Christos

**Comment by akaptano** [comment]
Easy fix here... the resembling and the rest of the new functionality is only available on the newest release, PySINDy version 1.5.1.

Best,
Alan

**Comment by ckaskouras** [comment]
Thank you for you quick response Alan. I was about to close the topic but I am facing another issue now. When I try to import PySINDy I am receiving the following error.

`cannot import name 'trapezoid' from 'scipy.integrate'`.

I have tried to install scipy from the beginning but nothing changed. Do yo have any idea? 
I am sorry to bother you with stuff like that but I am relatively new to Python, if you don't hve the solution easy don't bother digging for it.

Thank you,
Christos

**Comment by akaptano** [comment]
This could happen if you have an older spicy version. Let me know what version you have.

Best,
Alan

**Comment by ckaskouras** [comment]
That was it. I installed the latest version and works fine.

Thank you,
Christos
