### ISSUE TITLE
Include the code of conduct

### ISSUE THREAD

**Issue by henrykironde** [dynamicslab/pysindy#147]
You could adopt contributor covenant from https://www.contributor-covenant.org and customize it to your needs in the docs directory.

Ref: openjournals/joss-reviews#3994

**Comment by akaptano** [comment]
Added this... if you are satisfied with the change, go ahead and close this. Thanks!

**Comment by akaptano** [comment]
I should add this was an excellent suggestion that we should have thought of! Thanks again :)
