### ISSUE TITLE
ValueError: x and y arrays must be equal in length along interpolation axis.

### ISSUE THREAD

**Issue by muguro** [dynamicslab/pysindy#160]
(This might be a NEWBIE type of question)
I get this error when using
model.simulate(X_expt_data[0,:], t=t_expt[0:100], u=U_expt[0,:])

When I train the model without control the model is simulating as expected, control is done wrong?
Any ideas

**Comment by akaptano** [comment]
Thanks for your questions. Could you post a bit more information, such as what U_expt is and what error you are receiving? Also, the example 1 Jupyter notebook has an extended example using control terms -- check that out.

**Comment by muguro** [comment]
Thanks for the response

I did a simple experiment that gathers data from a ramp input signal (control) and corresponding angle output of a robot arm.
So control and data is an array equal in size.
When fitting the model I got error below:

ValueError: x and y arrays must be equal in length along interpolation axis.


I managed to get it working
The issue was the model expected a control and time duration to be same as in

model.simulate(X_expt_data[0,:], t=t_expt[0:100], u=U_expt[0:100])

I didn't expect x and y to refer to control input.




I got two new issue: 
the simulation time (takes over 1 hour to complete one sliced time step)

model.print() returns this error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11352\2758200502.py in <module>
----> 1 model_ex.print()

D:\Python Project\Control\control\lib\site-packages\pysindy\pysindy.py in print(self, lhs, precision)
    674             Precision to be used when printing out model coefficients.
    675         """
--> 676         eqns = self.equations(precision)
    677         if isinstance(self.feature_library, SINDyPILibrary):
    678             feature_names = self.get_feature_names()

D:\Python Project\Control\control\lib\site-packages\pysindy\pysindy.py in equations(self, precision)
    659             self.model,
    660             input_features=base_feature_names,
--> 661             precision=precision,
    662         )
    663 

D:\Python Project\Control\control\lib\site-packages\pysindy\utils\base.py in equations(pipeline, input_features, precision, input_fmt)
    387 
    388 def equations(pipeline, input_features=None, precision=3, input_fmt=None):
--> 389     input_features = pipeline.steps[0][1].get_feature_names(input_features)
    390     if input_fmt:
    391         input_features = [input_fmt(i) for i in input_features]

D:\Python Project\Control\control\lib\site-packages\pysindy\feature_library\polynomial_library.py in get_feature_names(self, input_features)
    160                     if exp != 1
    161                     else input_features[ind]
--> 162                     for ind, exp in zip(inds, row[inds])
    163                 )
    164             else:

D:\Python Project\Control\control\lib\site-packages\pysindy\feature_library\polynomial_library.py in <genexpr>(.0)
    160                     if exp != 1
    161                     else input_features[ind]
--> 162                     for ind, exp in zip(inds, row[inds])
    163                 )
    164             else:

IndexError: list index out of range

**Comment by akaptano** [comment]
I'll need basically the whole example you are trying to run to debug this. From what you have shared so far, there is no way I can tell why the simulation is so slow, or why the print error is occurring.

**Comment by muguro** [comment]
[sample_data.csv](https://github.com/dynamicslab/pysindy/files/7999597/sample_data.csv)

Here's a sample data (x,y,z is output),

 I don't exactly know what part am doing wrong
