### ISSUE TITLE
[BUG] Pre-computed Derivatives

### ISSUE THREAD

**Issue by alokwarey** [dynamicslab/pysindy#161]
I am trying to use pre-computed derivatives with multiple trajectories of different lengths.
 
Code Snippet:
feature_library = ps.IdentityLibrary()
optimizer = ps.STLSQ(threshold=7e-5, fit_intercept=False)

model = ps.SINDy(differentiation_method=**None**, 
    feature_library=feature_library,
    optimizer= optimizer)

model.fit(x=x_train_multi, u = u_train_multi, t=t_train_multi, multiple_trajectories=True, **x_dot = x_dot_multi**)

SINDy(differentiation_method=**FiniteDifference()**, 
      feature_library=<pysindy.feature_library.identity_library.IdentityLibrary object at 0x000000001A124A60>,
      feature_names=['x0', 'x1', 'x2', 'u0', 'u1', 'u2', 'u3', 'u4', 'u5', 'u6',
                     'u7', 'u8'],
      optimizer=STLSQ(threshold=7e-05))

Why does it say the differentiation method is Finite Difference? Is the model using pre-computed derivatives or not?

Thanks!

**Comment by akaptano** [comment]
The differentiation method defaults to Finite Differences. If you pass x_dot to model.fit, it will use that instead. It should work when you run this code.

**Comment by alokwarey** [comment]
Ok thanks!
