### ISSUE TITLE
pysindy 1.6.3 wont install with current dependencies

### ISSUE THREAD

**Issue by rneogi** [dynamicslab/pysindy#165]
Trying in colab ..
pip install pysindy says ..

WARNING: scikit-learn 1.0.2 does not provide the extra 'alldeps'

and then, 
import pysindy as ps
gives the following error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in requires(self, extras)
   2738             try:
-> 2739                 deps.extend(dm[safe_extra(ext)])
   2740             except KeyError as e:

KeyError: 'alldeps'

The above exception was the direct cause of the following exception:

UnknownExtra                              Traceback (most recent call last)
6 frames
[/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in requires(self, extras)
   2741                 raise UnknownExtra(
   2742                     "%s has no such extra feature %r" % (self, ext)
-> 2743                 ) from e
   2744         return deps

**Comment by akaptano** [comment]
Hi, I have fixed this on the GitHub repo and will release this with the next pysindy release. The issue can also be straightforwardly fixed on your end -- change "scikit-learn[alldeps]>=0.23" in the requirements.txt file to "scikit-learn"
