### ISSUE TITLE
[BUG] Unable to extract/print optimal model when using library ensemble

### ISSUE THREAD

**Issue by fahim831** [dynamicslab/pysindy#169]
I ran into an issue with my model.print() printing a very different model from what is used in model.simulate() since I am trying to integrate the models manually outside pysindy for post-processing. After reading the documentation on the ensemble part again more closely, I think the fix is small and just a small confusion that someone might be able to clarify easily.

The key problem is: I use model.simulate() to predict and test an initial condition. The results are quite good. I then use model.print() to get the actual ODE generated by SINDy and copy it to another file where I use solve_ivp to do the integration manually instead of pysindy. Since I noticed model.simulate() uses solve_ivp anyway, the results should be same. But they're very different and, in fact, diverge in my case. After doing 1 integration step by hand for the model  printed by model.print(), I can see from the signs of the derivatives that it is definitely not what model.simulate() gives me. I checked this link (https://pysindy.readthedocs.io/en/latest/examples/13_ensembling.html) and found this, which seemed to answer the issue.

"**Default is bragging - the median coefficients over all the models is printed by model.print(). However, model.simulate and model.predict use the coefficients of the last model that was fitted! To avoid confusion, we recommend using model.coef_list everywhere and doing all the post-processing separately.**"

If I understand correctly, model.simulate() is using the last model in model.coef_list to do the integration, while model.print() is giving me some median of every coefficient? But that doesn't seem to be the case when I actually go into my variable explorer and print the last entry of the list from my model.coef_list. It is the same coefficients there (bad) and what is printed by model.print().

My other question would be, if I do identify which of the ensembles performed best, how do I then specify the SINDy model's coefficients to be those optimal ones when I use model.simulate()? Do I manually set model.coefficients() = those coefficients? Because, right now, I get the same coefficients for all of:

1. model.coefficients()
2. model.coef_list[-1]
3. model.print()

And it's not the one that is integrated in model.simulate, which is the actual good one.

The question got a bit long unfortunately, but I hope I was able to explain the issue. Since the package is still in development, I guess I get confused quite easily by small loose ends here and there. But any help will be much appreciated.

I can edit and send some of my code but I think the ones in the link above will exhibit the issue since it seems to be something to do with pysindy rather than the specific example I'm working with. Specifically, I guess the main questions are

1. How to extract the model being used by model.simulate (good)?
2. How to get model.simulate (good) to agree with model.print (bad)?
3. How to change the coefficients used in model.simulate?

For #3, I tried following the link's example and used
`library_ensemble_optimizer.coef_ = median_ensemble_coefs`
But got the error at the end when trying to use model.simulate(). Therefore, I just manually rewrote the ODE using the coefficients in median_ensemble_coefs and integrated it using solve_ivp. As you can see, all 3 are quite different, with only whatever model.simulate() is using being the "good" one. I am using the documentation chapter 13's example as it should be easier to debug with the developers.

![image](https://user-images.githubusercontent.com/44279032/164895770-41eb6791-426f-47a9-878e-3929062ee8f8.png)
![image](https://user-images.githubusercontent.com/44279032/164895773-fab11b8e-7f32-4f5c-a99a-6c0a2315a9f1.png)

### Reproducing code example:

```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
from scipy.integrate import solve_ivp
from sklearn.metrics import mean_squared_error
from pysindy.utils.odes import lorenz

def SI_ode_print(t, y):
    x1, x2, x3 = y
    dydt = np.zeros(3)
    dydt[0] = -2.064 + 3.935*x1 + -0.280*x1*x2 + 0.171*x2**2
    dydt[1] = 1.626 + 15.569*x1 + 0.263*x2 + -0.102*x3 + 0.270*x1**2 + -0.231*x1*x2 + -0.150*x1*x3 + -0.452*x2**2
    dydt[2] = 0.191 + -2.669*x3 + 0.998*x1**2
    return dydt

def SI_ode_median(t, y):
    x1, x2, x3 = y
    dydt = np.zeros(3)
    dydt[0] = -10.0233*x1 + 10.0131*x2
    dydt[1] = 27.8076*x1 + -0.92999*x2 + -0.996201*x1*x3
    dydt[2] = 0.169326 + -2.66948*x3 + 0.998441*x1*x2
    return dydt

# Ignore integration and solver convergence warnings
import warnings
from scipy.integrate.odepack import ODEintWarning
warnings.simplefilter("ignore", category=UserWarning)
warnings.simplefilter("ignore", category=ODEintWarning)

import pysindy as ps

# Seed the random number generators for reproducibility
np.random.seed(100)

# integration keywords for solve_ivp, typically needed for chaotic systems
integrator_keywords = {}
integrator_keywords['rtol'] = 1e-12
integrator_keywords['method'] = 'LSODA'
integrator_keywords['atol'] = 1e-12

dt = .002
t_train = np.arange(0, 10, dt)
t_train_span = (t_train[0], t_train[-1])
x0_train = [-8, 8, 27]
x_train = solve_ivp(lorenz, t_train_span, x0_train,
                    t_eval=t_train, **integrator_keywords).y.T

# add 1% noise to add a little complexity
# (otherwise all the models are basically correct)
rmse = mean_squared_error(x_train, np.zeros(x_train.shape), squared=False)
x_train = x_train + np.random.normal(0, rmse / 100.0, x_train.shape)

# Evolve the Lorenz equations in time using a different initial condition
t_test = np.arange(0, 15, dt)
t_test_span = (t_test[0], t_test[-1])
x0_test = np.array([8, 7, 15])
x_test = solve_ivp(lorenz, t_test_span, x0_test,
                   t_eval=t_test, **integrator_keywords).y.T

# Instantiate and fit the SINDy model
feature_names = ['x', 'y', 'z']
library_ensemble_optimizer = ps.STLSQ()
model = ps.SINDy(feature_names=feature_names,
                 optimizer=library_ensemble_optimizer)
model.fit(x_train, t=dt, library_ensemble=True, quiet=True)
model.print()
library_ensemble_coefs = model.coef_list

# %% Integrate both and plot
mean_ensemble_coefs = np.mean(model.coef_list, axis=0)
median_ensemble_coefs = np.median(model.coef_list, axis=0)
library_ensemble_optimizer.coef_ = median_ensemble_coefs
x_test_sim = model.simulate(x0_test, t_test)

sol = solve_ivp(SI_ode_print, [t_test[0], t_test[-1]], x0_test, t_eval = t_test, method='LSODA', rtol=1e-12, atol=1e-12)
t1 = sol.t
external_print_simulate = sol.y.T
sol = solve_ivp(SI_ode_median, [t_test[0], t_test[-1]], x0_test, t_eval = t_test, method='LSODA', rtol=1e-12, atol=1e-12)
external_median_simulate = sol.y.T

# %% Manual integration
x_old = x0_test
h = 1e-4
num_iter = int(15.0/h)
t_manual_EE_predict = np.arange(0, 15, h)
x_manual_EE_predict = []
for i in range(num_iter):
    x_new = x_old + h * model.predict(x_old.reshape(1,-1))
    x_old = x_new
    x_manual_EE_predict.append(x_new)
x_manual_EE_predict = np.squeeze(np.array(x_manual_EE_predict))
# Now compare the model.simulate() with a random test initial condition to the integration of the model from model.print() outputted above. The results, in my case, show the former is very good while the latter is very poor.

# %% Plots
# Plot 3D trajectory results
fig = plt.figure(figsize=(14, 5))
ax = fig.add_subplot(111, projection='3d')
plt.plot(x_test[:, 0], x_test[:, 1], x_test[:, 2], 'k', label='Real')
plt.plot(x_test_sim[:, 0], x_test_sim[:, 1], x_test_sim[:, 2], '--g', label='model.simulate()')
plt.plot(external_print_simulate[:, 0], external_print_simulate[:, 1], external_print_simulate[:, 2], '.-r', label='model.print()')
plt.plot(external_median_simulate[:, 0], external_median_simulate[:, 1], external_median_simulate[:, 2], '--b', label='manual median')
plt.plot(x_manual_EE_predict[:, 0], x_manual_EE_predict[:, 1], x_manual_EE_predict[:, 2], '--m', label='manual EE with predict')
x_min, x_max = np.amin(x_test_sim, axis=0), np.amax(x_test_sim, axis=0)
ax.set_xlim(x_min[0], x_max[0])
ax.set_ylim(x_min[1], x_max[1])
ax.set_zlim(x_min[2], x_max[2])
plt.grid(True)
# plt.ylabel(feature_names[i], fontsize=20)
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)
plt.legend()
plt.show()

# Plot trajectory results
plt.figure(figsize=(14, 5))
for i in range(3):
    plt.subplot(3, 1, i + 1)
    plt.plot(t_test, x_test[:, i], 'k', label='Real')
    plt.plot(t_test, x_test_sim[:, i], '--g', label='model.simulate()')
    plt.plot(t1, external_print_simulate[:, i], '.-r', label='model.print()')
    # plt.plot(t1, external_print_simulate[:, i], 'r', label='Mean')
    plt.plot(t_test, external_median_simulate[:, i], '--b', label='manual median')
    plt.plot(t_manual_EE_predict, x_manual_EE_predict[:, i], '--m', label='manual EE with predict')
    ax = plt.gca()
    plt.grid(True)
    if i != 2:
        ax.set_xticklabels([])
    else:
        plt.xlabel('t', fontsize=20)
    plt.ylabel(feature_names[i], fontsize=20)
    plt.xticks(fontsize=16)
    plt.yticks(fontsize=16)
    ax.yaxis.set_label_coords(-0.05, 0.75 - 0.1 * (i + 1))
    if i == 0:
        ax.legend(bbox_to_anchor=(1.01, 1.05), fontsize=18)
    if i==0:
        ax.set_ylim(-20,20)
    elif i==1:
        ax.set_ylim(-25,25)
    else:
        ax.set_ylim(5,50)
```

### Error message:
`ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 10 is different from 9)`

### PySINDy/Python version information:
1.6.3 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)]

**Comment by briandesilva** [comment]
Thanks for the detailed description of the error, and sorry for the delayed response. Let me see if I can reproduce this and get back to you (hopefully with a fix).

**Comment by akaptano** [comment]
Sorry, this one slipped through the cracks. I thought @znicolaou and I discussed this at some point but can't find the conversation now

**Comment by fahim831** [comment]
Thanks for replying. As I was waiting, I had basically tried everything I could, and one last thing I tried was to manually integrate it using explicit Euler with model.predict() to find the functions' right-hand sides. But that also gave a very different answer. So I think the issue right now is that all of them are very different: the print, predict, and simulate functions.

**Comment by fahim831** [comment]
I was just wondering if there was an update on this, or if you could at least identify what model.simulate() uses, even if you cannot print it right now. Thanks!

**Comment by berkanaydin75** [comment]
Hi everyone, i have the same problem like fahim831, using library ensemble and model.simulate. 
I am also interested in any kind of help for this issue. Thanks!

**Comment by akaptano** [comment]
So assuming you have the latest version of PySINDy, I believe that model.simulate and model.print now both use the last model that was fit. Fahim, you need to disambiguate between two things: the model and the ODE solver. You are confusing yourself to no end because you can use two different ODE solvers with the same model and one of the solvers might go numerically stable. You need to compare things with exactly the same ODE solver, with exactly the same parameters. 

Model.simulate() is not doing anything magical. It is simply a wrapper function for scipy "solve_ivp" function. The point of all this is that you will generate a bunch of models in model.coef_list, which you can average, take the median, etc., and whatever final model you use, just plug this into an ODE solver. Of course, you will need to make sure your ODE solver is doing a good job, and if model.simulate is working, just copy the model.simulate default parameters (see line 1218 here https://github.com/dynamicslab/pysindy/blob/master/pysindy/pysindy.py and the scipy page https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html). So you should completely ignore model.simulate, collect the models from model.coef_list, and integrate them however you desire.
