### ISSUE TITLE
Including derivatives of non-linear terms in PDELibrary

### ISSUE THREAD

**Issue by BMP-TUD** [dynamicslab/pysindy#170]
Hi all, 

I would like to include a non-linear term in the PDELibrary that means I want to use e.g. u³ in the form of (u³)_1111. There was already a feature request from November last year by @znicolaou for this and an other feature ([https:/github.com/dynamicslab/pysindy/issues/134]) . It seemed like you have fixed that so it can be included, but I am bit stuck and do not know how exactly it can be done. Would you mind giving a brief example on that? 

Thank you in advance for your help, 
Best wishes, 
Bartosz

**Comment by akaptano** [comment]
Hey there, Zach can show you how this can be done if you want to keep it as you wrote. Note however that (u^3)_1111 is just 3u^2 u_{1111}, which can already be generated with the PDE or WeakPDE libraries in the code. Simply use "derivative_order = 4" and include candidate library terms up to quadratic polynomials. By default, the library will take all combinations of the derivative terms and the polynomial terms, generating a term like u^2 u_{1111}

**Comment by BMP-TUD** [comment]
Hey thanks for the quick response, you are absolutely right. I will try the simple approach, but for future projects I would really appreciate if @znicolaou could provide an example. Thank you for your help, 
Best, 
Bartosz.

**Comment by znicolaou** [comment]
Sure thing! I will share a little example some time in the next week I think, but the gist is its a little complicated and experimental still. You will need to calculate the derivatives of your input data "by hand" with pysindy's FiniteDifference class, then apply whatever nonlinear transformation you want to it and reshape it correctly. You can then create a CustomLibrary with that feature and add it to a GeneralizedLibrary along with a PDELibrary.  

One kind of nonlinearities that has to be handled this way is something like (u_x)^n*(u_xx)^m, except in special cases (for example, in the Kuramoto-Sivashinki equation, a clever change of variables converts (u_x)^2 to a term u*u_x). Anyway, would be good to add an example to a notebook. I also need to finish cleaning up the new WeakPDELibrary to merge with master, and include it in that push (incidentally, note that including general nonlinear derivative terms in the weak form is an open problem still...)
