### ISSUE TITLE
LSODA Integration stuck for more than a day

### ISSUE THREAD

**Issue by shekhar477** [dynamicslab/pysindy#171]
I have been trying to integrate ODEs with 4 State Variable and 2 Control Variable, having the polynomial degree 3 characteristic using the LSODA integration with a CubicSpline interpolation technique. I have been using this script:

`model.simulate(output_reshaped[0,0:4], u = new_input_reshaped, t=t_int, integrator_kws={"method": "LSODA"}, interpolator_kws={"method": "CubicSpline"})`

The integration is stuck for a really long time, there's no error coming up for this. I am positive that my system of ODEs are stiff in nature but should the numerical integration take days to get ODEs integrated? Any suggestions would be useful.

**Comment by akaptano** [comment]
The short answer is no, it shouldn't take this long. The longer answer is that figuring out the best integrator for your odes is often difficult. Have you tried using RK45 or other solvers? Are you sure your control inputs are being properly used in the ODE? Have you tried integrating a simpler version of the model (set the control inputs to zero first, for instance)? 

Best,
Alan

**Comment by shekhar477** [comment]
I have tried most of the non-stiff system solvers and all of them fails. I know that the ODEs are stiff looking from the data, the ODEs and the Jacobi (I have attached the equations below):
`(x0)' = -40.860 x1 + -40.041 u0 + 14.894 x0^2 x1 + 31.045 x0 x1^2 + 16.129 x1^3 + -49.031 x1 x2 x3 + 51.280 x1 x3 u1 + -50.611 x2 x3 u0 + 52.873 x3 u0 u1
(x1)' = 43.519 x1 + 43.507 u0 + -47.548 x0^3 + -73.043 x0^2 x1 + 40.590 x0^2 u0 + -83.561 x0 x1^2 + -32.295 x1^3 + 62.400 x1 x2 x3 + -65.163 x1 x3 u1 + 65.308 x2 x3 u0 + -68.109 x3 u0 u1 + -14.830 u0^3
(x2)' = -27.168 x2 + 26.829 u1 + 82.052 x0^2 x3 + -90.347 x0 x1 x2 + 78.252 x0 x1 x3 + 61.264 x0 x1 u1 + -76.784 x0 x3 u0 + -26.863 x0 u0 u1 + -69.684 x1^2 x2 + 79.140 x1^2 u1 + -75.466 x1 x3 u0 + 47.520 x1 u0 u1 + 35.143 u0^2 u1
(x3)' = -55.844 x1^2 x2 + 23.995 x1^2 u1 + -70.347 x1 x2 u0 + -40.419 u0^2 u1`

Methods like RK45, DOP853, RK23, etc. will not work hence I have to resort to the implicit solvers like Radau or LSODA. But here is the problem that the integration is taking a really long time and it does not show any error. I ran an iterative time-frame integral and found out that the integration was going out of bounds, but still there was no error being shown. I cannot think of any reason why the solve_ivp would behave like this.

**Comment by akaptano** [comment]
Is this a model identified by PySINDy? This equation may not be stable with *any* numerical solver if this is the case.

**Comment by shekhar477** [comment]
Yes, this model has been generated via PySINDy. 
Why would you say that such kind of generated model may not be stable with any numerical integration method?

**Comment by akaptano** [comment]
This is not a PySINDy issue -- most dynamical models are not *physically* stable. Try integrating x_dot = x.

**Comment by shekhar477** [comment]
I am very sure the time series dynamical data that has been generated did not show any physical instability, else that would have been gauged by the software itself that was used for the dynamical simulation. 
A new observation I noticed was let’s say at threshold = K the integration was providing extreme values at t=10h. But at threshold = K+1, the extreme value generation (this means the integration keeps on going and never stops) happened at t=48h. If such variation in model.simulate is happening with just change in threshold, I believe the PySINDy is creating numerically unstable models.

**Comment by akaptano** [comment]
Agreed, I am sure the data does not show instability. My point is that any generic model you try to write down or try to find via PySINDy or other method will not be a stable one for any new initial condition you give it. If that is your goal, you need to work harder to guarantee the identified model is stable on your set of interest (for interest, on a ball around the origin). My point was not that PySINDy isn't making numerically unstable models (it is) but that any method will do so unless you get lucky, add constraints, or build in some sense of stability. This is even more the case if you allow for arbitrary control inputs.
