### ISSUE TITLE
Find PDEs using full domain (including cylinder)

### ISSUE THREAD

**Issue by ZHHYKU** [dynamicslab/pysindy#173]
Dear All, 

I tried to find PDEs for identifying Navier-Stokes. In the FIND-PDE example, it first selects a smaller domain (behind the cylinder) and then apdopts sparse sampling. But if I do sparse sampling in the whole domain (including cylinder) or in the whole domain but only removing cylinder, it can not give correct PDEs. Could you please suggest how to solve this problem?

**Comment by akaptano** [comment]
Hi there, 

Could you show some more of your work? What data are you using? Have you tried the weak formulation? 

Also, for the von Karman street it is often not wise to highly sample in the whole domain. Often the boundaries are somewhat unphysical (there is some unphysical reflection or instance), and all the dynamics are right next to the cylinder and in the vortex wake anyways.

Best,
Alan

**Comment by ZHHYKU** [comment]
Hello Alan,

Thanks for your reply! I used the data generated by IBPM (cylinder.geom & ibpm15000.bin),  and Rudy's code...(https://github.com/snagcliffs/PDE-FIND/blob/master/Examples/Navier-Stokes%20with%20clean%20data.ipynb). I made changes in 
# Cut out the portion of the data before the cylinder
xmin = 100 (change to 0)
xmax = 425 (change to 499)
ymin = 15 (change to 0)
ymax = 185 (change to 199)
This gave different PDEs. I thought the it was probably caused by the cylinder and I removed the points falled into the cylinder and got another different PDEs. 

In fact, I would like to see if it is possible to the identify the dynamics between the cylinders. Could you please give some suggestions? Thanks in advance!

Best Regards,

**Comment by akaptano** [comment]
Are you using PySINDy code at all? If you are using Rudy's STRidge you should be able to reproduce his results when you sample the same places, which would be a good check you are on the right track. And getting different PDEs is entirely possible. You need to scan the optimizer hyper parameters such as how much regularization you are using. Also, you will be much better off using the ensemble and/or weak formulations of SINDy for this task. See the Example 1 Jupyter notebook for some basic examples (and the later example notebooks for more advanced examples).
