### ISSUE TITLE
Can I add common env folders to .gitignore?

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [dynamicslab/pysindy#175]
## Is your feature request related to a problem? Please describe.
:wave:  Looking to potentially start working on this package w/my PhD, and would like to be able to ignore my virtual envirnoment files.

## Describe the solution you'd like

The standard environments from the [GitHub recommended .gitignore](https://github.com/github/gitignore/blob/main/Python.gitignore).  FWIW I just use `env/`, so also happy with that choice.
```
# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/
```

## Describe alternatives you've considered
I mean `conda`, `pipenv`, and `pyenv` are all alternatives to `venv`, but some of them create their own files and none of them are on the current `requirements-dev.txt`.  If the choice is between adding a dependency or adding lines to the .gitignore, seems better to do the latter.

## Additional context
I have this in my fork and can PR it, just wanted to ask beforehand.

**Comment by briandesilva** [comment]
Sure, this is a good idea. Feel free to create a PR. Or, if you'd like, Alan or I could make the changes directly to master since this shouldn't affect the rest of the package.
