### ISSUE TITLE
does SINDy handle distributed parameters?

### ISSUE THREAD

**Issue by dialuser** [dynamicslab/pysindy#178]
Hi,
Is it possible to use SINDy to identify PDEs having distributed coeff/parameters, e.g.,
in the following equation, K(x,y) is a distributed parameter

dU/dt = K(x,y) [ Uxx + Uyy]

thanks,

Alex

**Comment by akaptano** [comment]
Hi Alex,

Quick answer is yes -- but you have to add them to your library. This is one use case for the "GeneralizedLibrary" class. Take a look at the Example 1 notebook and the Example 15 notebook for the usage, and close this issue unless you experience any issues. 

Best,
Alan

**Comment by dialuser** [comment]
Thanks.
