### ISSUE TITLE
Weak SINDy on non-rectangular domain

### ISSUE THREAD

**Issue by florianradack** [dynamicslab/pysindy#181]
From my understanding, the current implementation of WeakPDELibrary class requires the spatial grid to be rectangular, so that rectangular subdomains of lengths H_xt/2 can be sampled to evaluate the weak-form integrals. 

How would one deal with non-rectangular domains, such as in the flow past a cylinder, where the cylinder leaves a circular hole in the domain? Any advice will be appreciated.

**Comment by znicolaou** [comment]
Hi there! The current restriction on the weak form is that the spatiotemporal grid be a tensor product grid, which has some rectilinearity to it, but it doesn't need to be strictly a rectangular. The library also currently supports either periodic or non-periodic spatial bounaries, so torus domains are possible (and it wouldn't be hard to make only certain axes periodic either). For the flow past a cylinder problem, the tricky part will be coming up with a global coordinate system. Any manifold can be locally represented with rectilinear coordinates, but pysindy is not yet built to stitch together local coordinate patches to make a global coordinate description.

**Comment by znicolaou** [comment]
To expound a little, you can a grid of polar coordinate values on an annulus would still be a tensor product grid that would work fine with the library

**Comment by florianradack** [comment]
Thanks for the detailed reply!
