### ISSUE TITLE
Include known latent variables in the (weak)PDELibrary

### ISSUE THREAD

**Issue by florianradack** [dynamicslab/pysindy#183]
Hey there,
using the weak formulation, I am attempting to identify a PDE in a variable **u**(**x**,t) which I know also depends on a second, _latent_ variable p(**x**,t). I have snapshots of the spatiotemporal data and all derivatives and would like to include the latent variable and its derivatives in the weakPDELibrary. At the same time, I am not interested in discovering an evolution equation for the latent variable and would therefore not like to include it as one of the input variables. 

Specifically, I would like to construct the matrix **Theta**= [**u**, **u^2**, **u**_1,  ..., p, p_1, **u**p, ...] (or its weak/integral representation).
At the moment, I only see two options with pySINDy to achieve the above library matrix:

1. Manually perform numerical quadratures of the same test function with the latent variable and include the resulting terms q as: `library_functions = [lambda x: q, lambda x: q*q, ...]`, 
though here I would have to take great care to compute the integrals over the same subdomain samples as the `weakPDELibrary` does.
3. Include the latent variable as one of the input variables and discover a system of equations, where the evolution equation of the latent variable will be discarded.
`input[:, :, :, :, 0] = u`
`input[:, :, :, :, 1] = p`
`model.fit(x=input, t=dt)`

I feel like I must be missing some obvious way of doing this more effectively, so any advice would be greatly appreciated.

**Comment by znicolaou** [comment]
Hi @florianradack. For including a known latent variable, you can use the control input feature of pysindy, which is given by the optional keyword argument u=, like model.fit(u, u=p, t=dt). This constucts x_dot from the first input u, but constructs the Theta matrix by applying the library transformation to the appended (u,p). I think this should work without any complication in your case, but let us know if you have issues--we haven't tested all the edge cases in the weak form library super thoroughly.
