### ISSUE TITLE
Add Pytest config?

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [dynamicslab/pysindy#186]
## Is your feature request related to a problem? Please describe.
In #185 I've passed tests, but running into errors in the notebooks.  I don't want to manually open all notebooks to run them & I want to use the debugger, so I added a test to run all the notebooks automatically.  But we shouldn't run this test regularly, therefore we would need to add config to `pytest` in order to [register a custom mark and skip it by default](https://docs.pytest.org/en/7.1.x/how-to/mark.html#registering-marks)

## Describe the solution you'd like
`tool.pytest.ini_options` in a pyproject.toml
## Describe alternatives you've considered
- Keeping a local version of test_notebooks.py

## Additional context
What are people's feelings vis-a-vis adding a run-all notebooks test?

Happy to add this,can PR pretty quickly, but not my priority RN.  Adding it to remember for later.

**Comment by akaptano** [comment]
Looks like a good idea -- reopening all the notebooks is always annoying (same with opening the binder links, I wonder if we could do something similar there). Open a PR and I will rapidly approve.
