### ISSUE TITLE
Multiple Trajectories for Weak form

### ISSUE THREAD

**Issue by rahulrobotics** [dynamicslab/pysindy#187]
Hello!,

I am trying to use the weak form of sindy to learn a system of first order ODEs from noisy data. Is it possible to use the weak form of sindy when multiple trajectories are specified with different time vectors of various lengths for each trajectory?

for example,
```
ode_lib = ps.WeakPDELibrary(
    library_functions=library_functions,
    spatiotemporal_grid = t_grid,
    is_uniform=True,
    include_bias=True,
    K=100
)
model = ps.SINDy(feature_library=ode_lib, optimizer=opt)
model.fit(x=[x1 x2], t = [t1 t2], u=[u1 u2], multiple_trajectories = True)
```
In the example, x1, t1, and u1 are arrays of equal shape, and x2, t2, and u2 are arrays of equal shape. In this case I am not sure the proper way to specify the spatiotemporal_grid parameter. Any help would be appreciated.

Thanks!

**Comment by akaptano** [comment]
Sorry for the slowness on our end. I think it is currently unsupported to use trajectories with different time spans, although I will take a look at fixing this today. 

There is another way around though -- at the end of the day all PySINDy does is concatenate all the trajectories together and do on big regression. So you simply take your trajectories, concatenate them together (and concatenate the time bases) and pass it as one trajectories without the multiple_trajectories flag on.
