### ISSUE TITLE
Combine test_pysindy.py and test_sindyc.py

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [dynamicslab/pysindy#189]
The two modules have nearly identical tests but with different data. The can probably combined via `pytest.parametrize()`.

All the non-control fixtures need to be modified to unpack in the same way as the control fixtures.

I'm happy to do it, I'm just busy with my other PR right now and wanted to record this as a todo: after I finish that.

**Comment by akaptano** [comment]
Sounds good, closing this issue but I await your PR request!
