### ISSUE TITLE
Change bagging method for WeakPDE Library?

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [dynamicslab/pysindy#194]
@znicolaou this one's for you

## Is your feature request related to a problem? Please describe.
I had assumed bagging (`WeakPDELibrary(ensemble=True)`) worked by dropping domains randomly, but it actually drops the measurement points and recalculates new domains to span the full spatiotemporal grid (reduced by a bit since dropping measurement points at the end can shrink the st grid).

## Describe the solution you'd like
If there's no particular preference with how to do bagging, I'm in favor of dropping from the already-calculated domains.  Pros:
- Only calls to `convert_u_dot_integral()` and `_set_up_weights()` once, rather than `n_subset` times.
- Simplifies `drop_random_rows()` dramatically & removes most conditionals (in conjunction with reshaping edits I'm making, it drops the function SLOC by 85%, without offloading any work to helper functions).
- I'm not sure, but it looks like there's the possibility of an [infinite loop where domain centers are randomly chosen](https://github.com/dynamicslab/pysindy/blob/04a8374b8a579f98e26f639444316f77bdc78bed/pysindy/feature_library/weak_pde_library.py#L305).  That possibility would go up a lot when `n_subset` & `H_xt` are small, but I'm not sure that I'm reading this right.
- It should be possible to get a similar effect to the current WeakPDE bagging method by dropping domains but having the domains larger to begin with.

## Describe alternatives you've considered
Is the bagging method is a significant point of any paper under consideration?

## Additional context
Obviously would only make the change if it shows similar results in the notebooks.

**Comment by Jacob-Stevens-Haas** [comment]
I think the issue is that "ensemble" means something different for Weak and nonweak libraries, and that means the same code object really doesn't work for both.  If we do regular SINDy with a spectral derivative & bagging, we currently do not recalculate spectral derivative after bagging x.  If someone wanted to do so, they would have to wrap around the outside of `SINDy().fit()`.

I also think that part of the reason for the unique WeakPDE ensemble is that bagging happens before features are calculated.  While in most cases, applying a library doesn't change the length of the time/sample axis, it does with WeakPDELibrary.

I'd also like to propose creating `EnsemblingOptimizer(opt, n_subset, n_models, library_ensemble=False)` to handle ensemble/library ensemble.  It would do the bagging/library ensembling and then dispatch to another Optimizer (`opt`) to handle the actual model fitting, looping to create the final model coefficients.
Pros:
- Passing `x` in its natural shape to the libraries becomes easier (before its flattened), and those libraries can calculate spatial derivatives which out the convoluted un-reshaping and then re-reshaping
- `SINDy.fit()` doesn't have to set library attributes to enable correct logic of later functions (spooky action at a distance!) or know anything about how the optimizers fit and libraries work.  Neither does `drop_random_rows`.
- Reshaping into `n_samples, n_features` could be a step in the `Pipeline` between `self.feature_library` and `self.optimizer`.  It also makes the order of reshaping and concatenating (`vstack`ing, really) unimportant.  Currently, the data is passed in shape `(ax_spatial, ax_time, ax_coordinate)`, reshaped, and then multiple trajectories are concatenated along the zeroth axis.  Because of row-major ordering, that logic means recreating the spatial grid for a single trajecotry & single moment in time is not simply `x[::m*p,:]` for some n, but rather `x[`spatial_grid.size*m::p,:]`.  From a coding perspective, that requires that refactoring keep reshaping before concatenating.  And if I want to pass `x` to `feature_library.transform()` in its natural shape, I need to keep it in a list of multiple trajectories.  This makes `drop_random_rows` tricky.

**Comment by znicolaou** [comment]
It also struck me that the bagging was a little odd in the weak case. I'm not totally sure what the most natural way to do it is. 

On first look, I also think randomly subsampling among the K random domain cells/weak features seems best. That way, its the rows (or columns for the library ensembling) of the lib.transform matrix that are randomly dropped in all cases. But I think you're right that this doesn't work too well with the scikitlearn pipeline, since the ensembling is done before the pipeline is fit. 

It's possible to work around that if we add an attribute weak_ensemble_indices to the weak case to enable subsampling. For example, the weak transform function could return something like xp[self.weak_ensemble_indices,:]. For the library ensembling, this approach is already used in the BaseFeatureLibrary._ensemble function. I think it might be best to just expand BaseFeatureLibrary._ensemble to cover both ensembling and library ensembling.

Feel free to take a shot at implementing this. I can also work on it, but it may take some time before I can.

**Comment by akaptano** [comment]
I like both the ideas here for simplifying the ensembling. Happy to review the PR once I get through dealing with the other open issues.

**Comment by akaptano** [comment]
Sounds like this is addressed in #185, so closing this issue (please reopen if I'm wrong).
