### ISSUE TITLE
custormizing the polynomial feature library  

### ISSUE THREAD

**Issue by buathukorala** [dynamicslab/pysindy#198]
Hello,

I am working with a high-dimensional data set with 360 variables and would like to construct a system of ODEs using the polynomial library with order 2.
However, the catch is to construct the ODEs with the following specific form:
the left-hand side of the differential equation $\dot{x}_i$ should have only the terms/combinations with the variable $x_i$ only.

Initially, I was planning to construct a constraint matrix with the pattern that I wanted and then use the ConstrainedSR3 algorithm.
Unfortunately, the constraint matrix is a very large one and unable to store (python says the matrix takes the capacity in the order of Pebibits).

Suggestions are greatly appreciated!

Thank you,
Bhagya

**Comment by znicolaou** [comment]
There are a few ways to do this, I think. Try looking into the generalized library, with the inputs_per_library option. You can have a separate polynomial library for each of the 360 equations, and specify the inputs for each of them.

**Comment by buathukorala** [comment]
Thank you very much for the suggestion @znicolaou . 
I will check this too.

Bhagya

**Comment by akaptano** [comment]
There is an even easier solution if I am understanding you correctly. Each dx_i /dt equation is fit separately by SINDy anyways. So why not just fit each x_i with its own SINDy model one by one? Then the library you are using will only depend on the x_i -- it is the only variable.

**Comment by akaptano** [comment]
By the way, you will need to use constraints to guarantee the stability of your resulting equations. See Issue #157 for an extended discussion about why quadratic equations are not generically stable. For your case, you have:
dx_i /dt = a_i x_i + b_i x_i^2 
Energy = 0.5 * sum_i (x_i * dx_i /dt) ~ 0.5 * sum_i (b_i * x_i^3)  (to leading order)

and for generic x_i (i.e. assuming all the x_i can be positive or negative), this energy will blow up if you start with an initial condition outside a region centered at the origin.

**Comment by buathukorala** [comment]
Hi @akaptano,

Thank you very much for your comments and suggestions. 
Sorry for the confusion Alan - the right-hand side of the differential equation: $\dot{x}_i$ can contain terms: $x_ix_j ( j \in {1, \dots, 360 })$ as well ( for polynomial library with order 2). 

As an example, $\dot{x}_1 = f(1,x_1, x_1^2, x_1 x_2, x_1x_3, x_1x_4, \dots ,x_1 x_n )$.

Thank you very much for pointing me to Issue $157 - the discussion is very useful and interesting.

Bhagya
