### ISSUE TITLE
SINDy and differential equations with rational nonlinearities 

### ISSUE THREAD

**Issue by KIM-cpu05** [dynamicslab/pysindy#201]
Hi, I am new to GitHub.

Why is it hard for SINDy to detect the correct terms of implicit form of  differential equations with rational nonlinearities?

**Comment by Jacob-Stevens-Haas** [comment]
Can you provide an example of what you mean?  Maybe some code that generates a differential equation with rational nonlinearity that SINDy fails at?

**Comment by akaptano** [comment]
The short answer, if you are using SINDy-PI, is probably because the feature library is ill-conditioned.

**Comment by KIM-cpu05** [comment]
> Can you provide an example of what you mean? Maybe some code that generates a differential equation with rational nonlinearity that SINDy fails at?



> Can you provide an example of what you mean? Maybe some code that generates a differential equation with rational nonlinearity that SINDy fails at?

Hello. Thank you for the reply.

I am referring to the example in https://pysindy.readthedocs.io/en/latest/examples/9_sindypi_with_sympy.html where the 2D case is not correctly detected.

**Comment by KIM-cpu05** [comment]
> The short answer, if you are using SINDy-PI, is probably because the feature library is ill-conditioned.

Hello. 

I am referring to the 2D example in https://pysindy.readthedocs.io/en/latest/examples/9_sindypi_with_sympy.html. Unless there is an update where SINDy correctly detects the underlying equations...
