### ISSUE TITLE
[BUG] in STLSQ class with function _preprocess_data that is undefine

### ISSUE THREAD

**Issue by claraleduff** [dynamicslab/pysindy#204]
Hi everyone,
I'am trying to execute the first code in the doc at this page : https://pysindy.readthedocs.io/en/latest/examples/2_introduction_to_sindy.html

And I have the following error : AttributeError: 'STLSQ' object has no attribute '_preprocess_data'

And in the definition of STLSQ in the base.py file, I don't see any definition of the function _preprocess_data

Is it normal ?

Thanks a lot for your help

**Comment by akaptano** [comment]
Thanks for trying out the code! See Issue #179 or download the most recent version of the main branch. Basically it is a sklearn 1.1 issue and we have fixed it. 

Best,
Alan

**Comment by claraleduff** [comment]
What is the tag of the branch, you are talking ? there is 3 active one?

Thank a lot for your answer. 
Clara
