### ISSUE TITLE
AttributeError: 'STLSQ' object has no attribute '_preprocess_data'

### ISSUE THREAD

**Issue by stephanernx** [dynamicslab/pysindy#210]
after installing pysindy using the pip command I get the following error 

### Reproducing code example:

import numpy as np
import pysindy as ps

import sys, pysindy; print(pysindy.__version__, sys.version)

t = np.linspace(0, 1, 100)
x = 3 * np.exp(-2 * t)
y = 0.5 * np.exp(t)
X = np.stack((x, y), axis=-1)

differentiation_method = ps.FiniteDifference(order=2)
feature_library = ps.PolynomialLibrary(degree=3)
optimizer = ps.STLSQ(threshold=0.2)

model = ps.SINDy(differentiation_method=differentiation_method,
                 feature_library=feature_library,
                 optimizer=optimizer,
                 feature_names=["x", "y"])
model.fit(X, t=t)

### Error message:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/media/rdx/endumion_files/simul_rn/Sindy/essai_10.py in <module>
     17                  optimizer=optimizer,
     18                  feature_names=["x", "y"])
---> 19 model.fit(X, t=t)

~/.local/lib/python3.8/site-packages/pysindy/pysindy.py in fit(self, x, t, x_dot, u, multiple_trajectories, unbias, quiet, ensemble, library_ensemble, replace, n_candidates_to_drop, n_subset, n_models, ensemble_aggregator)
    561                         self.coef_list.append(coef_partial)
    562             else:
--> 563                 self.model.fit(x, x_dot)
    564 
    565         # Get average coefficients if ensembling was used

~/.local/lib/python3.8/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    380             if self._final_estimator != "passthrough":
    381                 fit_params_last_step = fit_params_steps[self.steps[-1][0]]
--> 382                 self._final_estimator.fit(Xt, y, **fit_params_last_step)
    383 
    384         return self

~/.local/lib/python3.8/site-packages/pysindy/optimizers/sindy_optimizer.py in fit(self, x, y)
     56                 self.optimizer = _MultiTargetLinearRegressor(self.optimizer)
     57 
---> 58         self.optimizer.fit(x, y)
     59         if not hasattr(self.optimizer, "coef_"):
     60             raise AttributeError("optimizer has no attribute coef_")

~/.local/lib/python3.8/site-packages/pysindy/optimizers/base.py in fit(self, x_, y, sample_weight, **reduce_kws)
    132         x_, y = check_X_y(x_, y, accept_sparse=[], y_numeric=True, multi_output=True)
    133 
--> 134         x, y, X_offset, y_offset, X_scale = self._preprocess_data(
    135             x_,
    136             y,

AttributeError: 'STLSQ' object has no attribute '_preprocess_data'

### PySINDy/Python version information:
1.7 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]

**Comment by akaptano** [comment]
See Issue #179
