### ISSUE TITLE
Setting Custom Equations for Each Variable

### ISSUE THREAD

**Issue by teddywillb** [dynamicslab/pysindy#213]
I am attempting to learn the dynamics of a system with multiple variables where we expect each variable's evolution equation to have a distinct functional form. To illustrate this I have come up with the following example system, where we wish to learn the coefficients in front of the terms having the form:
x' = x + x(y^2)
y' = y + (x^2)y + y^3
It appears that I should use a generalized library with the inputs_per_library and tensor_array functionality. However, I am having some difficulty understanding exactly what these arrays do and how I can use them to accomplish my task.

I have started by defining simple polynomial terms that I can combine by 'tensoring' them together using my tensor_array to complete my library. Where I am confused is the application of the inputs_per_library array. From its description [here](https://pysindy.readthedocs.io/en/latest/api/pysindy.feature_library.html#pysindy.feature_library.generalized_library.GeneralizedLibrary) its seems to have the functionality to inputs specific features into the desired libraries. In practice I am having a hard time understanding how each entry in the array changes which features go into which libraries. No matter what I choose for the inputs_per_library array, I get the same functional form for x' and y'. Also, my inputs_per_library1 and inputs_per_library2 give identical results. Why should this be?

To specify different functional forms for each variable (x' and y'), do I need to learn their evolution equations independently? And if so, how do I accomplish this?

### Reproducing code example:

import numpy as np
import pysindy as ps

x_train = np.array([[0.5,  1],  [3,    2],  [2,   -1],  [-2,   1]])

f1 = [lambda x: x]
f1_names = [lambda x: x]

f2 = [lambda x: x**2]
f2_names = [lambda x: x+'^2']

f3 = [lambda x: x**3]
f3_names = [lambda x: x+'^3']

lib1 = ps.feature_library.CustomLibrary(library_functions=f1, function_names=f1_names)
lib2 = ps.feature_library.CustomLibrary(library_functions=f2, function_names=f2_names)
lib3 = ps.feature_library.CustomLibrary(library_functions=f3, function_names=f3_names)

inputs_per_library1 = np.array([[1,   0],  [1,   0],   [1,   0]])   

inputs_per_library2 = np.array([[0,   1],   [0,   1],   [0,   1]])  

tensor_array = np.array([[1,   1,   0]])

lib = ps.GeneralizedLibrary( [lib1,lib2,lib3], inputs_per_library=inputs_per_library1, tensor_array=tensor_array )
lib.fit(x_train)
print(lib.transform(x_train))
print(lib.get_feature_names())

optimizer = ps.optimizers.STLSQ(threshold = 1e-3,alpha=0.1) 
model = ps.SINDy(feature_names=['x','y'], feature_library=lib, optimizer=optimizer)
model.fit(x_train, t=1)
model.print()

### PySINDy/Python version information:
1.7 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]

**Comment by teddywillb** [comment]
UPDATE: I have figured out a way to enforce separate functional forms on the evolution equations of the two different variables. I would still like some feedback as to if there is a better method so that I can scale this up for systems of more variables.

`import numpy as np
import pysindy as ps

# %% 4 example data points in time for each of the 2 variables
x_train = np.array([[0.5,  1],
                    [3,    2],
                    [2,   -1],
                    [-2,   1]])
feature_names=['x','y']

# %% define functions for function library
f1 = [lambda x: x]
f1_names = [lambda x: x]

f2 = [lambda x,y: x*y**2]
f2_names = [lambda x,y: x + y+'^2']

f3 = [lambda x: x**3]
f3_names = [lambda x: x+'^3']

f4 = [lambda x,y: x**2*y]
f4_names = [lambda x,y: x +'^2' + y]

lib1 = ps.feature_library.CustomLibrary(library_functions=f1, function_names=f1_names)
lib2 = ps.feature_library.CustomLibrary(library_functions=f2, function_names=f2_names)
lib3 = ps.feature_library.CustomLibrary(library_functions=f3, function_names=f3_names)
lib4 = ps.feature_library.CustomLibrary(library_functions=f4, function_names=f4_names)

optimizer = ps.optimizers.STLSQ(threshold = 1e-3,alpha=0.1) 
# %% create x library and transform example data
#                                x    y
inputs_per_library_x = np.array([[0,   0],    # lib1
                                 [0,   1]])   # lib2

lib_x = ps.GeneralizedLibrary( [lib1,lib2], inputs_per_library=inputs_per_library_x )
lib_x.fit(x_train)
print('______________________\nX Library: ',lib_x.get_feature_names())

# find the optimal coefficients
modelx = ps.SINDy(feature_names=['x','y'], feature_library=lib_x, optimizer=optimizer)
modelx.fit(x_train, t=1)

x_string = '(x)\' ='
decimals = 3
for i in range(np.size(lib_x.get_feature_names())):
    x_string += ' ' + str(np.round(modelx.coefficients()[0,i],decimals)) + ' ' + str(lib_x.get_feature_names()[i]) + ' +'
x_string = x_string[:-1]
print(x_string)

# %% create y library and transform example data
inputs_per_library_y = np.array([[1,   1],    # lib1
                                 [0,   1],    # lib2
                                 [1,   1]])   # lib3

lib_y = ps.GeneralizedLibrary( [lib1,lib4,lib3], inputs_per_library=inputs_per_library_y )
lib_y.fit(x_train)
print('______________________\nY Library: ',lib_y.get_feature_names())

# find the optimal coefficients
modely = ps.SINDy(feature_names=['x','y'], feature_library=lib_y, optimizer=optimizer)
modely.fit(x_train, t=1)

y_string = '(y)\' ='
decimals = 3
for i in range(np.size(lib_y.get_feature_names())):
    y_string += ' ' + str(np.round(modely.coefficients()[1,i],decimals)) + ' ' + str(lib_y.get_feature_names()[i]) + ' +'
y_string = y_string[:-1]
print(y_string)`

**Comment by Jacob-Stevens-Haas** [comment]
Hey @teddywillb, a few things that would help: make the example more minimal (you don't need to use an `Optimizer` and `SINDy.fit()` to demonstrate the library issue) and enclose your code blocks like:
\`\`\`python
x = "stuff"
\`\`\`
 so they appear like this:
```python
x = "stuff"
```
It also helps to print the result of your code and what you expected to appear instead (you would notice that the line `x_string = '(x)' ='` raises an error).

In the first case, it seems that your `tensor_array` parameter was giving you terms like `x0 x0^2'` (i.e. $ x^3 $).  Since you want to fit a different library for  $x $ and  $y $ however, I don't see a way around fitting two separate models.  You could cut down on fitting the unnecessary  $\dot y = x + x y ^2 $ and  $\dot x = y + x^2 y + y^3 $ by passing the variable for which you don't want to fit an equation as a control input.  For the ($\dot x = x + x y^2)$ equation, this is:
```python
import numpy as np
import pysindy as ps

x_train = np.array([[0.5, 1], [3, 2], [2, -1], [-2, 1]])
f1 = lambda x, y: x
f1_names = lambda x, y: x

f2 = lambda x, y: x * y**2
f2_names = lambda x, y: x+y+'^2'
lib1 = ps.feature_library.CustomLibrary(library_functions=(f1, f2), function_names=(f1_names, f2_names))

lib1.fit(x_train)
print(lib1.transform(x_train))
print(lib1.get_feature_names())
optimizer = ps.optimizers.STLSQ(threshold = 1e-3,alpha=0.1)

model = ps.SINDy(feature_names=['x','y'], feature_library=lib1, optimizer=optimizer)
model.fit(x_train[:,0], t=1, u=x_train[:,1])
model.print()
```
Gives:
```
[[ 0.5  0.5]
 [ 3.  12. ]
 [ 2.   2. ]
 [-2.  -2. ]]
['x0', 'x0x1^2']
(x)' = 1.230 x + -0.245 xy^2
```
