### ISSUE TITLE
PySINDy metamodels

### ISSUE THREAD

**Issue by Jungwoo95** [dynamicslab/pysindy#214]
Dear developer. I'm a master's student majoring in mechanical engineering.

I want to make a metamodel that can predict dynamic model's displacement.
Metamodel's input is spline data(time series - angle displacement) and output is same(time series - body's displacement)
As you know, metamodel's purpose is perdiction about body's displacement for given angle displacement.
I have about 5000 datum.(input and output.)(I can make more datum.)
In this, can I make a metamodel using pysindy??
Please give me a advise. 

Thank you.
Best regards,
Jungwoo.

**Comment by akaptano** [comment]
PySINDy input is time series data but its output is a set of equations describing the evolution. What you can do is concatenate your two time series together and try to discover a set of equations for the evolution of your body displacement variable.

**Comment by Jungwoo95** [comment]
Thank you for your answer.
So I can learn two data and get an equation to predict the displacement?
