### ISSUE TITLE
How to reproduce the dataset about POD in pysindy/examples/data/?

### ISSUE THREAD

**Issue by xgxg1314** [dynamicslab/pysindy#216]
Hi,  thank you so much for your nice repository!
I want to get the POD dataset for my own problem, but I have no idea how to implement it. Could you please share the code reproducing the POD dataset or give some advice about it? Thank you in advance!

**Comment by akaptano** [comment]
Which dataset are you referring to? The magnetohydrodynamic one? In this case, are you hoping to generate your own set of POD modes from a magnetohydrodynamic simulation?
