### ISSUE TITLE
CI include documentation build step

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [dynamicslab/pysindy#218]
## Is your feature request related to a problem? Please describe.
When I'm making PRs for docstring edits, I don't know if the RST markup inside the docstring is legal.
- I would normally try to build the docs locally.  With sphinx, that usually means `cd docs` `make html`, but I don't see a Makefile in docs, so I checked the CI yaml.
- CI doesn't build the docs.

## Describe the solution you'd like
How do I build docs locally?  Happy to implement CI doc build if I know how to do it locally.

**Comment by Ohjeah** [comment]
@Jacob-Stevens-Haas You can find the build log of readthedocs here https://readthedocs.org/projects/pysindy/builds/17412700/

I think it‘s easy to reproduce the build but checking for correct rst maybe tricky

**Comment by Jacob-Stevens-Haas** [comment]
Ahhhh, thanks that makes sense
```
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
```
was the line I was looking for.

Actually, I remember pandas uses some pre-commit hooks that check rst in python docstrings.  That might be a good first step.

Also, reading that build looks like my refactoring broke the [links](https://pysindy.readthedocs.io/en/latest/examples/5_differentation.html) to the notebooks.  @akaptano is that what you meant by the binder links?  This may be a good reason to include doc build in CI.
