### ISSUE TITLE
Simple poisson equation not giving sensible results

### ISSUE THREAD

**Issue by isshiki416** [dynamicslab/pysindy#232]
I have been trying to use the package to recover the Poisson Equations, but I get very poor results with the default parameters of SINDy and I was wondering what kind of things I should change.
The original equation is:

(t)' = 4.1e-5 (t_11+t_22)

The training data came from the MATLAB code on solid heat transfer written by myself.
Data file is here:
[t.xlsx](https://github.com/dynamicslab/pysindy/files/9177840/t.xlsx)

The pysindy code is:

```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
from sklearn.linear_model import Lasso
from scipy.io import loadmat
from sklearn.metrics import mean_squared_error
from scipy.integrate import solve_ivp

import warnings
warnings.filterwarnings("ignore", category=UserWarning)

import pandas as pd
import pysindy as ps

data_t = pd.read_excel('t.xlsx', header=0)
t_r = data_t.values
t = np.zeros((21,21,180))
for it in np.linspace(0,179,180):
  for iy in np.linspace(0,20,21):
    t[:,int(iy),int(it)] = t_r[(21*int(iy)):(21*(int(iy)+1)),int(it)]

temp = np.transpose(t, axes=[1, 0, 2])
t = np.zeros((21, 21, 180, 1))
t[:,:,:,0] = temp
t_dot = ps.SmoothedFiniteDifference(axis=2)._differentiate(t,10)
# t_dot = t_dot*1e5

print(t[:,:,0,0])
x = np.linspace(0,1,21)
y = x
X, Y = np.meshgrid(x, y)
# X = X.T
# Y = Y.T
space_grid = np.asarray([X, Y]).T
print(X)

library_functions = [lambda x: x]
library_function_names = [lambda x: x]
pde_lib = ps.PDELibrary(
    library_functions=library_functions,
    function_names=library_function_names,
    derivative_order=2,
    spatial_grid=space_grid,
    interaction_only=True,
    is_uniform=True,
    include_interaction=False,
    include_bias=False
)

'''
n_features = 6
n_tagets = 1
constraint_rhs = np.zeros(1)
constraint_lhs = np.zeros((1,n_features * n_tagets))
constraint_lhs[0, 2] = 1
constraint_lhs[0, 5] = -1

optimizer = ps.ConstrainedSR3(
    threshold=1e-5,
    max_iter=1000,
    tol=1e-10,
    nu=1,
    thresholder="l0",
    constraint_rhs=constraint_rhs,
    constraint_lhs=constraint_lhs,
)
'''

optimizer = ps.SR3(
    threshold=0.1,
    max_iter=1000,
    tol=1e-10,
    nu=1,
    thresholder="l0",
    normalize_columns=True,
)

model = ps.SINDy(feature_library=pde_lib, optimizer=optimizer, feature_names='t')
model.fit(t[:,:,:,:], x_dot=t_dot[:,:,:,:], ensemble=True)
model.print()
print(model.coefficients())
model.get_feature_names()
```

the result is:

(t)' = 0.000
[[-1.48042909e-04  3.71342336e-06  1.37479537e-05 -1.36383762e-05
   6.52022205e-07  4.51077557e-05]]
['t', 't_2', 't_22', 't_1', 't_12', 't_11']

It's far away from my target. Could you please tell me how I can optimize my model?

**Comment by kyrxanthos** [comment]
Is there a particular reason you are just using the `[lambda x: x]` as your only library function?

**Comment by isshiki416** [comment]
> Is there a particular reason you are just using the `[lambda x: x]` as your only library function?

No, but I think the target equation has only the second derivative of t on the right-hand side so just using the '[lambda x:x]' is enough.

**Comment by akaptano** [comment]
This will be a challenging PDE to identify because you have O(1) factor on the t' side and O(1e-5) factor on the other side. You might reconsider rescaling your equations or dimensionalizing them and trying again. A simple transformation will balance the numerical scales here.

**Comment by akaptano** [comment]
Your identified ODE is also not sparse. You could try increasing the sparsity threshold. But again, this will work better if your equation looks like t' = t_11 + t_22. And actually, t' = t_11 + t_22 is not the Poisson equation (it is time dependent here!) so I am not sure exactly what you are attempting.

**Comment by isshiki416** [comment]
> This will be a challenging PDE to identify because you have O(1) factor on the t' side and O(1e-5) factor on the other side. You might reconsider rescaling your equations or dimensionalizing them and trying again. A simple transformation will balance the numerical scales here.

I tried to artificially magnify the 't_dot' of the training data by a factor of 1e5, but the results show no obvious difference other than the order of magnitude. I expect at least the coefficients of t_11 and t_22 to be close.

**Comment by akaptano** [comment]
Could you make plots of t, t_dot, t_11, and t_22? The code should work so I think there is probably just a scaling missing here.
