### ISSUE TITLE
ps.AxesArray - no such attribute found?

### ISSUE THREAD

**Issue by williamsj0165** [dynamicslab/pysindy#235]
In the PDE-FIND example, block 3 line 4, the code:
`u = ps.AxesArray(np.ones((len(x) * len(t), 2)),{"ax_coord":1})
`
returned the error
`module 'pysindy' has no attribute 'AxesArray'`

I've updated PySINDy to 1.7.1 and uninstalled/reinstalled for good measure, but still face this error.

`dir(ps)` doesn't show the attribute AxesArray, either.

**Comment by williamsj0165** [comment]
I'm looking through the Commit history... it seems it's just been moved somewhere else. Finding out where.

**Comment by Jacob-Stevens-Haas** [comment]
`AxesArray` is in the 2.0.0-rc1 release, which is marked as pre-release.  There are a few things I want to sort out to make it stable (see the [release notes](https://github.com/dynamicslab/pysindy/releases/tag/v2.0.0-rc1))

Which is the PDE-FIND example?  on the 1.x branch, it shouldn't have any mention of AxesArray.

**Comment by williamsj0165** [comment]
This is the PDE-FIND example:
https://github.com/dynamicslab/pysindy/blob/master/examples/10_PDEFIND_examples.ipynb
Block 3, line 4

**Comment by Jacob-Stevens-Haas** [comment]
And that's because the 2.0.0-rc1 release is from the master branch, but 1.7.1 is from the 1.x branch.
