### ISSUE TITLE
custom PDE library

### ISSUE THREAD

**Issue by 27septembre** [dynamicslab/pysindy#241]
Hello, 
I want to build a custom PDE library, feature_names = ['a','b'], 
then  model.get_feature_names() 
['a', 'b', 'aa', 'bb', 'ab', 'a_2', 'b_2', 'a_1', 'b_1', '(ab)_2', '(aa)_2', '(bb)_2', '(ab)_1', '(aa)_1,'(bb)_1)]

I can get it by using feature_names = ['a','b','aa','bb','ab'] instead, but I wonder if there is a more general way. So far I only have
```
feature_names = ['a','b']

library_functions = [
    lambda x: x,
    lambda x: x*x,
    lambda x,y: x*y,
]
library_function_names = [
    lambda x: x,
    lambda x: x+x,
    lambda x,y: x+y,
]
pde_lib = ps.PDELibrary(
    library_functions=library_functions,
    function_names=library_function_names,
    derivative_order=1,
    spatial_grid=spatial_grid,
    include_bias=False,
    include_interaction=False,
    is_uniform=True,
)
```
model.get_feature_names()
['a', 'b', 'aa', 'bb', 'ab', 'a_2', 'b_2', 'a_1', 'b_1']

or 
```
library_functions = [
    lambda x: x,
]
library_function_names = [
    lambda x: x,
]
pde_lib = ps.PDELibrary(
    library_functions=library_functions,
    function_names=library_function_names,
    derivative_order=1,
    spatial_grid=spatial_grid,
    include_bias=False,
    include_interaction=True,
    is_uniform=True,
)
```
model.get_feature_names()
['a','b','a_2','b_2','a_1','b_1','aa_2', 'ab_2', 'ba_2','bb_2','aa_1','ab_1','ba_1', 'bb_1']
here 'ab_1' is 'a X b_1' not (ab)_1 I want

**Comment by Jacob-Stevens-Haas** [comment]
I'm a bit confused.  What do you want 
```
 ['a', 'b', 'aa', 'bb', 'ab', 'a_2', 'b_2', 'a_1', 'b_1', '(ab)_2', '(aa)_2', '(bb)_2', '(ab)_1', '(aa)_1,'(bb)_1)]
```
to mean?

**Comment by znicolaou** [comment]
Is it correct to say that you want to enforce a constraint that the coefficients of, say, `ab_1` and `ba_1` are identical, so they can be combined into `(ab)_1=ab_1+ba_1`? If so, you can probably use the `ConstrainedSR3` optimizer -- see the examples in the example notebook 1.

**Comment by 27septembre** [comment]
@znicolaou @Jacob-Stevens-Haas 
Thank you for the reply. I realized my mistake,  I will check the ConstrainedSR3 optimizer.
