### ISSUE TITLE
Simulation forward in time of PDE model

### ISSUE THREAD

**Issue by isshiki416** [dynamicslab/pysindy#246]
I've got a trained PDE model, and I want to see how it evolves in time. I used the simulate() method but got an error. 
It can only solve ODE, right? Could you please tell me how I can get the result of the time evolution of this model? Thanks!

**Comment by akaptano** [comment]
Yes, simulate only works for ODEs. PDEs require specialized solvers. Depends on what your PDE looks like!

**Comment by isshiki416** [comment]
OK. Thanks!

**Comment by isshiki416** [comment]
By the way, does predict() work for PDEs?

**Comment by akaptano** [comment]
Yes, check out https://github.com/dynamicslab/pysindy/blob/master/examples/10_PDEFIND_examples.ipynb
