### ISSUE TITLE
Can GPU speed up model training？

### ISSUE THREAD

**Issue by isshiki416** [dynamicslab/pysindy#247]
I'm training a PDE model. Can GPU accelerate this process?

**Comment by akaptano** [comment]
We do not have GPU functionality in the code currently. However, your model should train fairly fast unless your resolution is super high. Post some more information if you would like some more feedback on this.

**Comment by Jacob-Stevens-Haas** [comment]
@isshiki416 If you have any more information or question on model training speed, we can reopen the issue, but since it's been a week, I'm closing this.
