### ISSUE TITLE
Limit the candidate function in a strictly chosen range

### ISSUE THREAD

**Issue by isshiki416** [dynamicslab/pysindy#248]
Hello!

I'm studying the case of the 2D reaction-diffusion system. [https://pysindy.readthedocs.io/en/latest/examples/10_PDEFIND_examples.html#test-pde-functionality-on-2d-reaction-diffusion-system](url)

When I get the feature names of the trained model, I find some unexpected terms like x0x1_1. etc even though the inputted function is only x, xxx, xyy and xxy.
I know the unexpected terms are generated automatically, but is it possible to just consider the strictly chosen terms while training the model? In this case those are x0_11, x0_22, x0, x0x0x0, x0x0x1, x0x1x1 and x1x1x1 for the first equation.

I want to do this because sometimes we know exactly the terms in the equation and only need to get the corresponding coefficients.
The unexpected terms may disturb the model.

Thanks!

**Comment by akaptano** [comment]
It is not entirely clear what you want from your description. Are you wanting a library that takes spatial derivatives of x0, but not of x1, and then generates all the polynomial combinations up to order 3?

There are ways to make very tailored libraries using the GeneralizedLibrary class but your best bet here is probably to use the ConstrainedSR3 optimizer (see Example 1 notebook for simple usage) and then make it off-limits to use the terms that you don't want in the library.

**Comment by isshiki416** [comment]
I got it. Thank you.

**Comment by ericwhester** [comment]
I have a similar and simpler question:

Say I have a 2D ODE, and I want the library of functions for the first equation to only consider the second variable, and the library of functions for the second equation to only consider the first variable.

That is, something like [x1, x1^2] for the first equation, and [x0, x0^2, x0^3] for the second equation, but NOT also [x0,x0^2,x0^3] for the first equation.

I understand how to generate the [x0,x0^2,x0^3] and [x1,x1^2] libraries, and I understand how to join them with GeneralLibrary, but I do not understand how to make sure the first equation only considers the first library, and the second equation only considers the second library.

There is a reference to something sounding like this on the [advice for library selection](https://pysindy.readthedocs.io/en/latest/tips.html#library-selection) (specifically the IdentityLibrary), but I wasn't able to find a clear enough example to follow.

I hope this enquiry makes sense.

**Comment by akaptano** [comment]
yes, you can do this with the "inputs_per_library" parameter used in the GeneralizedLibrary class. See the last few cells in the Example 1 Jupyter notebook. 

Best,
Alan

**Comment by akaptano** [comment]
Oh sorry, I think I misunderstood your question. The easiest way to do what you suggest is simply to fit the two equations separately. So first build a SINDy model for x0_dot with the [x0, x0^2, x0^3] library and then build a model x1_dot. In your case, the equations are totally uncoupled, although even if they are coupled, the SINDy fits for x0_dot and x1_dot are independent, so you can do this anyways.

**Comment by ericwhester** [comment]
Ah ok, but if the specific library actually had some overlap between different equations (whilst not being identical), is there a solution for that?

Thanks for the quick reply,
Eric

On 25 Jan 2023, at 5:06 am, Alan Kaptanoglu ***@***.***> wrote:

﻿

Oh sorry, I think I misunderstood your question. The easiest way to do what you suggest is simply to fit the two equations separately. So first build a SINDy model for x0_dot with the [x0, x0^2, x0^3] library and then build a model x1_dot. In your case, the equations are totally uncoupled, although even if they are coupled, the SINDy fits for x0_dot and x1_dot are independent, so you can do this anyways.

**Comment by akaptano** [comment]
What is the issue? You can also fit the terms individually with a mixed-term library, like fitting x0_dot using a library [x0, x1, x0^2, x1^2]. The SINDy fits for x0_dot and x1_dot are _always_ independent, no matter what the library is doing.

**Comment by znicolaou** [comment]
To elaborate on @akaptano's solution, you can include the library functions for x1 in the fit for x0 by using the control input, as in `model.fit(x0,u=x1)`

**Comment by ericwhester** [comment]
@akaptano: The example I meant was, what if I wanted library [x1, x0, x0^2, x0^3] for equation 1, and [x0, x1^2] for equation 2? 

@znicolaou: So if I understand what you have been saying correctly, I could do this by doing a sindy fit for each equation separately, by defining a custom library for each equation, and incorporating other variables as control variables? And that would be the simplest way of doing so?

**Comment by znicolaou** [comment]
Yes, that would be one way to accomplish your fit. You can also use library functions that explicitly refer to the other variables, like 
```
custom_library = ps.CustomLibrary(library_functions=[lambda: x1])
model=ps.SINDy(feature_library=custom_library)
model.fit(x0)
```
The simplest way of doing things is a matter of opinion...
