### ISSUE TITLE
[BUG] Dicovering equations with rational terms

### ISSUE THREAD

**Issue by GemmaMasFes6** [dynamicslab/pysindy#252]
I am trying to recover the equations of a model with rational terms, but I am not able to achieve it. 
Here is the model:

def immunity(t, x, a=0.18, k = 60, s = 1.1, e = 0.005, b = 0.013, al = 0.01, ga = 0.02, d = 0.001, de = 0.105):
    return [
        a*(1-x[0]/k) * x[0]-e * x[0] * x[1]-b * x[0] * x[1]**2/(x[1]+al * x[0]/ga),
        s+d * x[0]-de * x[1],
    ]

Also, I was running the 2D example of model with rational terms and, I read that it needs a lot of terms. Which is the minimum of time points to ensure that SINDY will discover the rational terms?

**Comment by GemmaMasFes6** [comment]
And how can I interpret the output? For example, for my model I have obtained the following output:

_1 = 0.001 x1_dot
x0 = 0.000
x1 = 0.000
x0x1 = 0.000
x0x0 = 0.000
x1x1 = 0.000
x0x1x1 = 0.000
x0x0x0 = 0.004 x0x0_dot + -0.001 x0x0x1_dot
x1x1x1 = 0.000
x0x1x1x1 = 0.000
x0x0x0x0 = 0.000
x1x1x1x1 = 0.000
x0_dot = 0.006 x0x1_dot
x1_dot = 0.000
x0x0_dot = 0.002 x0x0x1_dot
x1x0_dot = -0.001 x0x0_dot + 0.001 x0x1x1_dot
x0x1x0_dot = 0.003 x0x0_dot + -0.001 x0x1_dot
x0x0x0_dot = -0.001 x0_dot + 0.003 x0x0_dot
x1x1x0_dot = 0.001 x1x0_dot
x0x1x1x0_dot = 0.001 x0_dot + -0.001 x0x0_dot + 0.001 x0x1x0_dot
x0x0x0x0_dot = 0.001 x0_dot + -0.005 x0x0_dot + 0.003 x0x0x0_dot + 0.001 x0x0x1_dot
x1x1x1x0_dot = 0.001 x0_dot
x0x1x1x1x0_dot = -0.001 x0_dot + -0.001 x0x1x0_dot
x0x0x0x0x0_dot = 0.000
x1x1x1x1x0_dot = 0.001 x0x0_dot
x0x1_dot = 0.039 x0_dot + 0.001 x0x0_dot
x1x1_dot = 0.000
x0x1x1_dot = 0.000
x0x0x1_dot = 0.001 x0_dot + 0.016 x0x0_dot
x1x1x1_dot = 0.001 x1x1_dot
x0x1x1x1_dot = -0.001 x0_dot
x0x0x0x1_dot = 0.000
x1x1x1x1_dot = 0.000
x0x1x1x1x1_dot = -0.001 x0x0_dot + -0.001 x1x0_dot + -0.001 x1x1x0_dot
x0x0x0x0x1_dot = 0.001 x0_dot + 0.035 x0x0_dot + -0.001 x0x1x0_dot + -0.007 x0x0x1_dot + 0.001 x0x0x0x1_dot
x1x1x1x1x1_dot = -0.001 x0x0_dot + 0.001 x1x1_dot_

Do I have to combine all possible pairs and see which one corresponds to my original model?

**Comment by akaptano** [comment]
Yes, what the SINDy-PI optimizer has done is fit a best model to all the _library terms_ and it is now up to you how to choose the best model from these. You could just go through and observe all the fits, but if you know your equations like your problem above, you know for instance that you should expect a term like x0x1^2. My guess is you are sparsifying too aggressively here to get a final model that is correct.
