### ISSUE TITLE
[BUG] The example notebook cannot be run without errors: 9_sindypi_with_sympy.ipynb

### ISSUE THREAD

**Issue by naikymen** [dynamicslab/pysindy#256]
We're trying to reproduce the example code for the identification of michaelis-menten kinetics.

### Reproducing code example:

Attempt to run the example notebook at:

https://github.com/dynamicslab/pysindy/blob/08f9fe7b61189d4acc1f8b5e644edd920bd56e88/examples/9_sindypi_with_sympy.ipynb

### Error message:

The part that I'm trying to reproduce produces this error:

```
# Solve 1D Michelson-Menten enzyme model as first demonstration
>>> model.fit(x_train, t=t)
IndexError: index 4000 is out of bounds for axis 0 with size 4000
```

There is also an error in the name of the equation, it is called "Michaelis-Menten" (and not "Michelson-Menten"). I suggest correcting this as it is harder to find with the incorrect name.

There is also an issue with a previous section of the notebook which is not of interest to us, but we report anyway :)

```
>>> lib = ps.PDELibrary(
    library_functions=functions,
    function_names=function_names,
    temporal_grid=t,
    derivative_order=1,
    implicit_terms=True
)
TypeError: PDELibrary.__init__() got an unexpected keyword argument 'temporal_grid'
```

### PySINDy/Python version information:

```
>>> print(ps.__version__, sys.version)
1.7.1 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
```

**Comment by naikymen** [comment]
After running `pip install git+https://github.com/dynamicslab/pysindy.git` to install the latest library, the errors went away.

It seems that pip's version is incompatible with the notebook.

**Comment by akaptano** [comment]
New version released, let me know if this doesn't fix the problem. Closing for now but feel free to reopen this.
