### ISSUE TITLE
PySINDy tutorial 2: Choosing algorithm hyperparameters

### ISSUE THREAD

**Issue by joardima** [dynamicslab/pysindy#262]
I,m trying to go through the youtube tutorial '_PySINDy tutorial 2: Choosing algorithm hyperparameters',

After downloading the data from _'pysindy/docs/Youtube'_ and copying the following script:

import numpy as np
import pysindy as ps

### Generate dynamical system data
import numpy as np
from scipy.integrate import odeint

def f(x, t):
    return [np.sin(2 * x[1]), 1 - np.cos(x[0])]

dt = 0.01
t_train = np.arange(0, 10, dt)
x0_train = [1, 2]
x_train = odeint(f, x0_train, t_train)

with open("data.npy", "wb") as file:
    np.save(file, x_train)

feature_names = ['x', 'y', 'z']
opt = ps.STLSQ(threshold = 0) # Lambda = 0
model = ps.SINDy(feature_names = feature_names, optimizer = opt)
model.fit(x_train, t=dt)
model.print()

The following message appears: _'AttributeError: can't set attribute'_

Any suggestion or insight on how to solve it would be really helpful.

Thanks.

**Comment by akaptano** [comment]
Can you specify the python line where the error is occurring?

**Comment by joardima** [comment]
Line 32 (Breakpoint in the debugging)

![image](https://user-images.githubusercontent.com/97732873/200937893-39c26556-3d65-478d-9504-ff3dacb3cdf9.png)

![image](https://user-images.githubusercontent.com/97732873/200937979-23997a31-3760-4f60-a3b9-d85922d1f6e4.png)

**Comment by joardima** [comment]
Solved, I had pysindy 1.3.0 version and after updating it to 1.7.2 version the script run.

Many thanks
