### ISSUE TITLE
Capturing correct frequencies

### ISSUE THREAD

**Issue by azanparmar** [dynamicslab/pysindy#263]
Hello team,

Most of the frequency data which are present in the nature are in the form of 2*pi*f*t.
In the current implementation of Fourier library we have sin(1t), sin(2t),....sin(nt) where n is an integer.

I tried to approximate the solution with a nearby frequency. The good part is it is identifying the nearest "integer" frequency, but as there is some _delta_ remaining, there is a lag in the data predicted as the time progresses.

Can someone tell a work around where we can make these coefficients as real numbers instead of integers?

![image](https://user-images.githubusercontent.com/117339917/201097067-4b110246-d16b-4006-b3ca-c95e0bd7b8fd.png)

**Comment by akaptano** [comment]
If you are fitting only a Fourier library, as above, you can simple rescale your time series until the plot matches

**Comment by azanparmar** [comment]
> If you are fitting only a Fourier library, as above, you can simple rescale your time series until the plot matches

Rescale the time series? I don't think I am getting what you are trying to suggest Sir.

The input frequency is 31.43 Hz whereas the best captured is 31 Hz or max 32. PySINDY cannot capture 31.43 Hz so how can I match the curves?

**Comment by Jacob-Stevens-Haas** [comment]
To expand on what @akaptano said:

The challenge you're running into is that the coordinate system (both time and independent variable) affects the sparsity of the ODE in any feature library.  For example, fitting $\dot x = \sin x$ in a `PolynomialLibrary` would result in the Taylor series expansion of $\sin$.  Likewise, $\dot x = x^2$, when fit with a `FourierLibrary`, would result in the Fourier cosine series of $x^2$.  Both of these results are not sparse.

There is a nuance to this problem - that sparsity relates to both the chosen library and the chosen coordinate system.  In your case, the ODE is sparse and exact with integer Fourier coefficients __in Hertz__ but not __in radians__.  If you were to rescale your time to be a unitless $\tau = t/(\pi \cdot \text{seconds})$, pysindy would give you an exact match.  This is a simple case, but in general there is no way to know if you are using the correct coordinate system for time or independent variables.
