### ISSUE TITLE
Add examples to documentation

### ISSUE THREAD

**Issue by briandesilva** [dynamicslab/pysindy#27]
We should add examples to the docstrings of top-level functions likely to be called by users (e.g. SINDy, the optimizers, the feature libraries, and the differentiation methods. It's probably fine to borrow examples from our jupyter notebooks when possible.

**Comment by Ohjeah** [comment]
We should also test examples in CI (e.g. `pytest pysindy --doctest-modules --suppress-no-test-exit-code --junitxml=./report/pytest.xml`) and consider sphinx-gallery.
