### ISSUE TITLE
SINDyPI error

### ISSUE THREAD

**Issue by ccrnn** [dynamicslab/pysindy#270]
When I run this example:
https://github.com/dynamicslab/pysindy/blob/master/examples/9_sindypi_with_sympy.ipynb
I'm getting an error:

```
sindy_opt = ps.SINDyPI(
    threshold=1e-6,
    tol=1e-8,
    thresholder="l1",
    max_iter=20000,
)

Traceback (most recent call last):

  File "C:\Users\44745\AppData\Local\Temp\ipykernel_4344\438862360.py", line 1, in <module>
    sindy_opt = ps.SINDyPI(

AttributeError: module 'pysindy' has no attribute 'SINDyPI'
```
(This worked the other week just fine, so it's new - I had to reinstall anaconda to try to get diffeqpy working, so maybe it's on my end? Not sure...)

Also - I'm not sure if I posted in the wrong place and it got missed, or if everyone is busy, but I posted in the discussion forum a few weeks ago. Since then i've managed to fit it on the smaller examples by consecutively fitting the difference, but I'm still having some problems on the test set, so if you are all not too busy at some point let me know & i'll update. If not, I'll try with the Julia route once SINDyPI is working. Thanks :)

**Comment by ccrnn** [comment]
It's 1.7.2.
Thanks!

**Comment by akaptano** [comment]
I am unable to reproduce this error on 1.7.2, so my guess is something is wrong with your python package management. Did you check which PySINDy version is being used when you are inside the example 9 jupyter notebook?

**Comment by ccrnn** [comment]
Ok, thanks for checking - I will try uninstalling everything again tomorrow & starting again.
Hopefully that will work. I'll update on the other stuff then too...

**Comment by ccrnn** [comment]
I had also deleted git along with the python stuff, that was the problem before.

For the things left over from the post over in discussions - firstly, I'm still trying to figure out how to convert the sympy example for my own model. I've changed a few things now, but I get errors in other places. I will keep trying, and might just go over to Julia and do it there (diffeqpy I couldn't get working for DAEs), but if you have time at any point, this example could be made easier to follow if it was clearer which parts of the code are always going to be the same and which depend on the particular model - it's just a little complicated if you don't already understand it.

Secondly, do you have any tips for simulating with concatenated libraries? I'm fitting sequentially the difference from my model because the simulation fails when I concatenate the 2 libraries that seem to work when I do it sequentially. I also wonder if there's still some hyperparameter I've missed trying, because it's fairly close with one library, but still a little too far out to work really well. For now I am running this on reversed data (because of missing data in my dataset), but it's harder to fit sequentially on the forward version, so if there's anything else I can try I might have missed that would be great.

Thirdly, even though when I fit the difference sequentially the results are accurate for the measured time-period, they are still diverging from the test set immediately afterwards. It looks like this:
![image](https://user-images.githubusercontent.com/108372845/206743480-dd19867a-c149-4895-a031-079d6faacd14.png)

while the difference leftover after sequentially fitting the difference looks like:
![image](https://user-images.githubusercontent.com/108372845/206743863-79e89306-6f44-4430-a462-101ac77bc441.png)
So I don't think this is the cause.

It looks like I might need constraints - I need to really think on this since the path i've taken to get here is a bit windy, and what could have been obviously constraints to begin with are now hard to see. Or it might really just need to be implicit. Or I might need to look into PDEs even, because i'm separating out variables from time dynamics using SVD (I just haven't learned PDEs at all yet so i'm not sure if it applies or not). I wondered if you would know just by seeing this which route would be better to try first, because all I would need to spend some significant time on trying. If all else fails I guess I could just simulate forward a little then try fitting the difference there and minusing it off as a kind of after-the-fact constraint. But I feel like I'm being quite messy already, so...

**Comment by ccrnn** [comment]
p.s. in the original discussion entry, I was having problems fitting curves, also. For instance:
![image](https://user-images.githubusercontent.com/108372845/207096572-89e85f06-66a3-43ca-b7e9-fd42458dd602.png)
it's not too big, but I still can't seem to fit it: even if I pass x_dot to 'fit', model.predict is completely different
![image](https://user-images.githubusercontent.com/108372845/207099261-b0b9b6ff-ca6b-49c6-bfd9-76d89377912e.png)
I'm getting quite a lot of these problems, so I wonder if there's something going wrong somewhere that would give an answer to question 2.

**Comment by azanparmar** [comment]
@akaptano I am facing the same error for SINDYPI optimizer. I am also not finding TrappingSR3 optimizer in my pysindy installation. The version installed is 1.7.2.

**Comment by ccrnn** [comment]
I solved this before by reinstalling git for python, but you might need cvxpy:
https://pysindy.readthedocs.io/en/latest/#caveats
