### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hunnder** [dynamicslab/pysindy#272]
![download (4)](https://user-images.githubusercontent.com/120238161/206831662-287bfec5-7515-4597-b734-5696daae6d9b.png)
Hello ,hope you doing fine .
I'm very interesting in pysindy.

as you can see my data does not identically equal my SINDY model I have used PolynomialLibrary  ,FourierLibrary , optimizer = ps.STLSQ .
my question is Could pysindy modify this kind of data or not .
thanks
![download (2)](https://user-images.githubusercontent.com/120238161/206831522-8d3f22a9-e2cf-4bae-ac52-dd841dcc29dc.png)
![download (3)](https://user-images.githubusercontent.com/120238161/206831544-6263a3d1-1977-4d00-910f-830534b9a073.png
![download](https://user-images.githubusercontent.com/120238161/206831403-d1d727e2-c6be-4890-97f1-6c7aa326eabf.png)

**Comment by Jacob-Stevens-Haas** [comment]
I'm sorry, can you provide a more detailed description and a minimal working example?  I am unclear what you are asking.
