### ISSUE TITLE
What is the fitting mechanism behind the multiple trajactories fittting

### ISSUE THREAD

**Issue by JisenesiL** [dynamicslab/pysindy#274]
## Describe the solution you'd like

I wonder what happens when we use multiple trajectories to fit our model. Will the program just fit each trajectory separately and then average the coefficients?

**Comment by akaptano** [comment]
Nope! It will concatenate all the trajectories together and give you back one model generated by fitting all the data. However, you can use the EnsembleOptimizer functionality to subsample the full data, generate different models, and then take an average or anything else.
