### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by shrutishrestha** [dynamicslab/pysindy#276]
I am searching for the Single Pendulum on a Cart dataset. Where can I find it? And, there are data available in the example folder, but is there some docs describing what these data are?

**Comment by Jacob-Stevens-Haas** [comment]
These data are used by the example notebooks - any documentation on them is either in place or in the notebooks that use them.

To generate single pendulum on a cart, you can use the `pysindy.utils.odes.pendulum_on_cart()` function, although, as I mention in #242, it's not clear how that function is parametrized.  I didn't have time to focus on clarifying that, but if you do work with that function, would love help cleaning it up!
