### ISSUE TITLE
 module 'pysindy' has no attribute 'TrappingSR3'

### ISSUE THREAD

**Issue by atabakselahi** [dynamicslab/pysindy#279]
I was trying to run the Trapping SINDy notebook, and I received this error:

AttributeError                            Traceback (most recent call last)
Cell In [3], line 23
     20 constraint_zeros, constraint_matrix = make_constraints(r)
     22 # run trapping SINDy algorithm
---> 23 sindy_opt = ps.TrappingSR3(threshold=threshold, eta=eta,
     24                            max_iter=max_iter, gamma=-1,
     25                            constraint_lhs=constraint_matrix,
     26                            constraint_rhs=constraint_zeros,
     27                            constraint_order="feature",
     28                            )
     30 model = ps.SINDy(
     31     optimizer=sindy_opt,
     32     feature_library=sindy_library,
     33     differentiation_method=ps.FiniteDifference(drop_endpoints=True),
     34 )
     35 model.fit(x_train, t=t, quiet=True)

AttributeError: module 'pysindy' has no attribute 'TrappingSR3'

**Comment by Jacob-Stevens-Haas** [comment]
1. Create a minimal working example that we can copy, paste, and run.
2. what version of pysindy?

**Comment by atabakselahi** [comment]
Thanks for your response. I am trying to go through the example  "8_trapping_sindy_paper_examples.ipynb" and the notebook is in its original form. When I ran the block below the "Mean field section" I received this error message. Here is the link to the screenshot

https://user-images.githubusercontent.com/98827344/214442442-e77c3101-8f63-4f33-891b-8c7d0aade269.png

Thanks for your help.

**Comment by axsano** [comment]
This error can occur due to a package missing from your installation. In my case, I needed to install cvxpy package to import TrappingSR3, which was not installed with pysindy.

**Comment by atabakselahi** [comment]
Thank you so much, it solved my issue.
