### ISSUE TITLE
Is it possible to just re-identify the coefficients of an already trained SINDy model?

### ISSUE THREAD

**Issue by fahim831** [dynamicslab/pysindy#284]
## Is your feature request related to a problem? Please describe.
I was going through [this](https://arxiv.org/abs/1803.00894) paper, also from the Brunton lab, on model re-identification where the authors developed the "abrupt-SINDy" method. The code was said to be publicly available at https://github.com/Ohjeah/sparsereg but it seems to have been archived and made read-only. I was wondering if it was absorbed into the development of PySINDy.

## Describe the solution you'd like
I basically want to re-do what the paper linked above is doing, although probably simpler in the sense that I just want to re-identify nonzero coefficients of an already-trained SINDy model based on new data. The addition or deletion are not necessary, though good to have. I thought all the SINDy works have been integrated into PySINDy. So I just want to know if it already exists in PySINDy and I am not able to find the feature or if it's going to be added in the future.

## Describe alternatives you've considered
At the moment, I think I've somewhat managed it by using ConstrainedSR3 with constraints to ensure all the nonzero entries stay nonzero. But this only prevents addition of new terms. Many terms still end up becoming zero.

**Comment by akaptano** [comment]
As far as I know, this has not been implemented into PySINDy. As you say, you can use ConstrainedSR3 to fix some coefficients (or fix the coefficients to stay within some range of values) and re-identify other coefficients. Depending on you application, I think using ensembling and doing some statistics with the resulting models might be a better way to go anyways.

**Comment by fahim831** [comment]
Thanks. The alternative does seem to work good enough once designed properly. I will continue to use that method.

**Comment by fahim831** [comment]
Thanks. The alternative does seem to work good enough once designed properly. I will continue to use that method.
