### ISSUE TITLE
Failing to simulate and ending up with a straight line instead of the discovered model

### ISSUE THREAD

**Issue by SM-CAU** [dynamicslab/pysindy#285]
Hi , I am Sayeed. Studying Materials Science and Engineering  and working on Magnetoelectric sensors.
I am using SINDy method to predict Magnetoelectric sensor output . When I applied the SINDy-PI on my data it discovers the model closely (for example if I excite my sensor using a sinusoidal signal I get x' = cosx , that seems correct or close.) But when I 
![sindy code](https://user-images.githubusercontent.com/126025023/221412983-36091444-64de-4f49-8d67-70c094d1d4fe.jpg)
![sindy simulated](https://user-images.githubusercontent.com/126025023/221413015-4c1c8ce2-abe7-4621-9e9b-724cf8b0863f.jpg)
simulate the model it always returns a straight line (I used Chirp and Sine signal to excite my sensors and in both cases I came up with a straight line.) It seems SINDy is simulatiing x'=x' in every case. How to get rid of that?

problem 2: I cant zoom in the figure I get after simulation to compare how well is the fit. But in Matlab it zooms well. Can anyone tell me How to solve this? I once accidentally got figures that can be zoomed but I can't reproduce it again.
I am new to coding . Any help would be appreciated.

**Comment by akaptano** [comment]
I think the model is just giving you zeros because it was not able to find a good fit. You should plot the derivative of x_train (model.differentiate(x_train)) versus the model prediction (model.predict(x_train, t=t_train)), which will tell you if your model is fitting the data at all. 

If this is a matplotlib plot, you should be able to zoom in with the magnifying glass icon.

**Comment by SM-CAU** [comment]
Thank you so much for your reply. I am not sure I could implement your hint
properly , I ended up with the same plot. The change I made is attached
below.
Can you please have a short look?
Thanks in advance. Have a great day.

**Comment by SM-CAU** [comment]
Hi,
I have attached the code I used!  
problem description : Based on the assumption that  our sensors motion of equation follows duffing equation which is a 2nd order differential equation, I am trying to predict its output via SINDy method.
Problems facing: 1. Although I am using Matplotlib plot , there is no zooming option. I also tried xlim and ylim but did not actually do anything. I need to be able to zoom a high frequency signal (KHz , e.g.) so that I can see the individual portion of the signal. If I use the zoom button (magnifier glass) option , the image actually doesnt' resolve to anything , just become more hazy.
problem 2: the model actually performig so bad that its correlation factor is almost 0. I think SINDy should give good result if I use only polynomial library

![Sindy_Sine_1](https://user-images.githubusercontent.com/126025023/225775146-327f0994-175b-4096-b8dd-d6d0901c8e0e.jpg)
![sindy_sine_2](https://user-images.githubusercontent.com/126025023/225775147-2d00e43b-dd66-4f7b-b4f3-0f5bf383247e.jpg)
![sindy_sine_3](https://user-images.githubusercontent.com/126025023/225775149-7897c8f8-a634-4cc4-aac4-01d0dd502356.jpg)
![sindy_sine_4](https://user-images.githubusercontent.com/126025023/225775150-bff6b29a-15e6-497b-bc73-5e0560496f11.jpg)
![sindy_sine_5](https://user-images.githubusercontent.com/126025023/225775151-a15ffa92-0101-4ace-a321-84a820ba652d.jpg)

**Comment by akaptano** [comment]
I think I agree with what you did here -- however if this is a Duffing system, presumably there is a control input that drives the system like cosine(omega * t). If this term is not modeled in the ODEs you will indeed get something very wrong. If that is the case, you can give that a try by using the FourierLibrary with Cosines, applied to the 't' variable. This functionality is provided for by the GeneralizedLibrary class. See the example 1 jupyter notebook for an example of the use case. If this system does not have a driving term, let me know and I will stare at the code a bit harder.

Best,
Alan

**Comment by SM-CAU** [comment]
Hey,
I tried to do  apply this generalized library according to the example. i also watched your tutorial videos on you-tube several times,   but it seems like I am stuck and to be honest I did not understand the implementation. how can I pass it to sindy so that it generates the fourier library using only t variable? 
How  the tile function is linking to the inputs? How do they know 0 or 1= x_train (x and xdot stacked), or t_train?
Your suggestion make sense as this term is also evolving with time and in every instance should ( or say it might) have different driving force on my magnetostrictive layer of the sensor. I added my implementation, but its actually didnt reflect  my intention.

Best, Sayeed
![trying generalized library](https://user-images.githubusercontent.com/126025023/226631819-011ed48b-2de6-4b10-ac4b-94075afeb3da.jpg)

**Comment by akaptano** [comment]
Can you post your code as text/jupyter notebook here so I can copy and paste the full script to a jupyter notebook and check for issues?

**Comment by SM-CAU** [comment]
Hi, Sure! The code isd attached as a jupyter notebook file.

**Comment by akaptano** [comment]
I do not see the file here or in the email you sent, double check that please :)

**Comment by SM-CAU** [comment]
[sensor_chirp.txt](https://github.com/dynamicslab/pysindy/files/11151344/sensor_chirp.txt)
Hey, sorry for the inconvenience. In the email the attachment is still there but in the github ithe json file appears not be supported with.
I hope it works this time.

**Comment by SM-CAU** [comment]
Hi,
I could apply the generalized library as you recommended but still end-up with very por performance. Can you please give me hint to make it perform better?
[### sindy prediction of the collected da.txt](https://github.com/dynamicslab/pysindy/files/11240645/sindy.prediction.of.the.collected.da.txt)

**Comment by akaptano** [comment]
I am still unable to help you. You have not provided a detailed error/issue message or pictures showing the poor model performance + I do not have the .mat file of the data you are using in this jupyter notebook, so I can only stare at the code you sent.

**Comment by SM-CAU** [comment]
Hello,
The poor performance was the same as before using the generalized library
which I have given before, that's why I thought it would be a
repetition and didn't do so.
Whatsoever, the data file is attached below. In github I am unable to share
a .mat file , so I am providing it via email.
Best ,
Sayeed.

**Comment by SM-CAU** [comment]
its solved.
