### ISSUE TITLE
2-order time derivative PDE solution

### ISSUE THREAD

**Issue by 1230lw** [dynamicslab/pysindy#296]
The current PDE is the 1-order derivative of time, is there a PDE solution for the 2 or higher order derivative of time?
eg:I want to identity The vibration equation of the string：u_tt-a^2*u_xx=0

**Comment by akaptano** [comment]
The way we typically deal with this is to rewrite this second-order PDE as a system of 2 first-order PDEs. This can always be done -- in your case set w = u_t and write out the equations. You can also fit this second order PDE directly by computing u_tt yourself and passing it as the "x_dot" parameter in model.fit(...)
