### ISSUE TITLE
Simpler `inputs_per_library` in GeneralizedLibrary?

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [dynamicslab/pysindy#306]
A `GeneralizedLibrary.inputs_per_library` describes which variables to use for which input library.  Rather than having a list (for each library...) of lists (...use these input variables indices) or a numpy array of True/False (0-axis: library, 1-axis: input variables), we have a numpy array of indices.  I'd like to make a case for either of the first two alternatives over the current system, with a slight preference for the former.

The way the numpy array of indices works is that repeat indices are ignored (`np.unique(self.inputs_per_library_[i, :])`), but still needed because numpy arrays cannot be ragged.  For instance, a `GeneralizedLibrary` containing a `PolynomialLibrary` for `x` and `y` with a `FourierLibrary` for `z` has any of the following `inputs_per_library`:

```python
# Most simple, but weird repeat of number 2.
np.array([
    [0, 1],
    [2, 2]
])

# most common in code, makes some sense because number of columns is number of indices
np.array([
    [0, 1, 0], # or [1, 0, 0], or [0, 1, 1], &c
    [2, 2, 2]
])

# silly but works.
np.array([
    [0, 1, 0, 1, 0, 1, 0, 0, 0],
    [2, 2, 2, 2, 2, 2, 2, 2, 2]
])
```

Compare that to the alternatives:
```python
# removing duplicates becomes set(inputs_per_library[i])
[[0, 1], [2]]

# similar to how TensoredLibrary uses booleans to indicate inclusion in a tensor product
np.array([
    [True, True, False],
    [False, False, True]
])
```
The documentation in `GeneralizedLibrary` isn't totally clear, and the current convention requires code that serves no purpose than padding the array with values (and breaks if padded with the wrong value).  Here's an excerpt from the new `ParametrizedLibrary`:

```python
feature_input = np.zeros(num_features + num_parameters, dtype=np.int32)
feature_input[:num_features] = np.arange(num_features)

parameter_input = (
    np.ones(num_features + num_parameters, dtype=np.int32) * num_features
)
parameter_input[-num_parameters:] = num_features + np.arange(num_parameters)

inputs_per_libraries = np.array([parameter_input, feature_input])
```

Here's the two alternatives:
```python
# instantly understandable
inputs_per_libraries = [range(num_features, num_parameters+num_features), range(num_features)]

# or, still pretty understandable
inputs_per_libraries = np.zeros((2, num_parameters+num_features), dtype=bool)
inputs_per_libraries[0, range(num_features, num_features+num_parameters)] = True
inputs_per_libraries[1, range(num_features)] = True
```

The former method also has the advantage of being distinguishable from existing uses, making deprecation simpler.  I'm not advocating any particular timeline, but I'd like to hear how other people feel about the matter.  Not the world's biggest issue, but I feel like we get a lot of issues on how to do generalized libraries, and every time I troubleshoot bugs in a PR I have a moment of confusion looking it up.  What are people's thoughts?

**Comment by znicolaou** [comment]
Hey @Jacob-Stevens-Haas, totally agree that the numpy array format for the generalized library input is pretty terrible. I like the list of lists approach as well, and would be very happy to see it implemented. Since the generalized library is integrated into a few different examples and other libraries, could you start up a new branch if you decide to try it? I think I will have some time to help too.
