### ISSUE TITLE
Saving/Loading a pysindy model similar to ML/DL models using Joblib or Pickle

### ISSUE THREAD

**Issue by bkhaldi** [dynamicslab/pysindy#313]
We are experimenting with pysindy utilizing a large X input matrix collected from real and simulation measurements, and instead of going through the process of building and fitting the pysindy model each time we want to use it, we aim to save and load it later for prediction and forward simulation. Is it possible to accomplish anything similar to what we did usually with any machine learning or deep learning models using joblib or pickle as examples?

I already tested both of these, but none of them work.

**Comment by Jacob-Stevens-Haas** [comment]
Please demonstrate a minimal working example that we can run to demonstrate your error, as well as any error traceback.

Also, to reuse pickled objects, it's required to import the related package before unpickling them, as [python objects are pickled by fully qualified name](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled).  Does this fix your issue?
