### ISSUE TITLE
[BUG] PDELibrary and WeakPDELibrary feature name order with multiple input features and interactions

### ISSUE THREAD

**Issue by znicolaou** [dynamicslab/pysindy#315]
I'm pretty sure the order of the feature names produced by `lib.get_feature_names()` does not coincide with the order of the library terms produced by `lib.transform(x_full)` when there are more than one input feature and `include_interactoins=True`. I don't think this case is currently used in any of the examples, since it requires a pretty complex problem to appear (most of the high-dimensional problems use `include_interactions=False` to keep the number of library terms and the runtime under control). 

The `transform` function takes advantage of vectorized numpy multiplication to calculate the products of the terms produced by `library_functions` and the differential terms determined by `multiindices`, as in 
```
            # mixed function derivative terms
            shape[-1] = n_library_terms * self.num_derivatives * n_features
            if self.include_interaction:
                xp[
                    ...,
                    library_idx : library_idx
                    + n_library_terms * self.num_derivatives * n_features,
                ] = np.reshape(
                    library_functions[..., np.newaxis, :]
                    * library_derivatives[..., :, np.newaxis],
                    shape,
                )
                library_idx += n_library_terms * self.num_derivatives * n_features
```
in the `PDELibrary` case at line 472. 

The `get_feature_names()` currently builds the names in a more tedious set of four unravelled for loop, since string concatenation is harder to map over numpy arrays than multiplication, as in 
```
        # Include mixed non-derivative + derivative terms
        if self.include_interaction:
            for k in range(self.num_derivatives):
                for jj in range(n_features):
                    for i, f in enumerate(self.functions):
                        for c in self._combinations(
                            n_features,
                            f.__code__.co_argcount,
                            self.interaction_only,
                        ):

                            feature_names.append(
                                self.function_names[i](*[input_features[j] for j in c])
                                + input_features[jj]
                                + "_"
                                + derivative_string(self.multiindices[k])
                            )
```
in the `PDELibrary` case at line 316. 

But the four unraveled loops here need to be carefully reordered so that the names correspond to the order produced by `np.reshape` in `transform`. I'm going to try to debug this soon, but wanted to record the issue here in case anyone is having trouble.

**Comment by Jacob-Stevens-Haas** [comment]
Interesting issue @znicolaou!  FWIW although the `+` and `-` operators don't work elementwise on string arrays, `np.char` has functions that do map/broadcast well for strings.  e.g. to do concatenation, outer-product style, it would be:
```python
import numpy as np
temp = np.array(["a", "b", "c"])
np.char.add(temp[:, np.newaxis], temp[np.newaxis, :])

array([['aa', 'ab', 'ac'],
       ['ba', 'bb', 'bc'],
       ['ca', 'cb', 'cc']], dtype='<U2')
```

**Comment by znicolaou** [comment]
Thanks for the suggestion @Jacob-Stevens-Haas! Should work I think--I did a little test to make sure that the ordering can be done consistently, as in:
```
vals1=np.random.random(size=(5,4))
vals2=np.random.random(size=(3,2))
vals=vals1.reshape(1,-1)*vals2.reshape(-1,1)
stringvals=np.char.add(np.char.add(vals1.astype(str).reshape(1,-1),'*'),vals2.astype(str).reshape(-1,1))
np.vectorize(eval)(stringvals)-vals
```
Hoping to implement the actual library versions in `get_feature_names` in the next day or two.

**Comment by znicolaou** [comment]
I fixed this today, using the suggestion of @Jacob-Stevens-Haas for the `PDELibrary` and swapping the order of a couple of `for` loops for the `WeakPDELibrary`. 

To test things, I replaced the previous nonlinear diffusion example in examples/12_weakform_SINDy_examples.ipynb with a much more extensive example on compressible flow equations. The old example tested the mixed function/derivative terms with $u_t = u u_{xx}$, which only had one input feature, so this bug went unnoticed. The new example is

$$\mathbf{u}_ t = -(\mathbf{u}\cdot\nabla)\mathbf{u} + (-\nabla P + \mu \nabla^2 \mathbf{u})/\rho,$$

$$ \rho_ t = -\nabla \cdot(\rho \mathbf{u}),$$

with $P = \rho R T$, which has three input features. The conclusion is the same--both the `PDELibrary` and the `WeakPDELibrary` can handle the noiseless data, but only the `WeakPDELibrary` works well with noise.

I also noticed a small typo in the Burger's equation example in examples/10_PDEFIND_examples.ipynb, where a `u_train` appeared for one fit rather than a `u`.

I'm going to push an update directly to master, since the changes are minimal and fix a bug.
