### ISSUE TITLE
[BUG] Intallation

### ISSUE THREAD

**Issue by erangit** [dynamicslab/pysindy#316]
Install using pip
pip install pysindy 
Install the main package using anaconda, but utils package contains only base.

That way :
from pysindy.utils import linear_damped_SHO 
from pysindy.utils import lorenz 

and other similar imports fail.

**Comment by erangit** [comment]
Hi
I installed using pip, as you have written above
The sw was installed at 
~/anaconda3/lib/python3.7/site-packages/pysindy
This is why I mentioned anaconda.

The utils folder there contains only base.py and the __init_.py  contains only one line:
from .base import *

I tried to download manually from git the utils folder (which contains more py files and the init is much larger) and
replace  this folder with the above mentioned utils, but then even pysindy import failed:
import pysindy as ps
..... some messages then :
ImportError: cannot import name 'capped_simplex_projection' from 'pysindy.utils.base' (~/anaconda3/lib/python3.7/site-packages/pysindy/utils/base.py)

Using the original utils (the one installed by pip) import pysidney works and I managed to reproduce the first example in the documentation. The problem is related to proper installation of the util methods

Thanks,
Eran

**Comment by erangit** [comment]
Thanks for the prompt response but this is not the problem:
which pip   => ~/anaconda3/bin/pip
which python =>~ /anaconda3/bin/python

The pip installed the pysindy  in the anaconda site_packages, but it installed only a lean utils

**Comment by erangit** [comment]
~/anaconda3/bin/pip  and ~/anaconda3/bin/python 
Seems that the ~ sign 
creates a line over text beyond it

**Comment by znicolaou** [comment]
Then I would guess that something is corrupted in your base conda environment. I just created a conda environment with only pip and installed pysindy with pip on my machine:
```
conda create -n test pip
conda activate test
pip install pysindy
```
I verified that the example 1 notebook runs successfully after installing jupyter as well `conda install jupyter`.  Can you try making a new environment and installing with pip?

**Comment by erangit** [comment]
Thanks. This was the case.
I had jupyter installed for another environment, and python was 3.7.6 and not 3.11 like now.
Working well now. Thanks a lot

**Comment by Jacob-Stevens-Haas** [comment]
@erangit if it's helpful in the future, you can also diagnose environment/install issues from within python.

E.g. 
```
import sys
import pysindy

print(sys.executable)
print(sys.path)
print(pysindy.__file__)
```

This would tell you which python interpreter you're using, where it searches for installed packages, and where it found `pysindy`.  You can compare it to the output of `pip install pysindy`, which lists the directories it's installing in.
