### ISSUE TITLE
Fixing the solution to some variables while allowing them to be used elsewhere

### ISSUE THREAD

**Issue by YuvalShechter** [dynamicslab/pysindy#324]
I've been looking around the docs but I haven't found a way to explicitly fix some of the data variable equations so that they can be used to generate other equations. 
**Specifically** I have data series' for four variables (x, xp, a, ap) and I want to fix x' = xp and a' = ap and have pysindy only solve for xp' and ap' while still using x, a and having their relationship to xp and ap inform the resulting equation. 
Is this something possible to do? If not is there a viable alternative? Thanks!

**Comment by akaptano** [comment]
Yes, you can use the ConstrainedSR3 optimizer to prescribe x' = xp and a' = ap as constraints, and fit the remaining equations with all four variables. Check out the Example 1 Jupyter notebook for how to use this optimizer and report back if you're still having issues!

Best,
Alan

**Comment by Jacob-Stevens-Haas** [comment]
Yes, pass `u=np.stack((x, xp), -1)` or the like to pass these as control variables.

**Comment by Jacob-Stevens-Haas** [comment]
Also FWIW, you can pass `x` and `a` as control variables so that SINDy will include them in features but not fit equations for _their_ derivatives.

**Comment by YuvalShechter** [comment]
Ok I have it figured out but I was wondering if there was a better way of zeroing out all coefficients besides something to this effect:
```
constraint_lhs = np.zeros((2*n_features, 4*n_features))

constraint_rhs = np.array([1, 1] + [0]*(2*n_features - 2))

constraint_lhs[0, :] = np.array([0]*(4*n_features))
constraint_lhs[0, 3] = 1
constraint_lhs[1, :] = np.array([0]*(4*n_features))
constraint_lhs[1, 4+n_features] = 1

other_coeffs_to_0 = list(range(0, 3))+list(range(4, 4+n_features))+list(range(4+n_features + 1, 2*n_features))
for j, i in enumerate(other_coeffs_to_0):
    constraint_lhs[j+2, :] = np.array([0]*(4*n_features))
    constraint_lhs[j+2, i] = 1
```
