### ISSUE TITLE
read the docs links broken

### ISSUE THREAD

**Issue by florisvb** [dynamicslab/pysindy#326]
The read the docs links in the readme are broken, eg:

https://pysindy.readthedocs.io/en/latest/examples/2_introduction_to_sindy.html
https://pysindy.readthedocs.io/en/latest/examples/1_feature_overview.html

**Comment by znicolaou** [comment]
Hi @florisvb ,

From where were you directed to those links? The current links can be found here: https://pysindy.readthedocs.io/en/latest/examples/index.html. But if we have those older links posted somewhere, we should update them too.

**Comment by florisvb** [comment]
The main README, e.g. here:

Each row of this matrix equation corresponds to one coordinate function of f(x). SINDy employs sparse regression techniques to find a solution Xi with sparse column vectors. For a more in-depth look at the mathematical foundations of SINDy, please see our [introduction to SINDy](https://pysindy.readthedocs.io/en/latest/examples/2_introduction_to_sindy.html).

and here:

PySINDy provides numerous other features not shown here. We recommend the [feature overview](https://pysindy.readthedocs.io/en/latest/examples/1_feature_overview.html) section of the documentation for a more exhaustive summary of additional features.

**Comment by znicolaou** [comment]
Thanks! Will update them shortly.
