### ISSUE TITLE
Create option for column interdependence

### ISSUE THREAD

**Issue by kpchamp** [dynamicslab/pysindy#33]
In the current implementation, SINDy models are fit using multi-output regression (i.e. each column of the coefficient matrix is fit separately). Some advanced features that we may implement as extensions will require interdependence among columns. Examples include trimming corrupt data points and imposing constraints on the coefficients.

**Comment by briandesilva** [comment]
I think we'll probably want to deal with this and #7 simultaneously. The solution to that problem depends on the fact that we're working with a MultiOutputRegressor under the hood and solving this issue might require us to change that.

**Comment by kpchamp** [comment]
Handled in #49
