### ISSUE TITLE
[BUG] WeakSindy gets stuck in infinite loop. Is there a way to fix?

### ISSUE THREAD

**Issue by samholt** [dynamicslab/pysindy#335]
When using WeakSINDy to fit small trajectories, where they can be variable sizes, with `multiple_trajectories=True`, WeakSINDy gets stuck in an infinite loop within it's `WeakPDELibrary._set_up_weights` function. Is there any way to fix this? 

### Reproducing code example:

```python
import pysindy
import numpy as np

library_functions = [lambda x: x, lambda x, y: x * y]
library_function_names = [lambda x: f'{x}', lambda x, y: f'{x} {y}']
model = pysindy.SINDy(feature_library=pysindy.WeakPDELibrary(
                                    library_functions=library_functions,
                                    function_names=library_function_names,
                                    spatiotemporal_grid=np.array([1,2]),
                                    include_bias=True,
                                    is_uniform=True,
                                    K=100),
                    optimizer = pysindy.SR3(threshold=0.1, thresholder="l1", max_iter=1000, normalize_columns=True, tol=1e-1))
model.fit([np.array([[1],[2]]), np.array([[5],[6]])], t=1, multiple_trajectories=True)
model.print()
```

### Error message:

Stuck in an infinite loop within `WeakPDELibrary._set_up_weights`

### PySINDy/Python version information:

1.7.5 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]

### Comment

I love SINDy and WeakSINDy, and am trying to use it for my current research, however this is a blocking issue at the moment. Interestingly normal SINDy works with this type of data e.g.,

```python
import pysindy
import numpy as np

library_functions = [lambda x: x, lambda x, y: x * y]
library_function_names = [lambda x: f'{x}', lambda x, y: f'{x} {y}']
model = pysindy.SINDy(optimizer=pysindy.STLSQ(threshold=0.1, alpha=0.5, max_iter=100, ridge_kw={'tol': 1e-6}),  differentiation_method=pysindy.FiniteDifference(drop_endpoints=False, order=1), feature_library=pysindy.PolynomialLibrary(degree=2, interaction_only=True))
model.fit([np.array([[1],[2]]), np.array([[5],[6]])], t=1, multiple_trajectories=True)
model.print()
```

**Comment by akaptano** [comment]
@znicolaou can correct me, but I think this is the same issue as #327 and we hope to add a line of code to warn/error-check for this in the next release. Let me know if this does not resolve your issue.

**Comment by znicolaou** [comment]
I think you're right, @akaptano -- hoping to add a warning/fix sometime soon! @samholt , try increasing H_xt to ensure that subdomains can be found.

**Comment by samholt** [comment]
Hi @znicolaou @akaptano 

Thank you so much for the quick response. 

Increasing H_xt to the largest possible value it can be in this example (i.e., `H_xt=[0.49]`), still makes it get stuck in the infinite loop. Is there any way at all to bypass this for now to get it to work on a dataset like the one presented in the minimal example? 

Thank you so much!

**Comment by znicolaou** [comment]
Looking more closely at the example, with just two input data points, there are no reasonably weak features that could be constructed. It would be possible with three or four input data points, but this is still way too little data to ever produce a reasonable fit, and the weak method will offer no benefit over a direct approach here.

**Comment by samholt** [comment]
Hi @znicolaou 

Thank you so much for this response. That is helpful to know that, sadly WeakSINDy is not suitable for this problem. Can you provide more details about this "direct approach" you mention?

Thank you so much

**Comment by znicolaou** [comment]
I meant the normal SINDy fit like you used with the `PolynomialLibrary` in your example above. The weak approach does a lot more processing to produce its features, which is why more data is needed in that case.It is helpful when you have a lot of data that is corrupted by noise, but when you have very little data, I'd recommend a simpler "normal" SINDy fit, or even perhaps a simpler regression that does not aim to promote sparsity. If you are only trying to find a best fit for 10 or less data points, I wouldn't expect the data to really contain enough information to be able to give you accurate sparse governing equations, since there are generally many sparse models that can reproduce data on just a few points (that is a classic overfitting issue).
