### ISSUE TITLE
[BUG]pip command in different shells

### ISSUE THREAD

**Issue by MPeng5** [dynamicslab/pysindy#344]
It seems that the pip command lines provided can only be used with Bash. Zshell doesn't support those options with the square brackets.

```zsh
pip install .[dev]
```

### Error message:

zsh: no matches found: .[dev]

**Comment by Jacob-Stevens-Haas** [comment]
The brackets are the way `pip` defines optional dependencies.  If there's an error using pip, as designed, in zsh, then I believe that's an error in either of those programs.

fwiw, does 
```
pip install .
```

work in Zshell?

**Comment by MPeng5** [comment]
> The brackets are the way `pip` defines optional dependencies. If there's an error using pip, as designed, in zsh, then I believe that's an error in either of those programs and not in pysindy.
> 
> fwiw, does
> 
> ```
> pip install .
> ```
> 
> work in Zshell?

Yes, those original ones work fine. I found this because I reset my MacBook recently so I had to reinstall the package again. It definitely has nothing to do with pysindy and since one can still use Bash on a Mac, it is probably better to point this out in the doc.

**Comment by Jacob-Stevens-Haas** [comment]
The solution is to use single quotes around any argument that uses square brackets: https://stackoverflow.com/a/30539963/534674

Since this is a question of how to use `pip` in ZShell, I don't think pysindy needs any more documentation on this bug than this issue.
