### ISSUE TITLE
Issue of precision in model.print() command and plotting of time series graph in SINDy-PI algorithm

### ISSUE THREAD

**Issue by anur2203** [dynamicslab/pysindy#350]
I am using SINDy-PI algorithm on my model.
When I am using default  value of precision in model.print it gives correct equation but when I am setting precision=4 or 5 then it gives many irrelvent terms( a very large equation).
How I can deal with it?
How can I plot the time series graph with implicit equations?

**Comment by Jacob-Stevens-Haas** [comment]
1. To clarify, SINDy is finding a lot of small terms of the order 1e-4?

2. `SINDy.simulate()`

**Comment by anur2203** [comment]
Can I omit the terms of order >= 1e-4 in SINDy-PI ?

**Comment by znicolaou** [comment]
@anur2203 , yes, you need to do a hyperparameter scan to find the appropriate hyperparameters for your fit. Look at the example notebooks and read the many papers on SINDy, but for the `STLSQ` case, for example, just increase `threshold` until it omits the terms you want to exclude.
