### ISSUE TITLE
Examples for unified approach

### ISSUE THREAD

**Issue by GioeleBuriani** [dynamicslab/pysindy#357]
Hello,

In the description you mentioned the fact that this package has "implementations for [...] including the unified optimization approach of Champion et al. (2019), [...]".

I was wondering if you had any example or any suggestion that explain how to use this library for the unified approach as I seem not to find anything already present on this matter.

Thank you very much and have a nice day!

Best regards,
Gioele

**Comment by Jacob-Stevens-Haas** [comment]
Their method is in the `SR3` optimizer.  The Example1 notebook describes all of the optimizers, including their SR3 method.  See [here](https://pysindy.readthedocs.io/en/latest/examples/1_feature_overview/example.html#SR3).  Also, the docstring for SR3 and Constrained SR3. You can run `help(pysindy.SR3)` or `help(pysindy.ConstrainedSR3)`.
