### ISSUE TITLE
Improve STLSQ

### ISSUE THREAD

**Issue by briandesilva** [dynamicslab/pysindy#36]
Setting the `alpha` (L2 regularization) parameter for the `STLSQ` optimizer improves the condition number of the least-squares problems that are solved, leading to better overall results when features are close to linearly dependent. However, it adds some bias to the learned coefficients (toward 0). We should consider modifying `STLSQ` (and maybe some of our other methods) by changing it to a two-step procedure when `alpha` is positive:
1. Use the existing algorithm with regularization to identify the support
2. Perform one last *unregularized* least-squares fit using only the features/terms identified in step 1.

**Comment by Ohjeah** [comment]
This was already a feature in the upstream repo `sparsereg`, see https://github.com/Ohjeah/sparsereg/blob/master/sparsereg/model/base.py#L219 and can be cherry-picked.

**Comment by Ohjeah** [comment]
This needs to be fixed for the other optimizers as well.

**Comment by briandesilva** [comment]
Fixed in #39
