### ISSUE TITLE
module 'pysindy' has no attribute 'SINDyPI'

### ISSUE THREAD

**Issue by penguinaugustus** [dynamicslab/pysindy#366]
Hi, I meet some problems when i try to run the sample of implicit-ODEs: 
https://pysindy.readthedocs.io/en/latest/examples/15_pysindy_lectures/example.html#Implicit-ODEs
the error was
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/cd/5hbmg50x21dcv5w59_3cwdrm0000gn/T/ipykernel_3812/3017384247.py in <module>
     49 '''
     50 
---> 51 sindy_opt = ps.SINDyPI(
     52     threshold=1e-6,
     53     tol=1e-8,

AttributeError: module 'pysindy' has no attribute 'SINDyPI'
```
I found a similar issue here:  https://github.com/dynamicslab/pysindy/issues/270
However, it seems that the current solution is to reinstall python. I tried to run the same example on another computer, still meet the same issue. Could you give me some instruction on how to deal with the problem? Thank you for your time!

_________________________-
My python version:
computer 1:   3.8.8
computer 2:  3.9.13 
pysindy version: both 1.7.5

**Comment by Jacob-Stevens-Haas** [comment]
`SINDyPI` requires `cvxpy`.  Run  `pip install pysindy[cvxpy]`

**Comment by penguinaugustus** [comment]
thank you for your reply! However, i still met some problem:
first I tried `pip install pysindy[cvxpy]` i got 
```
zsh:1: no matches found: pysindy[cvxpy]
Note: you may need to restart the kernel to use updated packages.
```
I restart the kernel but still `AttributeError: module 'pysindy' has no attribute 'SINDyPI'`
Then i try to upgrade my pip with `pip install --upgrade pip setuptools` and try `pip install pysindy[cvxpy]` again, but get the same result. Then i try `pip install "pysindy[cvxpy]"`, the result was:
```
Requirement already satisfied: pysindy[cvxpy] in /Users/yufu/opt/anaconda3/lib/python3.9/site-packages (1.7.5)
WARNING: pysindy 1.7.5 does not provide the extra 'cvxpy'
Requirement already satisfied: scikit-learn>=0.23 in /Users/yufu/opt/anaconda3/lib/python3.9/site-packages (from pysindy[cvxpy]) (1.0.2)
Requirement already satisfied: numpy in /Users/yufu/opt/anaconda3/lib/python3.9/site-packages (from pysindy[cvxpy]) (1.21.5)
.......
Note: you may need to restart the kernel to use updated packages.
```
could you give me some instruction on it? thank you so much on your help!

**Comment by Jacob-Stevens-Haas** [comment]
Oh I see you opened a new Issue.  Closing this one again.
