### ISSUE TITLE
zsh:1: no matches found: pysindy[cvxpy]

### ISSUE THREAD

**Issue by penguinaugustus** [dynamicslab/pysindy#369]
Hi, yesterday i submitted an issue on `module 'pysindy' has no attribute 'SINDyPI'` and got reply: https://github.com/dynamicslab/pysindy/issues/366
However, i still met some problem:
first I tried `pip install pysindy[cvxpy]` i got 
```
zsh:1: no matches found: pysindy[cvxpy]
Note: you may need to restart the kernel to use updated packages.
```
I restart the kernel but still `AttributeError: module 'pysindy' has no attribute 'SINDyPI'`
Then i try to upgrade my pip with `pip install --upgrade pip setuptools` and try `pip install pysindy[cvxpy]` again, but get the same result. Then i try `pip install "pysindy[cvxpy]"`, the result was:
```
Requirement already satisfied: pysindy[cvxpy] in /Users/yufu/opt/anaconda3/lib/python3.9/site-packages (1.7.5)
WARNING: pysindy 1.7.5 does not provide the extra 'cvxpy'
Requirement already satisfied: scikit-learn>=0.23 in /Users/yufu/opt/anaconda3/lib/python3.9/site-packages (from pysindy[cvxpy]) (1.0.2)
Requirement already satisfied: numpy in /Users/yufu/opt/anaconda3/lib/python3.9/site-packages (from pysindy[cvxpy]) (1.21.5)
.......
Note: you may need to restart the kernel to use updated packages.
```
could you give me some instruction on it? thank you so much on your help!

**Comment by Jacob-Stevens-Haas** [comment]
Sorry, I see that 1.7.5 didn't include the `cvxpy` extra.  Manually install the following packages should clear the error:

```
pip install cvxpy scs>=2.1,!=2.1.4
```

**Comment by penguinaugustus** [comment]
Thank you so much for your help! First i tried `pip install cvxpy scs>=2.1,!=2.1.4`. i was returned with 
```
zsh:1: 2.1,!=2.1.4 not found
Note: you may need to restart the kernel to use updated packages.
```
then i tried `pip install 'cvxpy' 'scs>=2.1' 'scs!=2.1.4'`. it worked!

**Comment by Jacob-Stevens-Haas** [comment]
yes, sorry, different shells can be finnicky with whitespace and different characters.
