### ISSUE TITLE
 SparseNonLinearModel for poly_order >=3

### ISSUE THREAD

**Issue by rochabm** [dynamicslab/pysindy#378]
I would like to have support for this SparseNonLinearModel class for poly_orders greater than 3.
Is there a quick way around to get that by myself?

**Comment by Jacob-Stevens-Haas** [comment]
Are you asking for `SINDy(feature_library=PolynomialLibrary(degree=k))` for k>3?

**Comment by rochabm** [comment]
I guess yes. Sorry, for my confusion, but in fact I am using dyn-opt package (https://github.com/billtubbs/dyn-opt) which encapsulates SINDy for handling problems with forcing terms, and their class SparseNonLinearModel has the limitation of poly_order up to 3. 

I did not find any working example in PySINDy to working with sparse identification considering forcing terms, then I had to start with this dyn-opt package.

Maybe. this is a limitation (dyn-opt) from their library, right?

**Comment by Jacob-Stevens-Haas** [comment]
That package doesn't import pysindy.  It's an entirely separate implementation.

**Comment by rochabm** [comment]
OK! Thank you so much for your kind attention.
Is there an example of the pysindy implementation working with forcing terms? I missed that, although I was able to find the theoretical papers on that, but not on the library.

**Comment by Jacob-Stevens-Haas** [comment]
Treat `t` like a control variable and add forcing terms to your `feature_library`.  You can use `GeneralizedLibrary` to combine a separate library for field terms and forcing terms, and even use a `ConstrainedSR3` optimizer if you know the coefficient of the forcing terms.

There should be examples of all three of these in  `./examples/1_feature_overview/example.ipynb` .
