### ISSUE TITLE
Extracting eigenvalues and eigenvectors from coefficients

### ISSUE THREAD

**Issue by sagastra** [dynamicslab/pysindy#381]
Does anyone know how to extract eigenvalues and eigenvectors for the polynomial expansion ? I think the linear solution is pretty straight forward, but would be nice to just call a function on the model.coefficients and returns both of them to you,

Thanks !!!!

**Comment by Jacob-Stevens-Haas** [comment]
Can you explain what you mean, or provide a minimal working example?  What is `model.coefficients` lacking, and perhaps is `optimizer.coef_` what you're looking for?

**Comment by Jacob-Stevens-Haas** [comment]
Closed due to inactivity.
