### ISSUE TITLE
Anosov flows

### ISSUE THREAD

**Issue by westurner** [dynamicslab/pysindy#383]
## Is your feature request related to a problem? Please describe.
- STORY: Users can generalize about dynamical systems with insufficient samples (and Anosov flows)

## Describe the solution you'd like
- https://www.quantamagazine.org/flow-proof-helps-mathematicians-find-stability-in-chaos-20230615/
  - (TIL about) Anosov flows, and there's a pendulum infographic, like "Deep Learning of Dynamics and Coordinates with SINDy Autoencoders" (2020) https://www.youtube.com/watch?v=WHhDgxkiR9c

## Describe alternatives you've considered
- https://www.google.com/search?&q=awesome+autoencoder+site%3Agithub.com
- Quantum Algorithms, Quantum Computers
  - https://qiskit.org/ecosystem/machine-learning/tutorials/12_quantum_autoencoder.html
    - https://en.wikipedia.org/wiki/Church%E2%80%93Turing%E2%80%93Deutsch_principle
      - https://en.wikipedia.org/wiki/Quantum_complexity_theory#Simulation_of_quantum_circuits
        - If the data is known to be of a quantum statistical process, can a classical autoencoder be sufficient (like how numerical solutions to n-body gravity problems are possible but not a complete set of solutions)?
  - https://github.com/tequilahub/tequila ; expectation values w/ various simulators and real QC
  - https://github.com/topics/quantum-fluids
    - Gross-Pitaevskii equations for:
      - Bose-Einstein Condensate *super*fluids
      - Superfluid Quantum Gravity w/ vortices (and Bernoulli's and Navier-Stokes)
      - https://en.wikipedia.org/wiki/Quantum_fluid
        > Quantum mechanical effects become significant for physics in the range of the [de Broglie wavelength](https://en.wikipedia.org/wiki/De_Broglie_wavelength). For condensed matter, this is when the de Broglie wavelength of a particle is greater than the spacing between the particles in the lattice that comprises the matter.
      - https://www.researchgate.net/figure/Comparison-between-the-velocities-of-a-quantum-superfluid-vortex-with-l-1-quantum_fig2_23757600 : 
      - "Quantum-like gravity waves and vortices in a classical
fluid" (2009) https://arxiv.org/abs/0901.1270 https://scholar.google.com/scholar?cluster=14044130315847002901&hl=en&as_sdt=5,43&sciodt=0,43
        > However, one can write in this
        > case a system of hydrodynamic equations in terms of a continuity equation and of a two-
        > dimensional Euler equation where the density is replaced by the height profile of the fluid
        > surface (see, e.g., [8]). Our new proposal is therefore to build a quantum-like potential,
        > and then a wave function, from the square root of the surface height. One can then show
        > that the gravity waves at the surface of a fluid subjected to such a generalized ‘quantum
        > potential’ would be solutions of a nonlinear Schr¨odinger equation whose form is typical
        > of superfluids. Then we suggest to achieve this quantum potential in a real experiment,
        - freak waves
          > These results may also be relevant to the
study of freak waves, which have already been described by nonlinear Schr¨odinger
equations.
  - "Gravity as a fluid dynamic phenomenon in a superfluid quantum space" (2016)
    https://hal.science/hal-01248015v5/preview/Fluid-Quantum-Gravity-And-Relativity_Fedi-v5_Sept2016.pdf
    - No gravitons
    - No dark energy
    - GR + Fluid Vortices
  - https://github.com/topics/lattice-boltzmann

## Additional context
- https://www.google.com/search?q=anosov+flows+superfluid+quantum+gravity

**Comment by Jacob-Stevens-Haas** [comment]
I'm sorry, this question is too general.  The **problem** section needs to be specific about something that SINDy doesn't do, as well as specifically what you'd like to see.  E.g. provide an example of equations for Anosov flow, some code of how you would hope to use pysindy with those equations, what mathematically counts as "inusfficient information", and what you'd like to see as output.

My own research isn't in this direction, so I'm unable to mentally create that kind of an example from the description you provided.

I'm likely to close this issue, as there doesn't seem to be anything other than quotes and links.  You need to put the work into summarizing the relevant information; it's unfair to expect us to do so.

**Comment by westurner** [comment]
I'm a bit miffed that you've suggested that you deserved a ScholarlyArticle
to teach you a better approach for the problems you're modeling with
PySindy and reluctant to spend more time on yours.

Are you aware of tools that model the same fluid problems as pysindy but
yield solutions  more algorithmically efficiently on classical computers?

FWIU, this new application of Anosov flows ~hashes stable patterns in
fluids?

**Comment by Jacob-Stevens-Haas** [comment]
There's a variety of competing methods, from [SINDy-adjacent-but-not-in-pysindy](https://arxiv.org/abs/2009.01006) to ones that take a different approach, such as [Gaussian Process Regression](https://arxiv.org/abs/2004.08376).  We're more focused on the problems of noisy data, choosing the function library, and choosing the measurement coordinates than on algorithmic efficiency.

**Comment by westurner** [comment]
From "Symbolic Regression"
https://en.wikipedia.org/wiki/Symbolic_regression :

> By not requiring a priori specification of a model, symbolic regression
isn't affected by human bias, or unknown gaps in domain knowledge. It
attempts to uncover the intrinsic relationships of the dataset, by letting
the patterns in the data itself reveal the appropriate models, rather than
imposing a model structure that is deemed mathematically tractable from a
human perspective. The fitness function that drives the evolution of the
models takes into account not only error metrics (to ensure the models
accurately predict the data), but also special complexity measures, [6]

Read:
https://en.wikipedia.org/wiki/Discovery_system_(AI_research)

- LLM prompt:
  - "you are a computational AI physicist explaining to a"
  - "let's think step by step"
  - "in SymPy, with pytest tests"
  - "in SymPy, with Hypothesis @given decorator tests"
  - "and then assert that"
  - "in a table with citations,"
  - "in JSON-LD"
  - "with lean mathlib"
    - https://github.com/leanprover-community/mathlib/issues/17919
  - Table of SOTA math LLMs:
https://github.com/nlpxucan/WizardLM/tree/main/WizardMath#comparing-wizardmath-with-the-llm-models

Anyways, Fitness functions for quantum chaotic fluid model prediction is
_out of scope and tangential_, too:
https://en.wikipedia.org/wiki/Fitness_function

-Anosov flows, degrees of curl, and fluid pattern emergence;
- are commonly emergent fluid flow patterns "hashable" after e.g. SiFT and
RiFT or at a lower level.
- The subset/superset relation between Anosov flows and Lorenz curves (in
fluids)
