### ISSUE TITLE
[BUG] importing pysindy adds "Ignore UserWarning" to the global warnings filter

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [dynamicslab/pysindy#414]
As title.  Should be a simple fix, but this is a placeholder to come back to it.

### Reproducing code example:

```python
import pysindy
import warnings
warnings.warn("Foo", UserWarning)
warnings.filters[0]
```

### Error message:

None, no warnings appear.  Filter is `('ignore', None, UserWarning, None, 0)`

### PySINDy/Python version information:

`master`

**Comment by maroun96** [comment]
Hello, 

This appears to be due to the following line in the sr3 module: ```warnings.filterwarnings("ignore", category=UserWarning)```.  Can I take the issue ?
