### ISSUE TITLE
[BUG] module 'pysindy' has no attribute 'SINDyPI'

### ISSUE THREAD

**Issue by Arincon94** [dynamicslab/pysindy#420]
Hi, we have found your work too interesting, but we are getting an error when the function ps.SINDyPI() is called.
We have tried to reproduce some basic codes from de SINDyPI documentation and we keep getting the same error.

### Reproducing code example:

sindy_library = ps.SINDyPILibrary(
    library_functions=x_library_functions,
    x_dot_library_functions=x_dot_library_functions,
    t=t,
    function_names=library_function_names,
    include_bias=True,
)

### Error message:

AttributeError: module 'pysindy' has no attribute 'SINDyPI'

### PySINDy/Python version information:

Python 3.10.9

**Comment by Jacob-Stevens-Haas** [comment]
Hey, you can find help on this by searching closed issues.  There's one with almost exactly the same title.  #366
