### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by anur2203** [dynamicslab/pysindy#421]
I can not understand why this is happening. In my old system it was working but in my new system I am facing this problem.
The error is only in line 27 but not in 21.

AttributeError                            Traceback (most recent call last)
Cell In[5], line 27
     11 library_function_names = [
     12     lambda x: x,
     13     lambda x, y: x + y,
   (...)
     17     lambda x, y: x + y + y,
     18     lambda x: x,]
     21 sindy_library = ps.SINDyPILibrary(library_functions = library_functions,
     22                                  x_dot_library_functions = x_dot_library,
     23                                  t = t_train,
     24                                  function_names = library_function_names)
---> 27 sindy_optimizer = ps.SINDyPI(
     28                              threshold = 0.01,
     29                              tol = 1e-5,
     30                              thresholder = "l1",
     31                              max_iter = 10000,
     32                              model_subset = [18])

AttributeError: **module 'pysindy' has no attribute 'SINDyPI'**

**Comment by Jacob-Stevens-Haas** [comment]
You need to pip install with the cvxpy optional requirements, a la
```
pip install pysindy[cvxpy]
```
If that fails, you can manually install
```
pip install cvxpy scs>=2.1, !=2.1.4
```

**Comment by anur2203** [comment]
Thanks. Issue resolved.
