### ISSUE TITLE
[BUG] sparse_ind argument in stlsq.py is not working

### ISSUE THREAD

**Issue by anur2203** [dynamicslab/pysindy#424]
TypeError                                 Traceback (most recent call last)
Cell In[4], line 13
     11 differentiation_method = ps.FiniteDifference(order=2)
     12 feature_library = ps.PolynomialLibrary(degree=2)
---> 13 optimizer = ps.STLSQ(threshold=stlsq_lambda, alpha=0.05, max_iter=20, ridge_kw=None, normalize_columns=False,
     14                                          copy_X=True, initial_guess=None, verbose=False, sparse_ind=None, unbias=True,)
     15 model = ps.SINDy(
     16     differentiation_method=differentiation_method,
     17     feature_library=feature_library,
     18     optimizer=optimizer,
     19     feature_names=["x", "y", "z"]
     20 )
     21 model.fit(x_train_multi, t=dt, multiple_trajectories=True)

TypeError: **STLSQ.__init__() got an unexpected keyword argument 'sparse_ind'**
Is this a error in code or I am doing something wrong?

**Comment by Jacob-Stevens-Haas** [comment]
`sparse_ind` is very new and only in the `master` branch - it hasn't been released yet (hopefully by the end of the year!).  It exists in order to to use a sparse optimizer when fitting the derivatives and the function library **at the same time.** This capability is only provided by the `SSSINDy` class (Single-step SINDy), which is in the `sss` branch and not even merged yet.

Were you installing `pysindy` from PyPI or directly from Github?

**Comment by anur2203** [comment]
I have installed from PyPI

**Comment by anur2203** [comment]
I am working with 3 state variable's and I want to discover each equation separately using different regularization constant.

**Comment by Jacob-Stevens-Haas** [comment]
Try using SR3, which allows separate thresholds not just for each equation, but for each term in each equation.
```
    thresholds : np.ndarray, shape (n_targets, n_features), optional \
            (default None)
        Array of thresholds for each library function coefficient.
        Each row corresponds to a measurement variable and each column
        to a function from the feature library.
        Recall that SINDy seeks a matrix :math:`\\Xi` such that
        :math:`\\dot{X} \\approx \\Theta(X)\\Xi`.
        ``thresholds[i, j]`` should specify the threshold to be used for the
        (j + 1, i + 1) entry of :math:`\\Xi`. That is to say it should give the
        threshold to be used for the (j + 1)st library function in the equation
        for the (i + 1)st measurement variable.
```
