### ISSUE TITLE
[BUG]Cannot use TrappingSR3

### ISSUE THREAD

**Issue by SimonYYS** [dynamicslab/pysindy#432]
TrappingSR3 is not working, even in the example you provided '8_trapping_sindy_paper_examples':
https://pysindy.readthedocs.io/en/latest/examples/8_trapping_sindy_paper_examples/example.html

Other optimizers I tried works fine..

### Error message:
AttributeError: module 'pysindy' has no attribute 'TrappingSR3'

Python 3.11.5

**Comment by Jacob-Stevens-Haas** [comment]
Please share pysindy version.  Also, based on relevant info, what are your `cvxpy`, `osqp`, and `scs` versions?

**Comment by SimonYYS** [comment]
Thanks for the reply.

pysindy     ver 1.7.5
osqp         ver 0.6.3
cvxpy        ver 1.4.1
scs            ver 3.2.4.post1

**Comment by SimonYYS** [comment]
> Please share pysindy version. Also, based on relevant info, what are your `cvxpy`, `osqp`, and `scs` versions?

Thanks for the reply.

pysindy ver 1.7.5
osqp ver 0.6.3
cvxpy ver 1.4.1
scs ver 3.2.4.post1

**Comment by Jacob-Stevens-Haas** [comment]
Thanks.  Let's get a bit more diagnostic error.  Can you try to directly import the trapping_sr3.py module?
```python
import pysindy.optimizers.trapping_sr3
```

**Comment by SimonYYS** [comment]
> Thanks. Let's get a bit more diagnostic error. Can you try to directly import the trapping_sr3.py module?
> 
> ```python
> import pysindy.optimizers.trapping_sr3
> ```

Now it works magically. That's cool.

**Comment by Jacob-Stevens-Haas** [comment]
Glad to hear. For context `pysindy` skips importing `TrappingSR3` from pysindy/optimizers/trapping_sr3.py if the latter runs into an error importing CVXPY.  So it looks like something about your CVXPY install was updated or fixed between your first error and the last attempt.
