### ISSUE TITLE
[BUG] Multiple trajectories raises a ValueError 

### ISSUE THREAD

**Issue by bentaps** [dynamicslab/pysindy#484]
When the training data input to `ps.SINDy()` is a Sequence of multiple trajectories as outlined in the documentation a ValueError is raised. The error can be reproduced by running the example found in [1_feature_overview/example.ipynb](https://github.com/dynamicslab/pysindy/tree/master/examples/1_feature_overview/example.ipynb). Specifically the following code can reproduce the error: 

### Reproducing code example:

```python
if __name__ != "testing":
    n_trajectories = 20
    sample_range = (500, 1500)
else:
    n_trajectories = 2
    sample_range = (10, 15)
x0s = np.array([36, 48, 41]) * (np.random.rand(n_trajectories, 3) - 0.5) + np.array(
    [0, 0, 25]
)
x_train_multi = []
for i in range(n_trajectories):
    x_train_multi.append(
        solve_ivp(
            lorenz, t_train_span, x0s[i], t_eval=t_train, **integrator_keywords
        ).y.T
    )

model = ps.SINDy()
model.fit(x_train_multi, t=dt)
model.print()
```

### Error message:

ValueError: x is a Sequence, but multiple_trajectories not set.  Did you mean to set multiple trajectories?

### PySINDy/Python version information:

1.7.5 3.9.6 (default, Oct 18 2022, 12:41:40) 
[Clang 14.0.0 (clang-1400.0.29.202)]

**Comment by Jacob-Stevens-Haas** [comment]
This is simply because you're on the `master` branch of the example notebook, but using a stable release of pysindy.  Check out the stable example of the notebook: https://pysindy.readthedocs.io/en/stable/examples/1_feature_overview/example.html

**Comment by bentaps** [comment]
Ah gotcha! Thanks for the quick reply, Jacob :) got it working now!
