### ISSUE TITLE
[BUG] cannot import name 'enzyme'

### ISSUE THREAD

**Issue by heidong** [dynamicslab/pysindy#486]
### Reproducing code example:

```python
import pysindy
<< your code here >>import pysindy as ps
from pysindy.utils import enzyme
from pysindy.utils import lorenz
from pysindy.utils import lorenz_control

```

### Error message:
ImportError                               Traceback (most recent call last)
<ipython-input-7-e39e101096bb> in <module>
     12 
     13 import pysindy as ps
---> 14 from pysindy.utils import enzyme
     15 from pysindy.utils import lorenz
     16 from pysindy.utils import lorenz_control

ImportError: cannot import name 'enzyme'

I get an error when I run this example
the  example is :
pysindy-master/examples/1_feature_overview/example.ipynb

### PySINDy/Python version information:
pysindy                            1.3.0
python                             3.6.7 |Anaconda

**Comment by Jacob-Stevens-Haas** [comment]
Upgrade your pysindy version; `enzyme` appears in 1.5.0
