### ISSUE TITLE
Bayesian Sindy

### ISSUE THREAD

**Issue by ashok1996annu** [dynamicslab/pysindy#496]
I want to implement Bayesian Sindy to my problem. But I got the following error " pysindy.optimizers has no attribute SBR".
I have tried so many times but failed.
Can anyone tell the solution for this?

**Comment by Jacob-Stevens-Haas** [comment]
When you install pysindy, you (a) need to install from master  branch - there's no PYPI release right now that has Bayesian SINDy, and (b) need the sbr optional dependencies.:
```
pip install pysindy[sbr] @ git+https://github.com/dynamicslab/pysindy
```

**Comment by ashok1996annu** [comment]
thanks for the help
