### ISSUE TITLE
[BUG] import fails due to ModuleNotFoundError in sklearn.preprocessing

### ISSUE THREAD

**Issue by jasnyder** [dynamicslab/pysindy#51]
Import of `sklearn.preprocessing._csr_polynomial_expansion` fails.

### Reproducing code example:

```python
import pysindy
```

### Error message:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-640311a760f6> in <module>
----> 1 import pysindy

c:\users\jordan\appdata\local\programs\python\python37\lib\site-packages\pysindy\__init__.py in <module>
     11 from pysindy.differentiation import *
     12 from pysindy.optimizers import *
---> 13 from pysindy.feature_library import *
     14 from pysindy.utils import *

c:\users\jordan\appdata\local\programs\python\python37\lib\site-packages\pysindy\feature_library\__init__.py in <module>
      2 from .fourier_library import FourierLibrary
      3 from .identity_library import IdentityLibrary
----> 4 from .polynomial_library import PolynomialLibrary

c:\users\jordan\appdata\local\programs\python\python37\lib\site-packages\pysindy\feature_library\polynomial_library.py in <module>
      6 from scipy import sparse
      7 from sklearn.preprocessing import PolynomialFeatures
----> 8 from sklearn.preprocessing._csr_polynomial_expansion import _csr_polynomial_expansion
      9 from sklearn.utils import check_array
     10 from sklearn.utils.validation import check_is_fitted

ModuleNotFoundError: No module named 'sklearn.preprocessing._csr_polynomial_expansion'
```
### Version info:
`import sys, sklearn; print(sklearn.__version__, sys.version)` returns `0.20.3 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]`

**Comment by briandesilva** [comment]
Thanks for bringing this to our attention. I suspect it has something to do with the fact that the file we're importing from, `_csr_polynomial_expansion.pyx` is compiled (cf. [this thead](https://github.com/scikit-learn/scikit-learn/issues/13202)).

@kpchamp , didn't you run into an issue like this at some point? Do you remember how you resolved it?

**Comment by kpchamp** [comment]
This looks like a versioning issue. Looks like Jordan has sklearn 0.20.3, but the `_csr_polynomial_expansion.pyx` wasn't added until 0.21. Our current requirements only lists sklearn 0.19 or higher. Should we just update to requiring 0.21 or higher?

**Comment by briandesilva** [comment]
Yes, I'll update the requirements. @jasnyder , let us know if updating your version of sklearn solves the problem for you.

**Comment by jasnyder** [comment]
Yes, it works now! Thanks guys!
