### ISSUE TITLE
 SINDy-PI/ one state derivative per model

### ISSUE THREAD

**Issue by yasheel222** [dynamicslab/pysindy#519]
I am trying to recover equations of three state system, using weak PDE library to implement SINDy-PI. Is there a way to add contraints to the library functions so that I can force only one temporal derivative in a every proposed model at a time.

**Comment by Jacob-Stevens-Haas** [comment]
There's an `implicit_terms` argument to `WeakPDELibrary` and `PDELibrary` that will do what I think you want

**Comment by yasheel222** [comment]
I will be a bit more descriptive.
Say input state vector has three components (x,s,p)
Now from what I understand implicit_terms argument will generate custom library with derivative terms for each component i.e. x_t, s_t, p_t.
What I mean to ask is that can I somehow further constraint it so that say I can choose only x_t to be in library?

**Comment by Jacob-Stevens-Haas** [comment]
I don't think you can do that.
