### ISSUE TITLE
Can not import pysindy after installation

### ISSUE THREAD

**Issue by xinchen236** [dynamicslab/pysindy#529]
I installed pysindy from a local copy, and it shows a successful installation. But when I tried to import the package on Python, an error came out as "**NameError: name 'cp' is not defined**". The details are attached below. Can anyone help me with this issue? Many thanks!
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[5], [line 1](vscode-notebook-cell:?execution_count=5&line=1)
----> [1](vscode-notebook-cell:?execution_count=5&line=1) import pysindy as ps
   cost = cp.sum_squares(x_expanded @ xi - y.flatten())

NameError: name 'cp' is not defined

**Comment by xinchen236** [comment]
Problem solved. Need to install "cvxpy" first.

**Comment by Jacob-Stevens-Haas** [comment]
No, this is an issue.  cvxpy is an optional dependency, and it shouldn't block importing `pysindy`.  (It should block using ConstrainedSR3, however).

the file likely needs a `from __future__ import annotations` line at the top

**Comment by talitta-nunes** [comment]
I had a similar problem, but it's causing the error below. I like to test using Google Colab, I never had any trouble until today! I tried to remove the derivative package, install the correct version of the importlib_metadata and run again, but unsuccessful. So I had to use the virtual environment to deal with and make it work
```---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
<ipython-input-24-a39643098e1c> in <cell line: 1>()
----> 1 import pysindy as ps
      2 import numpy as np
      3 import pandas as pd
      4 import math
      5 import matplotlib.pyplot as plt

5 frames
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py in _resolve_dist(self, req, best, replace_conflicting, env, installer, required_by, to_activate)
    871             # Oops, the "best" so far conflicts with a dependency
    872             dependent_req = required_by[req]
--> 873             raise VersionConflict(dist, req).with_context(dependent_req)
    874         return dist
    875 

ContextualVersionConflict: (importlib-metadata 8.0.0 (/usr/local/lib/python3.10/dist-packages), Requirement.parse('importlib-metadata<8.0.0,>=7.1.0'), {'derivative'})```

**Comment by azhartman79** [comment]
> I had a similar problem, but it's causing the error below. I like to test using Google Colab, I never had any trouble until today! I tried to remove the derivative package, install the correct version of the importlib_metadata and run again, but unsuccessful. So I had to use the virtual environment to deal with and make it work
> 
> ```
> ContextualVersionConflict                 Traceback (most recent call last)
> <ipython-input-24-a39643098e1c> in <cell line: 1>()
> ----> 1 import pysindy as ps
>       2 import numpy as np
>       3 import pandas as pd
>       4 import math
>       5 import matplotlib.pyplot as plt
> 
> 5 frames
> /usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py in _resolve_dist(self, req, best, replace_conflicting, env, installer, required_by, to_activate)
>     871             # Oops, the "best" so far conflicts with a dependency
>     872             dependent_req = required_by[req]
> --> 873             raise VersionConflict(dist, req).with_context(dependent_req)
>     874         return dist
>     875 
> 
> ContextualVersionConflict: (importlib-metadata 8.0.0 (/usr/local/lib/python3.10/dist-packages), Requirement.parse('importlib-metadata<8.0.0,>=7.1.0'), {'derivative'})```
> ```

The same thing happened to me.  I like run in colab first and after I install pysindy I get this:

ContextualVersionConflict                 Traceback (most recent call last)
[<ipython-input-6-a99f36019750>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import pysindy as ps

5 frames
[/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _resolve_dist(self, req, best, replace_conflicting, env, installer, required_by, to_activate)
    871             # Oops, the "best" so far conflicts with a dependency
    872             dependent_req = required_by[req]
--> 873             raise VersionConflict(dist, req).with_context(dependent_req)
    874         return dist
    875 

ContextualVersionConflict: (importlib-metadata 8.0.0 (/usr/local/lib/python3.10/dist-packages), Requirement.parse('importlib-metadata<8.0.0,>=7.1.0'), {'derivative'})


Haven't tried using virtual environment yet to work around, though.

**Comment by Jacob-Stevens-Haas** [comment]
For those with the `importlib-metadata` conflict, that's being generated by `derivative` - a dependency of python, but it's own package.  I would suggest positing the issue there.

**Comment by lunassneu** [comment]
The same thing happened to me. I installed Sindy directly from the git repository, I use Windows, Anaconda.
the installation was successful, but when I import sindy this error message appears about cp:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 import pysindy as ps

File D:\Program Files\anaconda3\Lib\site-packages\pysindy\__init__.py:11
      9 from . import differentiation
     10 from . import feature_library
---> 11 from . import optimizers
     12 from . import deeptime
     13 from . import utils

File D:\Program Files\anaconda3\Lib\site-packages\pysindy\optimizers\__init__.py:3
      1 from .base import BaseOptimizer
      2 from .base import EnsembleOptimizer
----> 3 from .constrained_sr3 import ConstrainedSR3
      4 from .frols import FROLS
      6 try:  # Waiting on PEP 690 to lazy import gurobipy

File D:\Program Files\anaconda3\Lib\site-packages\pysindy\optimizers\constrained_sr3.py:22
     18 from ..utils import reorder_constraints
     19 from .sr3 import SR3
---> 22 class ConstrainedSR3(SR3):
     23     """
     24     Sparse relaxed regularized regression with linear (in)equality constraints.
     25 
   (...)
    152         may increase and decrease as the algorithm works.
    153     """
    155     def __init__(
    156         self,
    157         threshold=0.1,
   (...)
    176         unbias=False,
    177     ):

File D:\Program Files\anaconda3\Lib\site-packages\pysindy\optimizers\constrained_sr3.py:276, in ConstrainedSR3()
    271     rhs = rhs.reshape(g.shape)
    272     return inv1.dot(rhs)
    274 def _create_var_and_part_cost(
    275     self, var_len: int, x_expanded: np.ndarray, y: np.ndarray
--> 276 ) -> Tuple[cp.Variable, cp.Expression]:
    277     xi = cp.Variable(var_len)
    278     cost = cp.sum_squares(x_expanded @ xi - y.flatten())

NameError: name 'cp' is not defined

I didn't understand what Jacob said about from __future__ import annotations
Where do I have to add this line of code?

**Comment by lunassneu** [comment]
> No, this is an issue. cvxpy is an optional dependency, and it shouldn't block importing `pysindy`. (It should block using ConstrainedSR3, however).
> 
> the file likely needs a `from __future__ import annotations` line at the top.
> 
> What's your pysindy version?

Can you help me please? I explained the problem above
