### ISSUE TITLE
Published paper additions to the examples directory

### ISSUE THREAD

**Issue by akaptano** [dynamicslab/pysindy#53]
Hey y'all, this is Alan from Steve's group. I am working on SINDy models in the field of plasma physics and have been using pySINDy. I am interested in contributing to the examples/ directory of the pySINDy with a jupyter notebook + all my other files unrelated to SINDy (4-5 python files for plasma-specific things which are compatible with the current pySINDy python requirements) which would reproduce the paper I am hoping to publish soon. This could be a cool thing for others to join as well, as we could accumulate a large bin of examples from disparate fields that reproduce published works. 

One minor caveat is that my analysis relies on some potentially large files to read in. However, I know that github has several ways to link to dropbox or other large extraneous files so this is probably a surmountable problem. 

Anyways, if you are interested in this idea as well, maybe we should meet soon to discuss a bit how we should formalize going about this process. I'm also happy to get more involved generally with the maintenance and oversight of this awesome github repo.

Cheers,
Alan

**Comment by briandesilva** [comment]
Hey Alan, we're definitely interested in incorporating your work into the PySINDy examples! I think it would be a good idea for us to talk in person about how to accomplish this as seamlessly as possible. One consideration is that we're planning on consolidating our examples in a Sphinx gallery (#46 ). I'll touch base with @kpchamp and shoot you an email to arrange a meeting.

**Comment by Ohjeah** [comment]
Hey, I would like to mention that examples in this repository would need be updated along the main pysindy source, i.e. if the pysindy api changes, examples may break.
Therefore I'd recommend setting up another repository for more complex examples, like reproducing published results, and pinning the pysindy version for each example.

We could still render these complex examples with sphinx gallery or link them to binder.

**Comment by briandesilva** [comment]
That solution makes sense to me. Do you know of any examples we can look at to get an idea of how to set this up?

**Comment by briandesilva** [comment]
@Ohjeah, are you aware of any other software packages that do something like you suggested?

**Comment by Ohjeah** [comment]
No sorry. I think we would need to script something like this ourself.
Maybe we can use the Github Actions and simply render notebooks as a start.

**Comment by Ohjeah** [comment]
I think it can be done with this feature: https://sphinx-nbexamples.readthedocs.io/en/latest/linkgalleries.html

**Comment by briandesilva** [comment]
Update: @akaptano is working to add linear equality constraints and a few other features to the `STLSQ` and `SR3` classes, making it possible for us to host the examples ourselves (as Jupyter notebooks in the examples directory). The primary obstacle here is that the experiments require some large data files (on the order of 10's of GB). One way around this would be for us to run the notebook locally, push it to GitHub, then have sphinx use it directly. @Ohjeah, am I right in assuming that because we set `dont_preprocess=True` in the configuration for our example gallery that the notebooks are being converted and rendered by sphinx without being re-run?

**Comment by Ohjeah** [comment]
That's correct. 

https://sphinx-nbexamples.readthedocs.io/en/latest/api/sphinx_nbexamples.html#sphinx_nbexamples.Gallery

**Comment by briandesilva** [comment]
Implemented in #78.
