### ISSUE TITLE
[BUG] SmoothedFiniteDifference does not have 'save_smooth'

### ISSUE THREAD

**Issue by sangnguyens** [dynamicslab/pysindy#530]
### Reproducing code example:

```python
import pysindy as ps

smooth_diff = ps.SmoothedFiniteDifference(save_smooth=False)

```

### Error message:

`FiniteDifference.__init__()`does not have save_smooth method.

I install pysindy version 1.7.5 from pypi. I have to manually update code from source, same for `SINDyDerivative`

**Comment by Jacob-Stevens-Haas** [comment]
That feature isn't in 1.7.5.  It's available in the master branch, which will soon be released as 2.0.0
