### ISSUE TITLE
[BUG] bad shape of model.coefficients() when using Lasso sklearn optimizer

### ISSUE THREAD

**Issue by xEmmaV99** [dynamicslab/pysindy#535]
I want to use the Lasso optimizer from sklearn.linear_model and I only require one output value for my problem.
I can create and fit the model, but I get an error on functions like model.print() and model.predict(). This does not occur when using built-in optimizers. I suppose the issue is that model.coefficients().shape gives (n, ) instead of (n,1). Reshaping and overwriting model.optimizer.coef_ resolves the issue. 

### Reproducing code example:

```python
import pysindy as ps
import numpy as np
from sklearn.linear_model import Lasso

# random data
x_train = np.array([0,1,1,0])
u_train = np.array([1,0,0,1])
xdot_train = np.array([1,1,1,1])

optimizer = Lasso(alpha=0.01, fit_intercept=False)

library = ps.PolynomialLibrary(degree=2, include_interaction=True)

model = ps.SINDy(optimizer=optimizer, feature_library=library)

model.fit(x_train, u=u_train, t=None, x_dot=xdot_train)
print(model.coefficients().shape)
model.print()
```

### Error message:

Traceback (most recent call last):
  File "C:\*\example_code\bug", line 17, in <module>
    model.print()
  File "C:\*\anaconda3\envs\env\Lib\site-packages\pysindy\pysindy.py", line 366, in print
    eqns = self.equations(precision)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\*\anaconda3\envs\env\Lib\site-packages\pysindy\pysindy.py", line 348, in equations
    return equations(
           ^^^^^^^^^^
  File "C:\*\anaconda3\envs\env\Lib\site-packages\pysindy\utils\base.py", line 319, in equations
    print_model(
  File "C:\*\anaconda3\envs\env\Lib\site-packages\pysindy\utils\base.py", line 296, in print_model
    components = [term(c, e, i) for c, e, i in zip(coef, errors, input_features)]
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object is not iterable
PS C:\*\PycharmProjects\SINDY_project> 

### PySINDy/Python version information:

1.7.6.dev346+g3503c15 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]

**Comment by Jacob-Stevens-Haas** [comment]
Use `ps.WrappedOptimizer`.  It takes a single argument, `optimizer`, which is any scikit-learn optimizer.  It also accepts arguments that other pysindy optimizers accept, e.g. `unbias`.

If using any model that has a `fit_intercept` argument, you must set it to `False`.
