### ISSUE TITLE
[BUG] 'PolynomialLibrary' object has no attribute 'calc_trajectory'

### ISSUE THREAD

**Issue by ghhmq** [dynamicslab/pysindy#539]
I am studying pysindy these days and I am trying the example code listed. But I encountered some problems that as I was trying to run the example code of noise_robustness, the outcome is 'PolynomialLibrary' object has no attribute 'calc_trajectory' .
I use anaconda to install pysindy, and I use jupyter notebook to run the example code.

### Reproducing code example:

```python
algorithm = "STLSQ"

# if using the weak form, this makes the Pareto curve based on the "strong" or regular RMSE error
# instead of the RMSE error of the weak formulation.
strong_rmse = True

t1 = time.time()

# Note, defaults to using the AIC to decide the Pareto-optimal model
n_models = 10
(xdot_rmse_errors, xdot_coef_errors, AIC, x_dot_tests, x_dot_test_preds,
predicted_coefficients, best_threshold_values, models, condition_numbers) = Pareto_scan_ensembling(
    systems_list, dimension_list, true_coefficients, 
    all_sols_train, all_t_train, all_sols_test, all_t_test, 
    normalize_columns=False,  # whether to normalize the SINDy matrix
    noise_level=noise_level,  # amount of noise to add to the training data
    n_models=n_models,  # number of models to train using EnsemblingOptimizer functionality
    n_subset=int(0.5 * len(all_t_train['HyperBao'][0])),  # subsample 50% of the training data for each model
    replace=False,  # Do the subsampling without replacement
    weak_form=weak_form,  # use the weak form or not
    algorithm=algorithm, # optimization algorithm
    strong_rmse=strong_rmse, # use the strong rmse with the weak form or not
)
            
t2 = time.time()
print('Total time to compute = ', t2 - t1, ' seconds')
# print('Condition numbers = ', condition_numbers)
```

### Error message:

AttributeError                            Traceback (most recent call last)
Cell In[8], line 12
      9 # Note, defaults to using the AIC to decide the Pareto-optimal model
     10 n_models = 10
     11 (xdot_rmse_errors, xdot_coef_errors, AIC, x_dot_tests, x_dot_test_preds,
---> 12 predicted_coefficients, best_threshold_values, models, condition_numbers) = Pareto_scan_ensembling(
     13     systems_list, dimension_list, true_coefficients, 
     14     all_sols_train, all_t_train, all_sols_test, all_t_test, 
     15     normalize_columns=False,  # whether to normalize the SINDy matrix
     16     noise_level=noise_level,  # amount of noise to add to the training data
     17     n_models=n_models,  # number of models to train using EnsemblingOptimizer functionality
     18     n_subset=int(0.5 * len(all_t_train['HyperBao'][0])),  # subsample 50% of the training data for each model
     19     replace=False,  # Do the subsampling without replacement
     20     weak_form=weak_form,  # use the weak form or not
     21     algorithm=algorithm, # optimization algorithm
     22     strong_rmse=strong_rmse, # use the strong rmse with the weak form or not
     23 )
     25 t2 = time.time()
     26 print('Total time to compute = ', t2 - t1, ' seconds')

File ~\SURF\noise_robustness\utils.py:568, in Pareto_scan_ensembling(systems_list, dimension_list, true_coefficients, all_sols_train, all_t_train, all_sols_test, all_t_test, normalize_columns, noise_level, tol_iter, n_models, n_subset, replace, weak_form, algorithm, strong_rmse, K)
    558     poly_library = ps.WeakPDELibrary(
    559         library_functions=library_functions,
    560         function_names=library_function_names,
   (...)
    564         K=K,
    565     )
    567 # pre-calculate the test trajectory derivatives and library matrices
--> 568 x_dot_test = [
    569     poly_library.calc_trajectory(
    570         ps.FiniteDifference(axis=-2),
    571         ps.AxesArray(x_test_list[i], axes={"ax_time": 0, "ax_coord": 1}),
    572         t_test_list[i],
    573     )
    574     for i in range(len(x_test_list))
    575 ]
    576 mats = poly_library.fit_transform(
    577     [ps.AxesArray(xt, axes={"ax_time": 0, "ax_coord": 1}) for xt in x_test_list]
    578 )
    579 order = np.arange(mats[0].shape[-1])

File ~\SURF\noise_robustness\utils.py:569, in <listcomp>(.0)
    558     poly_library = ps.WeakPDELibrary(
    559         library_functions=library_functions,
    560         function_names=library_function_names,
   (...)
    564         K=K,
    565     )
    567 # pre-calculate the test trajectory derivatives and library matrices
    568 x_dot_test = [
--> 569     poly_library.calc_trajectory(
    570         ps.FiniteDifference(axis=-2),
    571         ps.AxesArray(x_test_list[i], axes={"ax_time": 0, "ax_coord": 1}),
    572         t_test_list[i],
    573     )
    574     for i in range(len(x_test_list))
    575 ]
    576 mats = poly_library.fit_transform(
    577     [ps.AxesArray(xt, axes={"ax_time": 0, "ax_coord": 1}) for xt in x_test_list]
    578 )
    579 order = np.arange(mats[0].shape[-1])

AttributeError: 'PolynomialLibrary' object has no attribute 'calc_trajectory'

### PySINDy/Python version information:

pysindy.1.6.3, sys.3.8.19

**Comment by Jacob-Stevens-Haas** [comment]
Can you provide a more minimal working example?  Also, where is the funciton `Pareto_scan_ensembling()` from?

**Comment by Jacob-Stevens-Haas** [comment]
Closing due to lack of response.
