### ISSUE TITLE
[BUG] Import Error involving Metadata

### ISSUE THREAD

**Issue by virati** [dynamicslab/pysindy#547]
Import of pysindy in a Google Colab Notebook (pro) does not work - yields a "ContextualVersionConflict" error.

### Reproducing code example:

```python
!pip install pysindy
import pysindy as sindy

```

### Error message:
---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
[<ipython-input-1-1b18e50fa92f>](https://localhost:8080/#) in <cell line: 2>()
      1 get_ipython().system('pip install pysindy')
----> 2 import pysindy as sindy

5 frames
[/usr/local/lib/python3.10/dist-packages/pysindy/__init__.py](https://localhost:8080/#) in <module>
      3 
      4 try:
----> 5     __version__ = get_distribution(__name__).version
      6 except DistributionNotFound:
      7     pass

[/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in get_distribution(dist)
    544         dist = Requirement.parse(dist)
    545     if isinstance(dist, Requirement):
--> 546         dist = get_provider(dist)
    547     if not isinstance(dist, Distribution):
    548         raise TypeError("Expected str, Requirement, or Distribution", dist)

[/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in get_provider(moduleOrReq)
    427     """Return an IResourceProvider for the named module or requirement"""
    428     if isinstance(moduleOrReq, Requirement):
--> 429         return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    430     try:
    431         module = sys.modules[moduleOrReq]

[/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in require(self, *requirements)
   1064         included, even if they were already activated in this working set.
   1065         """
-> 1066         needed = self.resolve(parse_requirements(requirements))
   1067 
   1068         for dist in needed:

[/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in resolve(self, requirements, env, installer, replace_conflicting, extras)
    891                 continue
    892 
--> 893             dist = self._resolve_dist(
    894                 req, best, replace_conflicting, env, installer, required_by, to_activate
    895             )

[/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _resolve_dist(self, req, best, replace_conflicting, env, installer, required_by, to_activate)
    937             # Oops, the "best" so far conflicts with a dependency
    938             dependent_req = required_by[req]
--> 939             raise VersionConflict(dist, req).with_context(dependent_req)
    940         return dist
    941 

ContextualVersionConflict: (importlib-metadata 8.2.0 (/usr/local/lib/python3.10/dist-packages), Requirement.parse('importlib-metadata<8.0.0,>=7.1.0'), {'derivative'})

### PySINDy/Python version information:

pysindy-1.7.5-py3

**Comment by Jacob-Stevens-Haas** [comment]
See the linked PR in derivative
