### ISSUE TITLE
Extraneous code in top-level directory

### ISSUE THREAD

**Issue by briandesilva** [dynamicslab/pysindy#6]
There are a few files sitting around in the top level directory from when I first forked the project and I'm not sure whether we still need them. Specifically, the files I'm unsure about are
- .gitmodules
- .codecov.yml
- .gitattributes
- .readthedocs.yml
- .travis.yml

**Comment by Ohjeah** [comment]
We can definitely get rid of the `.gitmodules`, `.travis.yml` and `.codecov.yml`.
I don't know about versioning the project yet. The original repo used versioneer to automatically infer the python package version from git tags (the `.gitattributes` is used for this).
Also, do we want rendered documentation on readthedocs.org?

**Comment by briandesilva** [comment]
Great. I'll remove `.gitmodules`, `.travis.yml`, and `.codecov.yml`. We can hold off on modifying `.gitattributes` until we decide how to handle versioning.

Now that I look at it we may be able to prune some lines from `requirements.txt` and `requirements-dev.txt`.
 - `requirements.txt`: Can we drop the dependence on `matplotlib` if the only place we use it is in our example jupyter notebooks?
- `requirements-dev.txt`: There are a number of requirements I suspect we can drop. Could you take a look and see if that's the case and, if so, which lines can be safely removed?

I think we will want to host documentation on readthedocs.org. You have some experience with sphinx, right? Do you have an estimate for how much effort would be required to port our documentation over to readthedocs.org?

**Comment by Ohjeah** [comment]
I think it's a matter of a few hours to get it running, but will take a lot of effort to have a nice presentable version.
It's a great way presenting the examples though and we should definitely habe the online documentation on the roadmap.

**Comment by briandesilva** [comment]
Okay, we'll add it to our to-do list.

**Comment by Ohjeah** [comment]
@briandesilva I noticed you added support for travis again. Unit tests are now checked twice using Github actions and travis. I think staying with Github actions is fine.

**Comment by briandesilva** [comment]
I added Travis support again so that we could include a badge indicating to users whether our latest changes pass the unit tests. I will look into accomplishing a similar outcome with GitHub actions.

**Comment by Ohjeah** [comment]
I spilt up the remaining tasks in separate issues: #14 #15 #16
