### ISSUE TITLE
[BUG]AttributeError: module 'pytest' has no attribute 'lazy_fixture'

### ISSUE THREAD

**Issue by billtubbs** [dynamicslab/pysindy#67]
What version of pytest are you using?  I get the following error trying to run the tests.

```unix
$ pytest
============================ test session starts =============================
platform darwin -- Python 3.7.7, pytest-3.10.1, py-1.8.1, pluggy-0.13.1
rootdir: /Users/billtubbs/pysindy, inifile:
collected 24 items / 4 errors                                                

=================================== ERRORS ===================================
___________________ ERROR collecting test/test_pysindy.py ____________________
test/test_pysindy.py:88: in <module>
    pytest.lazy_fixture("data_1d"),
E   AttributeError: module 'pytest' has no attribute 'lazy_fixture'
```

I tried going back as far as version 3.10.1 and can't get it working in any version (latest version on conda is 5.4.1).
Thanks.

I think it's related to [this open issue](https://github.com/TvoroG/pytest-lazy-fixture/issues/24) with pytest.

**Comment by briandesilva** [comment]
If you don't have [pytest-lazy-feature](https://pypi.org/project/pytest-lazy-fixture/) installed, that could be the issue. It's listed in `requirements-dev.txt` but not `requirements.txt` since it's only needed for unit testing.

**Comment by billtubbs** [comment]
Thanks, that worked.  I should have looked at your requirements file.
