### ISSUE TITLE
Cross-validation with SINDy

### ISSUE THREAD

**Issue by briandesilva** [dynamicslab/pysindy#7]
At the moment it is not straightforward to perform cross-validation on different parameters passed into the SINDy constructor. Most of the parameters relevant to a SINDy model's performance are passed into the objects expected by the optimizer, feature_library, and differentiation_method arguments rather than being fed directly into the SINDy constructor.

Ideally users would be able to run cross-validation in a manner similar to the following example, but it is currently not possible to do so (since `threshold` is a parameter of the SINDy.optimizer class object).
```
model = SINDy()
params = {"threshold" : [0.01, 0.1, 0.5, 1]}
cv = KFold(n_splits=3)
grid_search = GridSearchCV(model, params, cv=cv)
grid_search.fit(x_train)
```
Our original motivation for encompassing most of the arguments in the optimizer, differentiation_method, and feature_library was to avoid creating a base object with dozens of optional arguments. 

Is there a relatively clean way for us to perform cross-validation with our current setup? I have a few ideas about how to do so, but they feel hacky:
- Use the sklearn.pipeline strategy of appending argument names to the keys in params. These names help identify which objects the corresponding parameters are meant to be passed into.
- Create some kind of wrapper object or helper function to aid the user in performing cross validation.

**Comment by Ohjeah** [comment]
You can use the sklearn gridsearch on nested or composed estimators as well: https://scikit-learn.org/stable/modules/grid_search.html#composite-estimators-and-parameter-spaces

We need to make sure though, that all nested objects inherit properly from the [`BaseEstimator`](https://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html) class, as this implements the two methods (`set_params` and `get_params`) needed.

**Comment by rspadim** [comment]
Should be interesting an example at documentation

**Comment by briandesilva** [comment]
I was looking into this again and your suggestion, @Ohjeah, now works smoothly (since we have refactored the optimizer code). 

However there's another problem: the SINDy `fit` and `score` methods take an optional parameter t which isn't standard for scikit-learn. When a uniform time step other than 1 is used, the cross validation object doesn't have a way to pass it into both the `fit` and `score` methods. You can pass in a fixed time step to `SINDy.fit` via the `**fit_params` argument of the cross validation object, but not the `score` function.

One option is to not try to feed t in and assume a uniform time step of 1. If you then divide the coefficients of the resulting model by the true time step you'll arrive at the correct equation, but you'll also have to shrink the thresholds by the same factor.

Another option could be to add a parameter to the `SINDy` constructor allowing you to specify a fixed uniform time step that would be used as a default if other values are not passed in. I think this might be the cleanest solution. I'll play around with it and see how it looks.

Nonuniform time steps or control variables are another story. I haven't thought much about how to incorporate them into this framework.

**Comment by Ohjeah** [comment]
Closed with #84

**Comment by Ohjeah** [comment]
@briandesilva I overlooked your last comment and assumed this issues was closed with the corresponding PR.

Should we re-open, or open a separate issue to discuss parameters for the derivative?

Btw: you can also use a custom scorer in gridsearches/crossvalidation.

**Comment by briandesilva** [comment]
I don't think we need to re-open the issue. I'm satisfied with our current cross-validation capabilities.
