### ISSUE TITLE
Complexity property test

### ISSUE THREAD

**Issue by Ohjeah** [dynamicslab/pysindy#74]
Sorry, I didn't see your comment before making the most recent commit. I relaxed the complexity test constraint a bit more.

I was able to reproduce the failed test locally by using the same parameters: `n_samples=1124`, `n_features=27`, `n_informative=5`, `random_state=6`. It looks like LASSO somehow finds 4 informative features, while the other heavily regularized models find 6. This seems like a bit of a fluke; for different random states this doesn't occur.

Maybe we could remove LASSO from this test? Or we could stick with the quick fix I made.

In any case, the bug isn't caused by this PR, so I think it's okay to accept it.

_Originally posted by @briandesilva in https://github.com/dynamicslab/pysindy/pull/71#issuecomment-622479207_

**Comment by Ohjeah** [comment]
Let's discuss it in a new issue.

Maybe the default values for the regularization parameters are not comparable enough, or we should average over more datasets to account for the randomness.

**Comment by briandesilva** [comment]
I like the idea of averaging over multiple datasets. So the idea would be that we would have the function, say, look over some nearby seed values, compute the *average* complexity for each optimizer across the different resulting datasets, then do the comparison?

**Comment by briandesilva** [comment]
Okay, I created a quick PR #75 implementing the averaging idea. Let me know what you think.
