### ISSUE TITLE
Prepare a major release

### ISSUE THREAD

**Issue by Ohjeah** [dynamicslab/pysindy#76]
After our JOSS submission has been accepted, we should release a major version of pysindy.

**Comment by briandesilva** [comment]
@Ohjeah, we have been asked by a JOSS editor to create a release and to obtain a DOI for it. Do you think this is a good opportunity to make a major release (i.e. v1.0)?

**Comment by Ohjeah** [comment]
Yes I think so. We will also make the promise not to break the API until version 2.

**Comment by briandesilva** [comment]
Okay, I'll create one now.
