### ISSUE TITLE
[BUG] model.score does not return correct values when using default r2_score

### ISSUE THREAD

**Issue by ruslanmustafin** [dynamicslab/pysindy#80]
As per [scikit-learn r2_score documentation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html), the function expects the arguments to be `y_true` followed by `y_pred`, however, in [your implementation](https://github.com/dynamicslab/pysindy/blob/master/pysindy/pysindy.py#L489) the order is reversed. Since R^2 is non-symmetric, it will produce a different score compared to correct order of arguments. This is hardly noticeable when predictions closely match the gt (score is close to 1.0), but will produce incorrect results otherwise. 

### Reproducing code example:

```python
import numpy as np

from scipy.integrate import odeint
from sklearn.metrics import r2_score

import pysindy as ps

# Control input
def u_fun(t):
    return np.column_stack([np.sin(2 * t), t ** 2])

# Lorenz equations with control input
def lorenz_control(z, t):
    u = u_fun(t)
    return [
        10 * (z[1] - z[0]) + u[0, 0] ** 2,
        z[0] * (28 - z[2]) - z[1],
        z[0] * z[1] - 8 / 3 * z[2] - u[0, 1],
    ]

# Generate measurement data
dt = .002

t_train = np.arange(0, 10, dt)
x0_train = [-8, 8, 27]
x_train = odeint(lorenz_control, x0_train, t_train)
u_train = u_fun(t_train)

# Instantiate and fit the SINDYc model
model = ps.SINDy()
model.fit(x_train, u=u_train, t=dt)

print(model.score(x_train, u=u_train, t=dt))

x_dot_test_predicted = model.predict(x_train, u=u_train)
x_dot_test_computed = model.differentiate(x_train, t=dt)

print(r2_score(x_dot_test_computed, x_dot_test_predicted))
```

This should print `0.999999960658854` and `0.999999960658851` (sorry for not providing a better example, I would have to give away our internal dataset to reproduce the issue, but in our case the score changes from 0.41 to 0.05)

### PySINDy/Python version information:

1.0.1 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 23:51:54) 
[GCC 7.3.0]

**Comment by briandesilva** [comment]
Thanks for pointing this out. The latest release, 1.0.2, fixes this issue.
