### ISSUE TITLE
 check_is_fitted() missing 1 required positional argument: 'attributes'

### ISSUE THREAD

**Issue by sameer9406** [dynamicslab/pysindy#81]
![image](https://user-images.githubusercontent.com/50555276/86750523-4e287100-c03e-11ea-8764-13a762cb1fec.png)

```python
import pysindy
<< your code here >>
```

**Comment by sameer9406** [comment]
I tried commenting the check_is_fitted()  and its working..

**Comment by briandesilva** [comment]
Thanks for pointing this out. I'll work on a fix, but in the meantime I suspect you can resolve the issue by updating your installation of scikit-learn to 0.23.

**Comment by briandesilva** [comment]
Fixed in #82.
