### ISSUE TITLE
iSindy implementation

### ISSUE THREAD

**Issue by ppgaluzio** [dynamicslab/pysindy#86]
Hello,

I was looking for a python implementation of isindy, and found this [repository](https://github.com/luckystarufo/pySINDy). There there is a deprecation message pointing to here. However I was unable to find the isindy implementation here, there is also no mention of it in the documentation and it doesn't seem to be implemented at all.

Is that a work in progress and there is an intent to bring that implementation to this package as well? That deprecation warning in the previous package, am I safe to assume that that implementation is robust and I can use that package and get reliable results?

I need to use iSindy in a project I am working on, when I saw the deprecation warning I decided to implement my own version based on the matlab code available (that also helps better understanding the algorithm, in case some adaptation is required). That went well to the first tests but due to the interface I need to implement, testing has been a little trickier than I first assumed. If that implementation is robust, I could just wrap my interface around it and make it work.

Thank you,
Paulo

**Comment by briandesilva** [comment]
Hi Paulo,

We don't have an iSINDy implementation here and we don't currently have plans to develop one. I'm not too familiar with the other implementation, but it is likely the most robust one out there (in Python). There have also been some advances in implicit SINDy [here](https://github.com/dynamicslab/SINDy-PI), but the code is written in Matlab and might not be as user-friendly as the package you linked.  Personally, I think your best bet is either the wrapping approach you mentioned, or to use PySINDy's `CustomLibrary` object to create a custom library of rational functions.

**Comment by ppgaluzio** [comment]
Hello Brian, thank you for your response.

I assumed that since that package pointed to this repository, it was a previous version of the same package. I looked to its code with more care, and it seems that some details of the implementation would need to be changed (the null space calculation, for example). In which case I think I'll try to figure out the problems in my own implementation.

I am working on a personal implementation, which is basically a translation from matlab from the code available [here](https://github.com/niallmm/iSINDy), which is giving the appropriate result for the Michaelis-Menten system, but its is failing for the "subtilis competence" example of the paper.  I am not sure whether it is the fact that I am running the system with only one realization (without multiple initial conditions) or how I am changing the value of lambda to try to determine its best value. 

Since in my data set I have a considerably large number of variables (>10), I'am not sure whether using Sindy with a `customlibrary` might be the best approach, my concern is that the size of the problem might increase too much with all the possible combinations. However, I was not familiar with this new work you sent, I will take a look and see if it helps to solve my problem. 

This implementation I am doing is inside a private larger project, but I can open-source the ISindy modules separately later, if an isindy implementation in Python is something that would interest you.

Thank you,

**Comment by briandesilva** [comment]
> I assumed that since that package pointed to this repository, it was a previous version of the same package.

Ah, I see. No, that package is not an earlier version of this one. The owner of that PySINDy package is someone in my same research group. He had the original rights to the `pysindy` name on PyPI, and was nice enough to transfer them to this implementation of SINDy since he wasn't planning on continuing development of his version. He must have added a link to this PySINDy at that time.

> I am not sure whether it is the fact that I am running the system with only one realization (without multiple initial conditions) or how I am changing the value of lambda to try to determine its best value.

I can't say for certain what's going wrong, but in my experience, using multiple initial conditions can be very beneficial, especially when they capture different qualitative behaviors of the underlying system.

> Since in my data set I have a considerably large number of variables (>10), I'am not sure whether using Sindy with a `customlibrary` might be the best approach, my concern is that the size of the problem might increase too much with all the possible combinations.

That's a valid concern. If you do decide to go down this path, be sure to increase the amount of regularization you use (e.g. set a larger value of `alpha` in `STLSQ`), because the problem is likely to become ill-conditioned.

> However, I was not familiar with this new work you sent, I will take a look and see if it helps to solve my problem.

My understanding is that the method is more robust and scales better than the original iSINDy method, but it's also more complicated.

**Comment by ppgaluzio** [comment]
Well I read the paper for the Sindy-PI method and it seems to me that it is probably the best approach, despite the increase in complexity in the implementation. In particular, my dataset is not only high dimensional but also very noisy, so robustness is of first importance. 

Thank you for your response, I can let you know if the sindy-PI implementation in python works and eventually I may have authorization from my company to open source it.
