### ISSUE TITLE
Stepwise sparse regression

### ISSUE THREAD

**Issue by briandesilva** [dynamicslab/pysindy#91]
It could be useful for us to implement the stepwise sparse regression optimization method proposed in _Sparse learning of stochastic dynamical equations_, Lorenzo Boninsegna et al., (2018) - [link](https://aip.scitation.org/doi/full/10.1063/1.5018409). See [this page](https://en.wikipedia.org/wiki/Stepwise_regression) for similar methods. The method is similar to sequentially thresholded least squares except, at each iteration, rather than eliminating _all_ coefficients of small magnitude, it eliminates the smallest one.

From the user's point of view, the biggest difference between this method and STLSQ is that this method allows one to forgo the sparsity threshold parameter and instead directly specify the desired number of nonzero coefficients. This number can also be chosen via cross-validation.

**Comment by briandesilva** [comment]
We may be able to leverage Scikit-learn's `sklearn.feature_selection.RFE` ([link](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html)) to simplify the implementation.

**Comment by akaptano** [comment]
Implemented in new branch SSR. Will submit a pull request in a moment, and marking this closed for now.
