### ISSUE TITLE
ValueError in model simulation due to wrong assumption

### ISSUE THREAD

**Issue by msis** [dynamicslab/pysindy#94]
When calling `model.simulate`, it is assumed that time `1` is can be interpolated:
https://github.com/dynamicslab/pysindy/blob/0f7ca74f45f1e76a190014f60c6eb80b22ace519/pysindy/pysindy.py#L738

This assumption is wrong is `t` is a given array.

## Example:
```python
import numpy as np

import pysindy as ps

t = np.linspace(0, 1, 100)
u = np.array([0]*100)
x = np.power(t, 2)

model = ps.SINDy()
model.fit(
    x,
    t=t,
    u=u,
)
print(model.print())

def gen_u(t):
    return t

x0 = 6

t_test_success = np.arange(0, 1.1, 0.1)
u_test_success = gen_u(t_test_success)

t_test_fail = np.arange(0, 1, 0.1)
u_test_fail = gen_u(t_test_fail)

sim_success = model.simulate(
    [x0],
    t=t_test_success,
    u=u_test_success,
)
sim_fail = model.simulate(
    [x0],
    t=t_test_fail,
    u=u_test_fail,
)
```
In this example, `sim_fail` will raise a `ValueError` exception as `1` is out of the interpolation range (see linked line above).

## Proposed fix:
Replace : `if ndim(u_fun(1)) == 1: ` with `if ndim(u_fun(t[0])) == 1: `.

**Comment by briandesilva** [comment]
Thanks for pointing this out. I'll push a fix this afternoon.

**Comment by briandesilva** [comment]
Fixed in 9d5855342e58651459aa884fde5f534d8b28661f. I've got another bug fix or two in the pipeline that I'd like to bundle with this in a new release. It should be out by the end of the week. If you urgently need this fixed, feel free to clone the master branch and install it in development mode:
```bash
git clone https://github.com/dynamicslab/pysindy.git
cd pysindy
pip install -e .
```

**Comment by msis** [comment]
Thanks @briandesilva !

I've been using the following work around for my situation:
```python
sim_fail = model.simulate(
    [x0],
    t=t_test_fail-t_test_fail[0],
    u=u_test_fail,
)
```

**Comment by briandesilva** [comment]
You shifted the time to start at 0—clever!
