### ISSUE TITLE
[Bug] unbias is not applied to intercept

### ISSUE THREAD

**Issue by briandesilva** [dynamicslab/pysindy#97]
Looking at the implementation of `pysindy.optimizers.SINDyOptimizer._unbias`, it looks like we are only unbiasing the linear coefficients `coef_` but not the intercept `intercept_`.

**Comment by briandesilva** [comment]
I'm working on a simple fix, but I don't have time to test it at the moment.

**Comment by akaptano** [comment]
Issue #113 is probably relevant here
